[![](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/itmorn/AI.handbook/blob/main/DL/torch/nn/RandomSampling/RandomSampling.ipynb)

# 随机种子相关

## seed
将用于生成随机数的种子设置为非确定性随机数。返回用于随机数生成器（Random Number Generator, RNG）种子的64位数字。

**定义**：  
torch.seed()

**参数**:  
- device (torch.device, optional) – the desired device for the generator.  generator所需的设备

In [10]:
import torch

torch.seed()

409617115381600

## manual_seed
设置生成随机数的种子。返回一个torch.Generator对象。
manual_seed()用于设置RNG的种子，以确保生成的随机数序列是可重复的

**定义**：  
torch.manual_seed(seed)

**参数**:  
- seed (int) – The desired seed. Value must be within the inclusive range [-0x8000_0000_0000_0000, 0xffff_ffff_ffff_ffff]. Otherwise, a RuntimeError is raised. Negative inputs are remapped to positive values with the formula 0xffff_ffff_ffff_ffff + seed.  所需的种子。值必须包含在[-0x8000_0000_0000_0000, 0xffff_ffff_ffff]范围内

In [22]:
import torch
seed = 666
torch.manual_seed(seed)
torch.randn(5) 

tensor([-2.1188,  0.0635, -1.4555, -0.0126, -0.1548])

## initial_seed
返回当前RNG种子的初始值。该函数可以用来检查当前的RNG种子是由哪个初始种子生成的。

**定义**：  
torch.initial_seed()

In [38]:
import torch
seed = 666
torch.manual_seed(seed)
print(torch.randn(5))
print(torch.initial_seed())

print(torch.randn(5))
print(torch.initial_seed())

tensor([-2.1188,  0.0635, -1.4555, -0.0126, -0.1548])
666
tensor([-0.0927,  2.5916,  0.4542, -0.6890, -0.9962])
666


## get_rng_state
返回随机数生成器状态(torch.ByteTensor)

**定义**：  
torch.get_rng_state()

## set_rng_state
设置随机数生成器状态

**定义**：  
torch.set_rng_state(new_state)

**参数**：
- new_state (torch.ByteTensor) – The desired state

In [40]:
import torch
new_state = torch.get_rng_state()
print(new_state)
print(torch.randn(5))

torch.set_rng_state(new_state)
print(torch.randn(5))

tensor([154,   2,   0,  ...,   0,   0,   0], dtype=torch.uint8)
tensor([-0.1043, -0.5187,  0.1231,  0.0755,  0.7091])
tensor([-0.1043, -0.5187,  0.1231,  0.0755,  0.7091])


# 随机抽样

## bernoulli
从伯努利分布中抽取二进制随机数(0或1)。

$$\text{out}_i\sim\operatorname{Bernoulli}(p=\operatorname{input}_i)$$

**定义**：  
torch.bernoulli(input, *, generator=None, out=None) → Tensor

**参数**：
- input (Tensor) – the input tensor of probability values for the Bernoulli distribution   伯努利分布的概率值的输入张量

- generator (torch.Generator, optional) – a pseudorandom number generator for sampling  用于采样的伪随机数生成器

- out (Tensor, optional) – the output tensor.

In [25]:
import torch
a = torch.ones(5,5)*0.5
# torch.manual_seed(666)
torch.bernoulli(a)

tensor([[0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 1.],
        [1., 1., 1., 1., 0.],
        [0., 0., 0., 0., 1.],
        [0., 1., 1., 1., 1.]])

## multinomial
返回一个张量，其中每行包含从张量输入的相应行中抽样的多项概率分布的num_samples索引。

**定义**：  
torch.multinomial(input, num_samples, replacement=False, *, generator=None, out=None) → LongTensor

**参数**：
- input (Tensor) – the input tensor containing probabilities  包含概率的输入张量

- num_samples (int) – number of samples to draw

- replacement (bool, optional) – whether to draw with replacement or not  是否放回

- generator (torch.Generator, optional) – a pseudorandom number generator for sampling

- out (Tensor, optional) – the output tensor.

In [68]:
import torch
# create a tensor of weights
weights = torch.tensor([1, 1, 1, 5], dtype=torch.float)
torch.multinomial(input=weights, num_samples=20, replacement=True)
# 每个样本都从weights的多项式分布中抽取

tensor([0, 3, 0, 3, 3, 3, 0, 3, 2, 3, 0, 3, 3, 3, 3, 3, 3, 1, 3, 3])

## normal
返回一个从均值和标准差给定的独立正态分布中抽取的随机数张量。

**定义**：  
torch.normal(mean, std, *, generator=None, out=None) → Tensor

**参数**：
- mean (Tensor) – the tensor of per-element means  每个元素均值的张量

- std (Tensor) – the tensor of per-element standard deviations  每个元素标准差的张量

- generator (torch.Generator, optional) – a pseudorandom number generator for sampling

- out (Tensor, optional) – the output tensor.

In [71]:
torch.normal(mean=torch.arange(1., 11.), std=torch.arange(1, 0, -0.1))

tensor([-0.1790,  1.9300, -0.3390,  4.6468,  4.8345,  6.6075,  7.2050,  7.3532,
         9.1929, 10.1335])

## poisson
返回一个与输入相同大小的张量，每个元素从泊松分布中采样

$$\text{out}_i\sim\operatorname{Poisson}(\operatorname{input}_i)$$

**定义**：  
torch.poisson(input, generator=None) → Tensor

**参数**：
- input (Tensor) – the input tensor containing the rates of the Poisson distribution  包含泊松分布率的输入张量

- generator (torch.Generator, optional) – a pseudorandom number generator for sampling

In [79]:
import torch
torch.manual_seed(666)
rates = torch.rand(4, 4) * 5  # rate parameter between 0 and 5
print(rates)
torch.poisson(rates)

tensor([[1.5595, 1.3507, 0.5589, 0.5060],
        [0.9384, 0.0904, 1.6583, 0.4231],
        [2.8662, 0.0395, 1.2601, 2.7589],
        [4.3923, 2.6407, 2.4804, 4.8957]])


tensor([[2., 0., 0., 0.],
        [1., 0., 0., 0.],
        [3., 0., 2., 2.],
        [4., 5., 6., 7.]])

## rand
返回一个张量，该张量由[0,1)区间上均匀分布的随机数填充

**定义**：  
torch.rand(*size, *, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False, pin_memory=False) → Tensor

**参数**：
- size (int...) – a sequence of integers defining the shape of the output tensor. Can be a variable number of arguments or a collection like a list or tuple.  形状

- generator (torch.Generator, optional) – a pseudorandom number generator for sampling  随机数生成器

- out (Tensor, optional) – the output tensor.  将创建的tensor赋值给out，共享内存

- dtype (torch.dtype, optional) – the desired data type of returned tensor. Default: if None, uses a global default (see torch.set_default_tensor_type()).  返回张量的期望数据类型。

- layout (torch.layout, optional) – the desired layout of returned Tensor. Default: torch.strided.  返回张量的期望布局

- device (torch.device, optional) – the desired device of returned tensor. Default: if None, uses the current device for the default tensor type (see torch.set_default_tensor_type()). device will be the CPU for CPU tensor types and the current CUDA device for CUDA tensor types.  张量的期望设备

- requires_grad (bool, optional) – If autograd should record operations on the returned tensor. Default: False.  是否记录张量的梯度

- pin_memory (bool, optional) – If set, returned tensor would be allocated in the pinned memory. Works only for CPU tensors. Default: False.  如果设置，返回的张量将分配到固定内存中。
pin_memory 是 PyTorch 中一种优化技术，它可以在 CPU 和 GPU 之间高速地复制数据，以加速数据的传输。在 PyTorch 中，可以通过在 Dataset 类中设置 pin_memory=True 来启用 pin_memory 技术。需要注意的是，pin_memory 技术需要更多的内存来存储固定内存区域中的数据，因此如果内存有限，可能需要考虑关闭 pin_memory 技术。

In [81]:
import torch
torch.manual_seed(666)
torch.rand(4)
torch.rand(2, 3)

tensor([[0.1877, 0.0181, 0.3317],
        [0.0846, 0.5732, 0.0079]])

## rand_like
返回一个与输入大小相同的张量，该张量由[0,1)区间上均匀分布的随机数填充

**定义**：  
torch.rand_like(input, *, dtype=None, layout=None, device=None, requires_grad=False, memory_format=torch.preserve_format) → Tensor

**参数**：
- input (Tensor) – the size of input will determine size of the output tensor.  输入的大小将决定输出张量的大小

- dtype (torch.dtype, optional) – the desired data type of returned Tensor. Default: if None, defaults to the dtype of input.  返回张量的期望数据类型

- layout (torch.layout, optional) – the desired layout of returned tensor. Default: if None, defaults to the layout of input.  返回张量的期望布局

- device (torch.device, optional) – the desired device of returned tensor. Default: if None, defaults to the device of input.  返回张量的期望设备。
 
- requires_grad (bool, optional) – If autograd should record operations on the returned tensor. Default: False.  是否记录张量的梯度

- memory_format (torch.memory_format, optional) – the desired memory format of returned Tensor. Default: torch.preserve_format.  返回的张量的期望内存格式

In [86]:
import torch
torch.manual_seed(666)
a = torch.ones(2, 3)
torch.rand_like(a)

tensor([[0.3119, 0.2701, 0.1118],
        [0.1012, 0.1877, 0.0181]])

## randint

**定义**：  
torch.randint(low=0, high, size, *, generator=None, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False) → Tensor

**参数**：
- low (int, optional) – Lowest integer to be drawn from the distribution. Default: 0.  从分布中抽取的最小整数。默认值:0。

- high (int) – One above the highest integer to be drawn from the distribution.  从分布中抽取的最大整数，不包括。

- size (tuple) – a tuple defining the shape of the output tensor.  定义输出张量形状的元组。

- generator (torch.Generator, optional) – a pseudorandom number generator for sampling

- out (Tensor, optional) – the output tensor.

- dtype (torch.dtype, optional) – if None, this function returns a tensor with dtype torch.int64.

- layout (torch.layout, optional) – the desired layout of returned Tensor. Default: torch.strided.

- device (torch.device, optional) – the desired device of returned tensor. Default: if None, uses the current device for the default tensor type (see torch.set_default_tensor_type()). device will be the CPU for CPU tensor types and the current CUDA device for CUDA tensor types.

- requires_grad (bool, optional) – If autograd should record operations on the returned tensor. Default: False.

In [122]:
import torch
torch.randint(low=1, high=3, size=(5, 5))

tensor([[1, 2, 2, 1, 2],
        [2, 1, 1, 1, 2],
        [1, 2, 1, 1, 1],
        [2, 1, 2, 1, 1],
        [2, 2, 1, 1, 1]])

## randint_like
返回一个与张量输入形状相同的张量，填充在low(包含)和high(不包含)之间均匀生成的随机整数。

**定义**：  
torch.randint_like(input, low=0, high, *, dtype=None, layout=torch.strided, device=None, requires_grad=False, memory_format=torch.preserve_format) → Tensor

**参数**：
- input (Tensor) – the size of input will determine size of the output tensor.  输入的大小将决定输出张量的大小。

- low (int, optional) – Lowest integer to be drawn from the distribution. Default: 0.

- high (int) – One above the highest integer to be drawn from the distribution.

- dtype (torch.dtype, optional) – the desired data type of returned Tensor. Default: if None, defaults to the dtype of input.

- layout (torch.layout, optional) – the desired layout of returned tensor. Default: if None, defaults to the layout of input.

- device (torch.device, optional) – the desired device of returned tensor. Default: if None, defaults to the device of input.

- requires_grad (bool, optional) – If autograd should record operations on the returned tensor. Default: False.

- memory_format (torch.memory_format, optional) – the desired memory format of returned Tensor. Default: torch.preserve_format.

In [129]:
import torch
a = torch.ones(3,3)
torch.randint_like(input=a,low=0,high=2)

tensor([[0., 1., 1.],
        [1., 0., 0.],
        [1., 0., 1.]])

## randn
返回一个由均值为0，方差为1的正态分布(也称为标准正态分布)中的随机数填充的张量。
$$\text{out}_i\sim\mathcal{N}(0,1)$$

**定义**：  
torch.randn(*size, *, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False, pin_memory=False) → Tensor

**参数**：
- size (int...) – a sequence of integers defining the shape of the output tensor. Can be a variable number of arguments or a collection like a list or tuple.

- generator (torch.Generator, optional) – a pseudorandom number generator for sampling

- out (Tensor, optional) – the output tensor.

- dtype (torch.dtype, optional) – the desired data type of returned tensor. Default: if None, uses a global default (see torch.set_default_tensor_type()).

- layout (torch.layout, optional) – the desired layout of returned Tensor. Default: torch.strided.

- device (torch.device, optional) – the desired device of returned tensor. Default: if None, uses the current device for the default tensor type (see torch.set_default_tensor_type()). device will be the CPU for CPU tensor types and the current CUDA device for CUDA tensor types.

- requires_grad (bool, optional) – If autograd should record operations on the returned tensor. Default: False.

- pin_memory (bool, optional) – If set, returned tensor would be allocated in the pinned memory. Works only for CPU tensors. Default: False.

In [131]:
import torch
torch.randn(2, 3)

tensor([[-0.3615,  0.4625, -0.6849],
        [-1.7486, -1.5345, -0.9446]])

## randn_like

**定义**：  
torch.randn_like(input, *, dtype=None, layout=None, device=None, requires_grad=False, memory_format=torch.preserve_format) → Tensor

**参数**：
- input (Tensor) – the size of input will determine size of the output tensor.  输入的大小将决定输出张量的大小。

- dtype (torch.dtype, optional) – the desired data type of returned Tensor. Default: if None, defaults to the dtype of input.

- layout (torch.layout, optional) – the desired layout of returned tensor. Default: if None, defaults to the layout of input.

- device (torch.device, optional) – the desired device of returned tensor. Default: if None, defaults to the device of input.

- requires_grad (bool, optional) – If autograd should record operations on the returned tensor. Default: False.

- memory_format (torch.memory_format, optional) – the desired memory format of returned Tensor. Default: torch.preserve_format.

In [134]:
import torch
a = torch.ones(3,3)
torch.randn_like(input=a)

tensor([[-0.8604,  0.3904,  3.3089],
        [ 0.5811,  1.6342, -1.5522],
        [ 1.0125,  1.3283, -0.6265]])

## randperm
返回从0到n - 1的整数的随机排列。

**定义**：  
torch.randperm(n, *, generator=None, out=None, dtype=torch.int64, layout=torch.strided, device=None, requires_grad=False, pin_memory=False) → Tensor

**参数**：
- n (int) – the upper bound (exclusive)  上限(不包含)

- generator (torch.Generator, optional) – a pseudorandom number generator for sampling

- out (Tensor, optional) – the output tensor.

- dtype (torch.dtype, optional) – the desired data type of returned tensor. Default: torch.int64.

- layout (torch.layout, optional) – the desired layout of returned Tensor. Default: torch.strided.

- device (torch.device, optional) – the desired device of returned tensor. Default: if None, uses the current device for the default tensor type (see torch.set_default_tensor_type()). device will be the CPU for CPU tensor types and the current CUDA device for CUDA tensor types.

- requires_grad (bool, optional) – If autograd should record operations on the returned tensor. Default: False.

- pin_memory (bool, optional) – If set, returned tensor would be allocated in the pinned memory. Works only for CPU tensors. Default: False.

In [139]:
import torch
torch.randperm(4)

tensor([1, 3, 0, 2])

## xxx

**定义**：  


**参数**：
- 

## xxx

**定义**：  


**参数**：
- 

## xxx

**定义**：  


**参数**：
- 