[![](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/itmorn/AI.handbook/blob/main/DL/torch/torch/Tensors/Tensors.ipynb)

# is_tensor
Returns True if obj is a PyTorch tensor.  

如果obj是一个PyTorch张量，则返回True。

In [2]:
import torch

x=torch.tensor([1,2,3])
torch.is_tensor(x)

True

# is_storage
	
Returns True if obj is a PyTorch storage object.  

如果obj是PyTorch存储对象，则返回True。

在PyTorch中，存储对象（torch.Storage）是一个比张量更底层的数据结构，用于存储和管理数据。与张量不同，存储对象不包含任何形状和维度信息，它们只是简单的一维数组。

在实际应用中，存储对象可能不太常用，但它们在某些情况下可以提供性能优势。以下是一些常见的使用场景：

1. 在使用自定义的数据类型或格式时，存储对象可以提供一种更灵活的数据存储方式。例如，如果要存储稀疏矩阵，则存储对象可以更有效地存储非零元素。

2. 存储对象可以提供一种更高效的内存管理方式，特别是在处理大型数据集时。例如，在处理大型图像或音频数据时，使用存储对象可以更有效地管理内存和数据加载。

3. 存储对象可以用于实现自定义张量操作，例如，可以将存储对象用于实现卷积和池化操作中的内部存储。

总之，使用存储对象需要对PyTorch底层的内存管理和数据操作有一定的了解，但它们可以在某些情况下提供性能优势。通常情况下，如果不需要直接访问存储对象，则建议使用张量来管理数据。

In [7]:
import torch

storage = torch.FloatStorage(10)
print(torch.is_storage(storage))


x=torch.tensor([1,2,3])
print(torch.is_storage(x))

True
False


# is_complex
	
Returns True if the data type of input is a complex data type i.e., one of torch.complex64, and torch.complex128.  

如果输入数据的数据类型是复数类型，即torch.complex64或torch.complex128，则返回True。

In [9]:
import torch

x = torch.tensor([1+2j, 3-4j], dtype=torch.complex128)

print(torch.is_complex(x))  # True
# 在这个例子中，我们创建了一个数据类型为torch.complex128的复数张量x，
# 然后使用torch.is_complex()函数检查x的数据类型是否为复数类型，结果返回True。

True


# is_conj

Returns True if the input is a conjugated tensor, i.e. its conjugate bit is set to True.

如果输入的张量是共轭张量，即其共轭标志位(conjugate bit)设置为True，则返回True。

在数学中，一个复数的共轭是将其虚部变号，实部不变的一种操作。类似地，对于一个复数张量，将其每个元素共轭得到的新张量称为共轭张量(conjugate tensor)。

在PyTorch中，使用torch.conj()函数可以求得一个张量的共轭张量。共轭张量在信号处理、光学等领域中有广泛的应用。

In [12]:
import torch

x = torch.tensor([1+2j, 3-4j], dtype=torch.complex128)
y = torch.conj(x)

print(torch.is_conj(y))  # True
y

False


tensor([1.-2.j, 3.+4.j], dtype=torch.complex128)

# is_floating_point
	
Returns True if the data type of input is a floating point data type i.e., one of torch.float64, torch.float32, torch.float16, and torch.bfloat16.

如果输入数据的数据类型是浮点数类型，即torch.float64、torch.float32、torch.float16或torch.bfloat16之一，则返回True。

In [13]:
import torch

x = torch.tensor([1.0, 2.0, 3.0])
y = torch.tensor([1, 2, 3])

print(torch.is_floating_point(x))  # True
print(torch.is_floating_point(y))  # False

True
False


# is_nonzero
	
Returns True if the input is a single element tensor which is not equal to zero after type conversions.

如果输入是一个单元素张量，并且在类型转换后不等于零，即不等于torch.tensor([0.])、torch.tensor([0])或torch.tensor([False])，则返回True。如果torch.numel()不等于1（即张量元素个数不为1），则抛出一个运行时错误。

In [14]:
import torch

x = torch.tensor([3], dtype=torch.float32)
y = torch.tensor([0])
z = torch.tensor([True])

print(torch.is_nonzero(x))  # True
print(torch.is_nonzero(y))  # False
print(torch.is_nonzero(z))  # True

True
False
True


# set_default_dtype
	
Sets the default floating point dtype to d.

将默认的浮点数数据类型设置为d。支持输入torch.float32和torch.float64。其他数据类型可能会被接受但不会报错，但不受支持，可能不会按预期工作。

# get_default_dtype

Get the current default floating point torch.dtype.

获取默认浮点数数据类型

In [6]:
import torch

torch.set_default_dtype(torch.float32) #默认
print(torch.get_default_dtype())  # torch.float32
print(torch.tensor([1.2, 3]).dtype)
print(torch.tensor([1.2, 3j]).dtype)
print("="*50)
torch.set_default_dtype(torch.float64)
print(torch.get_default_dtype())
print(torch.tensor([1.2, 3]).dtype)
print(torch.tensor([1.2, 3j]).dtype)

torch.float32
torch.float32
torch.complex64
torch.float64
torch.float64
torch.complex128


# set_default_tensor_type

Sets the default torch.Tensor type to floating point tensor type t.

将默认的torch.Tensor类型设置为浮点数张量类型t。

In [2]:
import torch

torch.set_default_tensor_type(torch.FloatTensor)
print(torch.tensor([1.2, 3]).dtype)

torch.set_default_tensor_type(torch.DoubleTensor)
print(torch.tensor([1.2, 3]).dtype)


torch.float32
torch.float64


# set_default_tensor_type和set_default_dtype的适用场景
set_default_tensor_type()
- 当你需要在不同设备上运行代码时，可以使用set_default_tensor_type()设置默认的张量类型。例如，如果你需要在GPU上训练模型，可以将默认的张量类型设置为torch.cuda.FloatTensor，这样在创建新的张量时将默认使用这种类型。

- 当你需要在创建大量的张量时，可以使用set_default_tensor_type()设置默认的张量类型。例如，在生成大量数据集时，如果你需要使用GPU加速，可以将默认的张量类型设置为torch.cuda.FloatTensor。


set_default_dtype()
- 当你需要在执行数学运算时使用特定的数据类型时，可以使用set_default_dtype()设置默认的数据类型。例如，在数值计算中，float32通常足够精确，但在某些情况下，你可能需要更高的精度，这时你可以将默认的数据类型设置为float64。

- 当你需要在创建张量时，使用与上下文匹配的默认数据类型时，可以使用set_default_dtype()设置默认的数据类型。例如，当你需要在不同计算机上运行相同的代码时，可以使用这个函数来确保数据类型在各种环境中的一致性。

需要注意的是，这两个函数都是全局设置，会影响到整个程序，因此在使用它们时需要谨慎。

# numel
Returns the total number of elements in the input tensor.
返回输入张量中元素的总数。

In [3]:
import torch

x = torch.randn(2, 3)
num_elements = torch.numel(x)
print(num_elements)  # 输出 6

6


# set_printoptions
Set options for printing.

torch.set_printoptions函数可以用于设置张量打印的选项，包括精度、格式等。

In [6]:
import torch

# Limit the precision of elements
torch.set_printoptions(precision=2)
print(torch.tensor([1.12345]))

# Limit the number of elements shown
torch.set_printoptions(threshold=5)
print(torch.arange(10))

# Restore defaults
torch.set_printoptions(profile='default')
print(torch.tensor([1.12345]))
print(torch.arange(10))


tensor([1.12])
tensor([0, 1, 2,  ..., 7, 8, 9])
tensor([1.1235])
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


# set_flush_denormal
Disables denormal floating numbers on CPU.

禁用CPU上的非规格化浮点数。

在计算机科学中，非规格化浮点数是一种特殊的浮点数形式，其指数位为全0而尾数位非0。这种数通常表示接近于0的数值，但具有较低的精度和性能代价。禁用非规格化浮点数可以提高计算精度和效率。


 当在CPU上执行大量的浮点计算时，将浮点数规范化为正常值可能会降低性能。 因此，禁用浮点数规范化可能会提高性能。 但是，请注意，禁用规范化可能会影响计算的精度，并且可能会导致不一致的行为。 因此，应该在使用之前进行仔细的测试和评估，确保其对应用程序的性能和精度产生积极的影响。
