[![](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/itmorn/AI.handbook/blob/main/DL/torch/torch/Tensors/Tensors.ipynb)

# 类型判断、全局设置

## is_tensor
Returns True if obj is a PyTorch tensor.  

如果obj是一个PyTorch张量，则返回True。

In [2]:
import torch

x=torch.tensor([1,2,3])
torch.is_tensor(x)

True

## is_storage
	
Returns True if obj is a PyTorch storage object.  

如果obj是PyTorch存储对象，则返回True。

在PyTorch中，存储对象（torch.Storage）是一个比张量更底层的数据结构，用于存储和管理数据。与张量不同，存储对象不包含任何形状和维度信息，它们只是简单的一维数组。

在实际应用中，存储对象可能不太常用，但它们在某些情况下可以提供性能优势。以下是一些常见的使用场景：

1. 在使用自定义的数据类型或格式时，存储对象可以提供一种更灵活的数据存储方式。例如，如果要存储稀疏矩阵，则存储对象可以更有效地存储非零元素。

2. 存储对象可以提供一种更高效的内存管理方式，特别是在处理大型数据集时。例如，在处理大型图像或音频数据时，使用存储对象可以更有效地管理内存和数据加载。

3. 存储对象可以用于实现自定义张量操作，例如，可以将存储对象用于实现卷积和池化操作中的内部存储。

总之，使用存储对象需要对PyTorch底层的内存管理和数据操作有一定的了解，但它们可以在某些情况下提供性能优势。通常情况下，如果不需要直接访问存储对象，则建议使用张量来管理数据。

In [7]:
import torch

storage = torch.FloatStorage(10)
print(torch.is_storage(storage))


x=torch.tensor([1,2,3])
print(torch.is_storage(x))

True
False


## is_complex
	
Returns True if the data type of input is a complex data type i.e., one of torch.complex64, and torch.complex128.  

如果输入数据的数据类型是复数类型，即torch.complex64或torch.complex128，则返回True。

In [9]:
import torch

x = torch.tensor([1+2j, 3-4j], dtype=torch.complex128)

print(torch.is_complex(x))  # True
# 在这个例子中，我们创建了一个数据类型为torch.complex128的复数张量x，
# 然后使用torch.is_complex()函数检查x的数据类型是否为复数类型，结果返回True。

True


## is_conj

Returns True if the input is a conjugated tensor, i.e. its conjugate bit is set to True.

如果输入的张量是共轭张量，即其共轭标志位(conjugate bit)设置为True，则返回True。

在数学中，一个复数的共轭是将其虚部变号，实部不变的一种操作。类似地，对于一个复数张量，将其每个元素共轭得到的新张量称为共轭张量(conjugate tensor)。

在PyTorch中，使用torch.conj()函数可以求得一个张量的共轭张量。共轭张量在信号处理、光学等领域中有广泛的应用。

In [12]:
import torch

x = torch.tensor([1+2j, 3-4j], dtype=torch.complex128)
y = torch.conj(x)

print(torch.is_conj(y))  # True
y

False


tensor([1.-2.j, 3.+4.j], dtype=torch.complex128)

## is_floating_point
	
Returns True if the data type of input is a floating point data type i.e., one of torch.float64, torch.float32, torch.float16, and torch.bfloat16.

如果输入数据的数据类型是浮点数类型，即torch.float64、torch.float32、torch.float16或torch.bfloat16之一，则返回True。

In [13]:
import torch

x = torch.tensor([1.0, 2.0, 3.0])
y = torch.tensor([1, 2, 3])

print(torch.is_floating_point(x))  # True
print(torch.is_floating_point(y))  # False

True
False


## is_nonzero
	
Returns True if the input is a single element tensor which is not equal to zero after type conversions.

如果输入是一个单元素张量，并且在类型转换后不等于零，即不等于torch.tensor([0.])、torch.tensor([0])或torch.tensor([False])，则返回True。如果torch.numel()不等于1（即张量元素个数不为1），则抛出一个运行时错误。

In [14]:
import torch

x = torch.tensor([3], dtype=torch.float32)
y = torch.tensor([0])
z = torch.tensor([True])

print(torch.is_nonzero(x))  # True
print(torch.is_nonzero(y))  # False
print(torch.is_nonzero(z))  # True

True
False
True


## set_default_dtype
	
Sets the default floating point dtype to d.

将默认的浮点数数据类型设置为d。支持输入torch.float32和torch.float64。其他数据类型可能会被接受但不会报错，但不受支持，可能不会按预期工作。

## get_default_dtype

Get the current default floating point torch.dtype.

获取默认浮点数数据类型

In [6]:
import torch

torch.set_default_dtype(torch.float32) #默认
print(torch.get_default_dtype())  # torch.float32
print(torch.tensor([1.2, 3]).dtype)
print(torch.tensor([1.2, 3j]).dtype)
print("="*50)
torch.set_default_dtype(torch.float64)
print(torch.get_default_dtype())
print(torch.tensor([1.2, 3]).dtype)
print(torch.tensor([1.2, 3j]).dtype)

torch.float32
torch.float32
torch.complex64
torch.float64
torch.float64
torch.complex128


## set_default_tensor_type

Sets the default torch.Tensor type to floating point tensor type t.

将默认的torch.Tensor类型设置为浮点数张量类型t。

In [2]:
import torch

torch.set_default_tensor_type(torch.FloatTensor)
print(torch.tensor([1.2, 3]).dtype)

torch.set_default_tensor_type(torch.DoubleTensor)
print(torch.tensor([1.2, 3]).dtype)


torch.float32
torch.float64


## set_default_tensor_type和set_default_dtype的适用场景
set_default_tensor_type()
- 当你需要在不同设备上运行代码时，可以使用set_default_tensor_type()设置默认的张量类型。例如，如果你需要在GPU上训练模型，可以将默认的张量类型设置为torch.cuda.FloatTensor，这样在创建新的张量时将默认使用这种类型。

- 当你需要在创建大量的张量时，可以使用set_default_tensor_type()设置默认的张量类型。例如，在生成大量数据集时，如果你需要使用GPU加速，可以将默认的张量类型设置为torch.cuda.FloatTensor。


set_default_dtype()
- 当你需要在执行数学运算时使用特定的数据类型时，可以使用set_default_dtype()设置默认的数据类型。例如，在数值计算中，float32通常足够精确，但在某些情况下，你可能需要更高的精度，这时你可以将默认的数据类型设置为float64。

- 当你需要在创建张量时，使用与上下文匹配的默认数据类型时，可以使用set_default_dtype()设置默认的数据类型。例如，当你需要在不同计算机上运行相同的代码时，可以使用这个函数来确保数据类型在各种环境中的一致性。

需要注意的是，这两个函数都是全局设置，会影响到整个程序，因此在使用它们时需要谨慎。

## numel
Returns the total number of elements in the input tensor.
返回输入张量中元素的总数。

In [3]:
import torch

x = torch.randn(2, 3)
num_elements = torch.numel(x)
print(num_elements)  # 输出 6

6


## set_printoptions
Set options for printing.

torch.set_printoptions函数可以用于设置张量打印的选项，包括精度、格式等。

In [6]:
import torch

# Limit the precision of elements
torch.set_printoptions(precision=2)
print(torch.tensor([1.12345]))

# Limit the number of elements shown
torch.set_printoptions(threshold=5)
print(torch.arange(10))

# Restore defaults
torch.set_printoptions(profile='default')
print(torch.tensor([1.12345]))
print(torch.arange(10))


tensor([1.12])
tensor([0, 1, 2,  ..., 7, 8, 9])
tensor([1.1235])
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


## set_flush_denormal
Disables denormal floating numbers on CPU.

禁用CPU上的非规格化浮点数。

在计算机科学中，非规格化浮点数是一种特殊的浮点数形式，其指数位为全0而尾数位非0。这种数通常表示接近于0的数值，但具有较低的精度和性能代价。禁用非规格化浮点数可以提高计算精度和效率。


 当在CPU上执行大量的浮点计算时，将浮点数规范化为正常值可能会降低性能。 因此，禁用浮点数规范化可能会提高性能。 但是，请注意，禁用规范化可能会影响计算的精度，并且可能会导致不一致的行为。 因此，应该在使用之前进行仔细的测试和评估，确保其对应用程序的性能和精度产生积极的影响。


# 创建操作

## tensor
在PyTorch中，当我们使用torch.Tensor()或者torch.tensor()函数创建一个新的张量时，这个张量就会被标记为“无autograd history”，也就是说，它没有任何与自动求导相关的历史记录。这意味着我们不能对这个张量进行自动求导。


**定义**：
torch.tensor(data, *, dtype=None, device=None, requires_grad=False, pin_memory=False) → Tensor

**参数**：
- data (array_like) – Initial data for the tensor. Can be a list, tuple, NumPy ndarray, scalar, and other types.  张量的初始数据。可以是列表、元组、NumPy ndarray、标量和其他类型。

- dtype (torch.dtype, optional) – the desired data type of returned tensor. Default: if None, infers data type from data.   返回张量的期望数据类型。默认值:如果为None，则从数据推断数据类型。

- device (torch.device, optional) – the device of the constructed tensor. If None and data is a tensor then the device of data is used. If None and data is not a tensor then the result tensor is constructed on the CPU.  构造张量的设备。如果None且data是一个张量，则使用data的设备。如果None且data不是一个张量，那么结果张量将在CPU上构造。

- requires_grad (bool, optional) – If autograd should record operations on the returned tensor. Default: False.  是否记录张量的梯度

- pin_memory (bool, optional) – If set, returned tensor would be allocated in the pinned memory. Works only for CPU tensors. Default: False.  如果设置，返回的张量将分配到固定内存中。
pin_memory 是 PyTorch 中一种优化技术，它可以在 CPU 和 GPU 之间高速地复制数据，以加速数据的传输。在 PyTorch 中，可以通过在 Dataset 类中设置 pin_memory=True 来启用 pin_memory 技术。需要注意的是，pin_memory 技术需要更多的内存来存储固定内存区域中的数据，因此如果内存有限，可能需要考虑关闭 pin_memory 技术。

In [6]:
import torch
print(torch.tensor([[0.1, 1.2], [2.2, 3.1], [4.9, 5.2]]))

print(torch.tensor([0, 1]))  # Type inference on data

print(torch.tensor([0.5, 1],requires_grad=True))  # Type inference on data

print(torch.tensor([[0.11111, 0.222222, 0.3333333]],
             dtype=torch.float64,
             device=torch.device('cpu')) )
            #  device=torch.device('cuda:0'))  # creates a double tensor on a CUDA device

print(torch.tensor(3.14159))  # Create a zero-dimensional (scalar) tensor

print(torch.tensor([]))  # Create an empty tensor (of size (0,))

tensor([[0.1000, 1.2000],
        [2.2000, 3.1000],
        [4.9000, 5.2000]])
tensor([0, 1])
tensor([0.5000, 1.0000], requires_grad=True)
tensor([[0.1111, 0.2222, 0.3333]], dtype=torch.float64)
tensor(3.1416)
tensor([])


## sparse_coo_tensor
sparse_coo_tensor 是一种用于创建稀疏张量的函数。稀疏张量是一种特殊的张量，其中只有一小部分元素是非零值，大部分元素都是零值。与密集张量相比，稀疏张量可以更高效地存储和计算，因为它们只需要存储非零值和对应的索引。

 **定义**：
 torch.sparse_coo_tensor(indices, values, size=None, *, dtype=None, device=None, requires_grad=False) → Tensor

**参数**：
- indices (array_like) – Initial data for the tensor. Can be a list, tuple, NumPy ndarray, scalar, and other types. Will be cast to a torch.LongTensor internally. The indices are the coordinates of the non-zero values in the matrix, and thus should be two-dimensional where the first dimension is the number of tensor dimensions and the second dimension is the number of non-zero values.  一个二维的 LongTensor，表示非零元素的索引。

- values (array_like) – Initial values for the tensor. Can be a list, tuple, NumPy ndarray, scalar, and other types.    一个一维的 Tensor，表示非零元素的值。

- size (list, tuple, or torch.Size, optional) – Size of the sparse tensor. If not provided the size will be inferred as the minimum size big enough to hold all non-zero elements.  一个元组，表示稀疏张量的形状。

- dtype (torch.dtype, optional) – the desired data type of returned tensor. Default: if None, infers data type from values.   返回张量的期望数据类型。默认值:如果为None，则从值推断数据类型。

- device (torch.device, optional) – the desired device of returned tensor. Default: if None, uses the current device for the default tensor type (see torch.set_default_tensor_type()). device will be the CPU for CPU tensor types and the current CUDA device for CUDA tensor types.  返回张量的期望设备

- requires_grad (bool, optional) – If autograd should record operations on the returned tensor. Default: False.   是否记录张量的梯度

In [18]:
import torch

i = torch.tensor([[0, 1, 1],
                  [2, 0, 2]])
v = torch.tensor([3, 4, 5], dtype=torch.float32)
sparse_tensor = torch.sparse_coo_tensor(i, v, [2, 4])
print(sparse_tensor.to_dense())

sparse_tensor = torch.sparse_coo_tensor(i, v)  # Shape inference
print(sparse_tensor.to_dense())

sparse_tensor = torch.sparse_coo_tensor(i, v, [2, 4],
                        dtype=torch.float64)
print(sparse_tensor.to_dense())

tensor([[0., 0., 3., 0.],
        [4., 0., 5., 0.]])
tensor([[0., 0., 3.],
        [4., 0., 5.]])
tensor([[0., 0., 3., 0.],
        [4., 0., 5., 0.]], dtype=torch.float64)


## asarray
将obj转换为一个张量。

 **定义**：
torch.asarray(obj, *, dtype=None, device=None, copy=None, requires_grad=False) → Tensor

**参数**：
- obj (object) – a tensor, NumPy array, DLPack Capsule, object that implements Python’s buffer protocol, scalar, or sequence of scalars.  一个张量，NumPy数组，DLPack胶囊，实现Python的缓冲区协议，标量或标量序列的对象。

- dtype (torch.dtype, optional) – the datatype of the returned tensor. Default: None, which causes the datatype of the returned tensor to be inferred from obj.  返回张量的数据类型

- copy (bool, optional) – controls whether the returned tensor shares memory with obj. Default: None, which causes the returned tensor to share memory with obj whenever possible. If True then the returned tensor does not share its memory. If False then the returned tensor shares its memory with obj and an error is thrown if it cannot.    控制返回的张量是否与obj共享内存。默认值:None，这使得返回的张量尽可能地与obj共享内存.

- device (torch.device, optional) – the device of the returned tensor. Default: None, which causes the device of obj to be used.  返回张量的设备

- requires_grad (bool, optional) – whether the returned tensor requires grad. Default: False, which causes the returned tensor not to require a gradient. If True, then the returned tensor will require a gradient, and if obj is also a tensor with an autograd history then the returned tensor will have the same history.   是否记录张量的梯度


In [26]:
import torch
a = torch.tensor([1, 2, 3])
# Shares memory with tensor 'a'
b = torch.asarray(a)
print(a.data_ptr() == b.data_ptr())

# Forces memory copy
c = torch.asarray(a, copy=True)
print(a.data_ptr() == c.data_ptr()) # 数据指针

True
False


In [31]:
import torch
a = torch.tensor([1., 2, 3], requires_grad=True)
b = a + 2

# Shares memory with tensor 'b', with no grad
c = torch.asarray(b)
print(c)

# Shares memory with tensor 'b', retaining autograd history
d = torch.asarray(b, requires_grad=True)
d

tensor([3., 4., 5.])


tensor([3., 4., 5.], grad_fn=<AddBackward0>)

In [55]:
import torch
import numpy

array = numpy.array([1, 2, 3])
# Shares memory with array 'array'
t1 = torch.asarray(array)
print(array.__array_interface__['data'][0] == t1.data_ptr())

# Copies memory due to dtype mismatch
t2 = torch.asarray(array, dtype=torch.float32)
print(array.__array_interface__['data'][0] == t2.data_ptr())

True
False


## as_tensor
将数据转换为一个张量，如果可能的话，共享数据并保存自动梯度历史。

如果数据已经是具有所请求的dtype和device的张量，则返回数据本身，但如果数据是具有不同dtype或device的张量，则复制它，就像使用数据一样。


对于 NumPy 数组，确实可以使用 copy=False 的方式来控制是否共享内存。但是对于其他类型的输入数据（如 Python 列表、Python 元组等），copy=False 并不能控制内存共享。此外，即使是对于 NumPy 数组，使用 copy=False 也并不总是能够共享内存，这取决于输入数组是否满足共享内存的条件。

相比之下，torch.as_tensor() 的共享内存特性更加稳定和可靠，它可以确保在所有情况下都尽可能地共享内存，而不需要依赖于输入数据的类型和属性。另外，torch.as_tensor() 还提供了更精细的控制，例如可以指定数据类型、设备等参数，以满足不同的需求。

因此，在需要共享内存和更精细控制输出张量属性的情况下，推荐使用 torch.as_tensor()。而如果只是简单地将 NumPy 数组或标量转换为 PyTorch 张量，而不需要特别控制输出张量的属性，那么 torch.asarray() 也是一个不错的选择。

 **定义**：
 torch.as_tensor(data, dtype=None, device=None) → Tensor

**参数**：
- data (array_like) – Initial data for the tensor. Can be a list, tuple, NumPy ndarray, scalar, and other types.  张量的初始数据。可以是列表、元组、NumPy ndarray、标量和其他类型。

- dtype (torch.dtype, optional) – the desired data type of returned tensor. Default: if None, infers data type from data.  返回张量的期望数据类型。默认值:如果为None，则从数据推断数据类型。

- device (torch.device, optional) – the device of the constructed tensor. If None and data is a tensor then the device of data is used. If None and data is not a tensor then the result tensor is constructed on the CPU.  构造张量的设备。如果None且data是一个张量，则使用data的设备。如果None且data不是一个张量，那么结果张量将在CPU上构造。

In [56]:
import torch
import numpy
a = numpy.array([1, 2, 3])
t = torch.as_tensor(a)
t[0] = -1
print(a)

[-1  2  3]


In [59]:
import torch
import numpy

a = numpy.array([1, 2, 3])
t = torch.as_tensor(a, dtype=torch.float64)
# t = torch.as_tensor(a, device=torch.device('cuda'))
t[0] = -1
print(a)

[1 2 3]


## as_strided
torch.as_strided是一个 PyTorch 的张量操作函数，它可以基于现有的张量创建一个新的张量，该新张量具有指定大小和步幅的视图。

具体来说，该函数会将输入张量 input 视为一个一维的存储（即将多维张量展平为一维），并根据指定的大小 size 和步幅 stride 重新构造一个新的张量。新张量的形状和大小由 size 参数决定，步幅由 stride 参数决定。具体地，新张量在第 i 维的步幅为 stride[i]，大小为 size[i]。

storage_offset 参数表示新张量在存储中的偏移量，可以用于构造多个视图共享相同的存储空间。如果不指定 storage_offset 参数，则默认为 0。

需要注意的是，使用 torch.as_strided() 构造的新张量仅仅是输入张量的视图，它与输入张量共享存储空间。如果输入张量的数据发生改变，那么新张量的数据也会相应地改变。

使用 torch.as_strided() 函数需要非常小心，因为它可以创建一些不符合规范的张量，例如张量的视图可能会超出存储的边界，或者在处理时可能会出现内存访问错误等问题。因此，通常情况下不建议直接使用该函数，而是建议使用更安全的张量操作函数来实现相应的功能。

 **定义**：
torch.as_strided(input, size, stride, storage_offset=None) → Tensor

**参数**：
- input (Tensor) – the input tensor.  输入张量

- size (tuple or ints) – the shape of the output tensor  输出张量的形状

- stride (tuple or ints) – the stride of the output tensor  输出张量的步幅

- storage_offset (int, optional) – the offset in the underlying storage of the output tensor.  输出张量在底层存储中的偏移量

In [77]:
import torch

x = torch.arange(81).reshape(9,9) # 不加reshape也是一样的结果
print(x)
t = torch.as_strided(x, size=(10, 10), stride=(1, 2))
print(t)
t = torch.as_strided(x, size=(10, 10), stride=(1, 2), storage_offset=1)
t

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
        54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
        72, 73, 74, 75, 76, 77, 78, 79, 80])
tensor([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
        [ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19],
        [ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20],
        [ 3,  5,  7,  9, 11, 13, 15, 17, 19, 21],
        [ 4,  6,  8, 10, 12, 14, 16, 18, 20, 22],
        [ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23],
        [ 6,  8, 10, 12, 14, 16, 18, 20, 22, 24],
        [ 7,  9, 11, 13, 15, 17, 19, 21, 23, 25],
        [ 8, 10, 12, 14, 16, 18, 20, 22, 24, 26],
        [ 9, 11, 13, 15, 17, 19, 21, 23, 25, 27]])


tensor([[ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19],
        [ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20],
        [ 3,  5,  7,  9, 11, 13, 15, 17, 19, 21],
        [ 4,  6,  8, 10, 12, 14, 16, 18, 20, 22],
        [ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23],
        [ 6,  8, 10, 12, 14, 16, 18, 20, 22, 24],
        [ 7,  9, 11, 13, 15, 17, 19, 21, 23, 25],
        [ 8, 10, 12, 14, 16, 18, 20, 22, 24, 26],
        [ 9, 11, 13, 15, 17, 19, 21, 23, 25, 27],
        [10, 12, 14, 16, 18, 20, 22, 24, 26, 28]])

## from_numpy
从numpy.ndarray创建一个张量。

 **定义**：
torch.from_numpy(ndarray) → Tensor

In [78]:
import torch
a = numpy.array([1, 2, 3])
t = torch.from_numpy(a)
t
t[0] = -1
a

array([-1,  2,  3])

## from_dlpack
将一个张量从外部库转换为torch.Tensor。

DLPack是一个轻量级的跨框架张量内存交换标准，它定义了一种描述张量数据内存布局的结构体。通过DLPack，可以将一个深度学习框架的张量数据转换为DLPack tensor并传递给另一个框架处理，从而实现模型组合和迁移等功能。DLPack已经被多个深度学习框架所支持。

 **定义**：
torch.from_dlpack(ext_tensor) → Tensor

In [79]:
import torch
import torch.utils.dlpack
t = torch.arange(4)

t2 = torch.from_dlpack(t)
t2[:2] = -1  # show that memory is shared
t2
t

tensor([-1, -1,  2,  3])

## frombuffer
从实现Python缓冲区协议的对象创建一个一维张量。

 **定义**：
torch.frombuffer(buffer, *, dtype, count=- 1, offset=0, requires_grad=False) → Tensor

**参数**：


In [80]:
import array
import torch
a = array.array('i', [1, 2, 3])
t = torch.frombuffer(a, dtype=torch.int32)
t
t[0] = -1
print(a)

# Interprets the signed char bytes as 32-bit integers.
# Each 4 signed char elements will be interpreted as
# 1 signed 32-bit integer.
a = array.array('b', [-1, 0, 0, 0])
torch.frombuffer(a, dtype=torch.int32)

array('i', [-1, 2, 3])


tensor([255], dtype=torch.int32)

## zeros
返回一个用标量值0填充的张量，其形状由变量参数size定义。

 **定义**：
torch.zeros(*size, *, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False) → Tensor

**参数**：
- out (Tensor, optional) – the output tensor.  将创建的tensor赋值给out，共享内存

- dtype (torch.dtype, optional) – the desired data type of returned tensor. Default: if None, uses a global default (see torch.set_default_tensor_type()).  返回张量的期望数据类型

- layout (torch.layout, optional) – the desired layout of returned Tensor. Default: torch.strided.  返回张量的期望布局,有 strided， sparse_coo(稀疏张量使用)等

- device (torch.device, optional) – the desired device of returned tensor. Default: if None, uses the current device for the default tensor type (see torch.set_default_tensor_type()). device will be the CPU for CPU tensor types and the current CUDA device for CUDA tensor types.  构造张量的设备

- requires_grad (bool, optional) – If autograd should record operations on the returned tensor. Default: False. 是否记录张量的梯度

In [87]:
import torch
a = torch.ones(2, 3)
b = torch.zeros(2,3,out=a)
print(a.data_ptr() == b.data_ptr())

True


In [90]:
import torch

# 创建一个大小为 (2, 3) 的张量，存储顺序为行优先
x = torch.zeros((2, 3), layout=torch.strided)
print(x)

# 创建一个大小为 (2, 3) 的张量，存储顺序为列优先
y = torch.zeros((2, 3), layout=torch.sparse_coo)
print(y)


tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor(indices=tensor([], size=(2, 0)),
       values=tensor([], size=(0,)),
       size=(2, 3), nnz=0, layout=torch.sparse_coo)


## zeros_like
返回一个用标量值0填充的张量，大小与输入相同。

 **定义**：
torch.zeros_like(input, *, dtype=None, layout=None, device=None, requires_grad=False, memory_format=torch.preserve_format) → Tensor

**参数**：
- input (Tensor) – the size of input will determine size of the output tensor.  输入的大小将决定输出张量的大小。

- dtype (torch.dtype, optional) – the desired data type of returned Tensor. Default: if None, defaults to the dtype of input.  返回张量的期望数据类型。Default:如果为None，默认为输入的dtype。

- layout (torch.layout, optional) – the desired layout of returned tensor. Default: if None, defaults to the layout of input.  返回张量的期望布局。Default:如果为None，默认为输入的布局。

- device (torch.device, optional) – the desired device of returned tensor. Default: if None, defaults to the device of input.  返回张量的期望设备。Default:如果为None，则默认为输入设备。

- requires_grad (bool, optional) – If autograd should record operations on the returned tensor. Default: False.  是否记录张量的梯度

- memory_format (torch.memory_format, optional) – the desired memory format of returned Tensor. Default: torch.preserve_format.  返回的张量的期望内存格式

In [91]:
import torch

input = torch.empty(2, 3)
torch.zeros_like(input)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

## ones

 **定义**：
torch.ones(*size, *, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False) → Tensor

**参数**：
- size (int...) – a sequence of integers defining the shape of the output tensor. Can be a variable number of arguments or a collection like a list or tuple.   一个定义输出张量形状的整数序列。可以是可变数量的参数，也可以是列表或元组之类的集合。

- out (Tensor, optional) – the output tensor.  将创建的tensor赋值给out，共享内存

- dtype (torch.dtype, optional) – the desired data type of returned tensor. Default: if None, uses a global default (see torch.set_default_tensor_type()).  返回张量的期望数据类型。

- layout (torch.layout, optional) – the desired layout of returned Tensor. Default: torch.strided.  返回张量的期望布局。Default:如果为None，默认为输入的布局。

- device (torch.device, optional) – the desired device of returned tensor. Default: if None, uses the current device for the default tensor type (see torch.set_default_tensor_type()). device will be the CPU for CPU tensor types and the current CUDA device for CUDA tensor types.  返回张量的期望设备。Default:如果为None，则默认为输入设备。

- requires_grad (bool, optional) – If autograd should record operations on the returned tensor. Default: False.  是否记录张量的梯度

In [92]:
import torch
torch.ones(2, 3)

torch.ones(5)

tensor([1., 1., 1., 1., 1.])

## ones_like
返回一个用标量值1填充的张量，大小与输入相同。

 **定义**：
torch.ones_like(input, *, dtype=None, layout=None, device=None, requires_grad=False, memory_format=torch.preserve_format) → Tensor

**参数**：
- input (Tensor) – the size of input will determine size of the output tensor.  输入的大小将决定输出张量的大小。

- dtype (torch.dtype, optional) – the desired data type of returned Tensor. Default: if None, defaults to the dtype of input.  返回张量的期望数据类型。Default:如果为None，默认为输入的dtype。

- layout (torch.layout, optional) – the desired layout of returned tensor. Default: if None, defaults to the layout of input.  返回张量的期望布局。Default:如果为None，默认为输入的布局。

- device (torch.device, optional) – the desired device of returned tensor. Default: if None, defaults to the device of input.  返回张量的期望设备。Default:如果为None，则默认为输入设备。

- requires_grad (bool, optional) – If autograd should record operations on the returned tensor. Default: False.  是否记录张量的梯度

- memory_format (torch.memory_format, optional) – the desired memory format of returned Tensor. Default: torch.preserve_format.  返回的张量的期望内存格式

In [93]:
import torch
input = torch.empty(2, 3)
torch.ones_like(input)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

## arange

 **定义**：
torch.arange(start=0, end, step=1, *, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False) → Tensor

**参数**：
- start (Number) – the starting value for the set of points. Default: 0.  点集的起始值。默认值:0。

- end (Number) – the ending value for the set of points  点集的结束值

- step (Number) – the gap between each pair of adjacent points. Default: 1.  每对相邻点之间的距离。默认值:1。

- out (Tensor, optional) – the output tensor.  将创建的tensor赋值给out，共享内存

- dtype (torch.dtype, optional) – the desired data type of returned tensor. Default: if None, uses a global default (see torch.set_default_tensor_type()). If dtype is not given, infer the data type from the other input arguments. If any of start, end, or stop are floating-point, the dtype is inferred to be the default dtype, see get_default_dtype(). Otherwise, the dtype is inferred to be torch.int64.  返回张量的期望数据类型。Default:如果为None，则使用全局默认值

- layout (torch.layout, optional) – the desired layout of returned Tensor. Default: torch.strided.  返回张量的期望布局。Default:如果为None，默认为输入的布局。

- device (torch.device, optional) – the desired device of returned tensor. Default: if None, uses the current device for the default tensor type (see torch.set_default_tensor_type()). device will be the CPU for CPU tensor types and the current CUDA device for CUDA tensor types.  返回张量的期望设备。Default:如果为None，则默认为输入设备。

- requires_grad (bool, optional) – If autograd should record operations on the returned tensor. Default: False.  是否记录张量的梯度

In [94]:
import torch
torch.arange(5)
torch.arange(1, 4)
torch.arange(1, 2.5, 0.5)

tensor([1.0000, 1.5000, 2.0000])

## linspace
创建一个一维大小步长的张量，其值从开始到结束都是均匀间隔的.

 **定义**：
torch.linspace(start, end, steps, *, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False) → Tensor

**参数**：
- start (float) – the starting value for the set of points  点集的起始值

- end (float) – the ending value for the set of points  点集的结束值

- steps (int) – size of the constructed tensor  构造张量的大小

- out (Tensor, optional) – the output tensor.  将创建的tensor赋值给out，共享内存

- dtype (torch.dtype, optional) – the data type to perform the computation in. Default: if None, uses the global default dtype (see torch.get_default_dtype()) when both start and end are real, and corresponding complex dtype when either is complex.  返回张量的期望数据类型。Default:如果为None，则使用全局默认值

- layout (torch.layout, optional) – the desired layout of returned Tensor. Default: torch.strided.  返回张量的期望布局。Default:如果为None，默认为输入的布局。

- device (torch.device, optional) – the desired device of returned tensor. Default: if None, uses the current device for the default tensor type (see torch.set_default_tensor_type()). device will be the CPU for CPU tensor types and the current CUDA device for CUDA tensor types.  返回张量的期望设备

- requires_grad (bool, optional) – If autograd should record operations on the returned tensor. Default: False.  是否记录张量的梯度

In [96]:
import torch
torch.linspace(3, 10, steps=5)
torch.linspace(-10, 10, steps=5)
torch.linspace(start=-10, end=10, steps=5)
torch.linspace(start=-10, end=10, steps=10)

tensor([-10.0000,  -7.7778,  -5.5556,  -3.3333,  -1.1111,   1.1111,   3.3333,
          5.5556,   7.7778,  10.0000])

## logspace
生成在对数空间中均匀分布的数值.
$$(\text{base}^{\text{start}},\text{base}^{\left(\text{stand}+\frac{\text{end}-\text{start}}{\text{steps}-1}\right)},\ldots,\text{base}^{\left(\text{start}+\left(\text{steps}-2\right)*\frac{\text{end}-\text{start}}{{\text{steps}-1}}\right)},\text{base}^\text{end})$$

 **定义**：
torch.logspace(start, end, steps, base=10.0, *, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False) → Tensor

**参数**：
- start (float) – the starting value for the set of points 点集的起始值

- end (float) – the ending value for the set of points  点集的结束值

- steps (int) – size of the constructed tensor  构造张量的大小

- base (float, optional) – base of the logarithm function. Default: 10.0.  对数函数的基数。默认值:10.0。

- out (Tensor, optional) – the output tensor.  将创建的tensor赋值给out，共享内存

- dtype (torch.dtype, optional) – the data type to perform the computation in. Default: if None, uses the global default dtype (see torch.get_default_dtype()) when both start and end are real, and corresponding complex dtype when either is complex.  执行计算的数据类型

- layout (torch.layout, optional) – the desired layout of returned Tensor. Default: torch.strided.  返回张量的期望布局。Default:如果为None，默认为输入的布局。

- device (torch.device, optional) – the desired device of returned tensor. Default: if None, uses the current device for the default tensor type (see torch.set_default_tensor_type()). device will be the CPU for CPU tensor types and the current CUDA device for CUDA tensor types.  返回张量的期望设备。Default:如果为None，则默认为输入设备。

- requires_grad (bool, optional) – If autograd should record operations on the returned tensor. Default: False.  是否记录张量的梯度

In [99]:
import torch
torch.logspace(start=-10, end=10, steps=5)
torch.logspace(start=0.1, end=1.0, steps=5)
torch.logspace(start=0.1, end=1.0, steps=1)
torch.logspace(start=2, end=2, steps=1, base=2)
torch.logspace(start=1, end=10, steps=10, base=2)

tensor([   2.,    4.,    8.,   16.,   32.,   64.,  128.,  256.,  512., 1024.])

## eye
返回一个二维张量，对角线上为1，其他地方为0。

 **定义**：
torch.eye(n, m=None, *, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False) → Tensor

**参数**：
- n (int) – the number of rows  行数

- m (int, optional) – the number of columns with default being n  默认为n的列数

- out (Tensor, optional) – the output tensor.  将创建的tensor赋值给out，共享内存

- dtype (torch.dtype, optional) – the desired data type of returned tensor. Default: if None, uses a global default (see torch.set_default_tensor_type()).  执行计算的数据类型

- layout (torch.layout, optional) – the desired layout of returned Tensor. Default: torch.strided.  返回张量的期望布局。Default:如果为None，默认为输入的布局。

- device (torch.device, optional) – the desired device of returned tensor. Default: if None, uses the current device for the default tensor type (see torch.set_default_tensor_type()). device will be the CPU for CPU tensor types and the current CUDA device for CUDA tensor types.  Default:如果为None，则默认为输入设备。

- requires_grad (bool, optional) – If autograd should record operations on the returned tensor. Default: False.  是否记录张量的梯度

In [101]:
import torch
torch.eye(3,4)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]])

## empty
返回一个充满未初始化数据的张量。张量的形状由变量参数大小定义。

 **定义**：
torch.empty(*size, *, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False, pin_memory=False, memory_format=torch.contiguous_format) → Tensor

**参数**：
- size (int...) – a sequence of integers defining the shape of the output tensor. Can be a variable number of arguments or a collection like a list or tuple.  一个定义输出张量形状的整数序列。

- out (Tensor, optional) – the output tensor.  将创建的tensor赋值给out，共享内存

- dtype (torch.dtype, optional) – the desired data type of returned tensor. Default: if None, uses a global default (see torch.set_default_tensor_type()).  返回张量的期望数据类型

- layout (torch.layout, optional) – the desired layout of returned Tensor. Default: torch.strided.  返回张量的期望布局。Default:如果为None，默认为输入的布局。

- device (torch.device, optional) – the desired device of returned tensor. Default: if None, uses the current device for the default tensor type (see torch.set_default_tensor_type()). device will be the CPU for CPU tensor types and the current CUDA device for CUDA tensor types.  返回张量的期望设备。Default:如果为None，则使用当前设备作为默认张量类型

- requires_grad (bool, optional) – If autograd should record operations on the returned tensor. Default: False.  是否记录张量的梯度

- pin_memory (bool, optional) – If set, returned tensor would be allocated in the pinned memory. Works only for CPU tensors. Default: False.如果设置，返回的张量将分配到固定内存中。pin_memory 是 PyTorch 中一种优化技术，它可以在 CPU 和 GPU 之间高速地复制数据，以加速数据的传输。在 PyTorch 中，可以通过在 Dataset 类中设置 pin_memory=True 来启用 pin_memory 技术。需要注意的是，pin_memory 技术需要更多的内存来存储固定内存区域中的数据，因此如果内存有限，可能需要考虑关闭 pin_memory 技术。

- memory_format (torch.memory_format, optional) – the desired memory format of returned Tensor. Default: torch.contiguous_format.  返回的张量的期望内存格式

In [106]:
import torch
torch.empty((2,3))

tensor([[0.0000e+00, 7.1466e-44, 1.8754e+28],
        [1.0396e-05, 2.1180e+23, 1.0425e-11]])

## empty_like
返回一个与输入大小相同的未初始化张量。

 **定义**：
torch.empty_like(input, *, dtype=None, layout=None, device=None, requires_grad=False, memory_format=torch.preserve_format) → Tensor

**参数**：
- input (Tensor) – the size of input will determine size of the output tensor.  输入的大小将决定输出张量的大小。

- dtype (torch.dtype, optional) – the desired data type of returned Tensor. Default: if None, defaults to the dtype of input. 返回张量的期望数据类型

- layout (torch.layout, optional) – the desired layout of returned tensor. Default: if None, defaults to the layout of input. 返回张量的期望布局。Default:如果为None，默认为输入的布局。

- device (torch.device, optional) – the desired device of returned tensor. Default: if None, defaults to the device of input.  返回张量的期望设备。Default:如果为None，则使用当前设备作为默认张量类型

- requires_grad (bool, optional) – If autograd should record operations on the returned tensor. Default: False.  是否记录张量的梯度

- memory_format (torch.memory_format, optional) – the desired memory format of returned Tensor. Default: torch.preserve_format.  返回的张量的期望内存格式

In [108]:
import torch
a=torch.empty((2,3), dtype=torch.int32, device = 'cpu')
torch.empty_like(a)

tensor([[ 842607925, 1663906402, 1650745655],
        [ 878798128,  775238498, 1667594341]], dtype=torch.int32)

## full


 **定义**：
torch.full(size, fill_value, *, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False) → Tensor

**参数**：
- size (int...) – a list, tuple, or torch.Size of integers defining the shape of the output tensor.  列表、元组或火炬。定义输出张量形状的整数的大小。

- fill_value (Scalar) – the value to fill the output tensor with.  用来填充输出张量的值。

- out (Tensor, optional) – the output tensor.  将创建的tensor赋值给out，共享内存

- dtype (torch.dtype, optional) – the desired data type of returned tensor. Default: if None, uses a global default (see torch.set_default_tensor_type()).  返回张量的期望数据类型。

- layout (torch.layout, optional) – the desired layout of returned Tensor. Default: torch.strided.   返回张量的期望布局。Default:如果为None，默认为输入的布局。

- device (torch.device, optional) – the desired device of returned tensor. Default: if None, uses the current device for the default tensor type (see torch.set_default_tensor_type()). device will be the CPU for CPU tensor types and the current CUDA device for CUDA tensor types.  返回张量的期望设备

- requires_grad (bool, optional) – If autograd should record operations on the returned tensor. Default: False.  是否记录张量的梯度

In [109]:
import torch
torch.full((2, 3), 3.141592)

tensor([[3.1416, 3.1416, 3.1416],
        [3.1416, 3.1416, 3.1416]])

## full_like
返回一个与输入相同大小的张量，填充fill_value

 **定义**：
torch.full_like(input, fill_value, *, dtype=None, layout=torch.strided, device=None, requires_grad=False, memory_format=torch.preserve_format) → Tensor

**参数**：
- input (Tensor) – the size of input will determine size of the output tensor.  输入的大小将决定输出张量的大小。

- fill_value – the number to fill the output tensor with.  填充输出张量的数字。

- dtype (torch.dtype, optional) – the desired data type of returned Tensor. Default: if None, defaults to the dtype of input.  返回张量的期望数据类型

- layout (torch.layout, optional) – the desired layout of returned tensor. Default: if None, defaults to the layout of input.  返回张量的期望布局

- device (torch.device, optional) – the desired device of returned tensor. Default: if None, defaults to the device of input.  返回张量的期望设备

- requires_grad (bool, optional) – If autograd should record operations on the returned tensor. Default: False.是否记录张量的梯度

- memory_format (torch.memory_format, optional) – the desired memory format of returned Tensor. Default: torch.preserve_format.  返回的张量的期望内存格式

In [111]:
import torch
a=torch.empty((2,3), dtype=torch.int32, device = 'cpu')
torch.full_like(a,fill_value=2)

tensor([[2, 2, 2],
        [2, 2, 2]], dtype=torch.int32)

## quantize_per_tensor
Converts a float tensor to a quantized tensor with given scale and zero point.

用于将一个 float 类型的张量量化为一个定点数张量

在深度学习中，通常会使用浮点数来表示神经网络中的参数和计算结果。然而，在一些硬件设备（如边缘设备、嵌入式设备）中，浮点数计算的复杂度和存储需求都很高，因此无法直接使用浮点数进行计算。为了在这些设备上运行深度学习模型，需要将浮点数转换为定点数。

定点数是一种用整数表示的数值类型，其表示范围和精度可以通过量化比例和量化零点来控制。量化比例用于控制数值范围，量化零点用于控制数值精度。

量化的过程就是将浮点数转换为定点数的过程。在 PyTorch 中，使用 quantize_per_tensor 函数可以将一个浮点数张量量化为一个定点数张量。具体来说，quantize_per_tensor 函数会将浮点数除以一个量化比例 scale 并四舍五入取整，然后加上一个量化零点 zero_point 得到一个整数。量化后的整数值将使用指定的数据类型来存储，其范围由量化比例和量化零点决定。

例如，假设我们要将一个浮点数 0.1 量化为一个 uint8 类型的定点数。我们可以指定量化比例为 0.01，量化零点为 128。量化后的整数值为：  
quantized_value = round(float_value / scale) + zero_point = round(0.1 / 0.01) + 128 = 138
因此，浮点数 0.1 将被量化为整数 138。同样，我们可以将其他浮点数量化为定点数。

在使用定点数进行计算时，需要进行一定的数值范围和精度的调整。具体来说，定点数的数值范围和精度可能与浮点数不同，因此需要进行量化后的数值范围和精度的调整，以保证计算的正确性。

计算和反量化的先后顺序如下：

1. 计算前，将浮点数张量量化为定点数张量。

2. 进行计算，使用定点数张量进行计算。

3. 计算后，将定点数张量反量化为浮点数张量。

具体地说，在计算前，需要使用 quantize_per_tensor 函数将浮点数除以一个量化比例并四舍五入取整，然后加上一个量化零点得到一个整数。在计算过程中，使用定点数张量进行计算。计算后，需要使用 dequantize 函数将定点数张量减去量化零点，并乘以量化比例得到一个浮点数。

所以，量化和反量化是成对使用的，用于将浮点数张量转换为定点数张量进行计算，然后将定点数张量转换回浮点数张量，以保证计算的正确性。


 **定义**：
torch.quantize_per_tensor(input, scale, zero_point, dtype) → Tensor

**参数**：
- input (Tensor) – float tensor or list of tensors to quantize  float张量或要量化的张量列表

- scale (float or Tensor) – scale to apply in quantization formula  应用于量化公式的尺度

- zero_point (int or Tensor) – offset in integer value that maps to float zero  映射到浮点零的整数值的偏移量

- dtype (torch.dtype) – the desired data type of returned tensor. Has to be one of the quantized dtypes: torch.quint8, torch.qint8, torch.qint32  返回张量的期望数据类型

In [113]:
import torch
torch.quantize_per_tensor(torch.tensor([-1.0, 0.0, 1.0, 2.0]), 0.1, 10, torch.quint8)
# torch.quantize_per_tensor(torch.tensor([-1.0, 0.0, 1.0, 2.0]), 0.1, 10, torch.quint8).int_repr()
# torch.quantize_per_tensor([torch.tensor([-1.0, 0.0]), torch.tensor([-2.0, 2.0])],
# torch.tensor([0.1, 0.2]), torch.tensor([10, 20]), torch.quint8)
# torch.quantize_per_tensor(torch.tensor([-1.0, 0.0, 1.0, 2.0]), torch.tensor(0.1), torch.tensor(10), torch.quint8)

tensor([-1.,  0.,  1.,  2.], size=(4,), dtype=torch.quint8,
       quantization_scheme=torch.per_tensor_affine, scale=0.1, zero_point=10)

## quantize_per_channel
将一个浮点张量转换为具有给定尺度和零点的每通道量化张量。

 **定义**：
torch.quantize_per_channel(input, scales, zero_points, axis, dtype) → Tensor

**参数**：
- input (Tensor) – float tensor to quantize  float张量或要量化的张量列表

- scales (Tensor) – float 1D tensor of scales to use, size should match input.size(axis)  应用于量化公式的尺度

- zero_points (int) – integer 1D tensor of offset to use, size should match input.size(axis)  使用的偏移量的整数1D张量

- axis (int) – dimension on which apply per-channel quantization  应用每个通道量化的维度

- dtype (torch.dtype) – the desired data type of returned tensor. Has to be one of the quantized dtypes: torch.quint8, torch.qint8, torch.qint32  返回张量的期望数据类型。


In [115]:
import torch
x = torch.tensor([[-1.0, 0.0], [1.0, 2.0]])
torch.quantize_per_channel(x, torch.tensor([0.1, 0.01]), torch.tensor([10, 0]), 0, torch.quint8)
# torch.quantize_per_channel(x, torch.tensor([0.1, 0.01]), torch.tensor([10, 0]), 0, torch.quint8).int_repr()

tensor([[-1.,  0.],
        [ 1.,  2.]], size=(2, 2), dtype=torch.quint8,
       quantization_scheme=torch.per_channel_affine,
       scale=tensor([0.1000, 0.0100], dtype=torch.float64),
       zero_point=tensor([10,  0]), axis=0)

## dequantize
用于将定点数张量反量化为浮点数张量

**定义**：
torch.dequantize(tensor) → Tensor

In [133]:
import torch

# 创建一个定点数张量
x = torch.quantize_per_tensor(
    torch.tensor([1., 2, 3]),
    dtype=torch.quint8, scale=0.1, zero_point=20)

# 将定点数张量反量化为浮点数张量
y = torch.dequantize(x)

print("x:", x)
print("y:", y)


x: tensor([1., 2., 3.], size=(3,), dtype=torch.quint8,
       quantization_scheme=torch.per_tensor_affine, scale=0.1, zero_point=20)
y: tensor([1., 2., 3.])


## complex
构造一个复张量，其实部等于实部，虚部等于像。

**定义**：
torch.complex(real, imag, *, out=None) → Tensor

**参数**：
- real (Tensor) – The real part of the complex tensor. Must be float or double.  复张量的实部。必须为float或double。

- imag (Tensor) – The imaginary part of the complex tensor. Must be same dtype as real.  复张量的虚部。dtype必须和real相同。

- out (Tensor) – If the inputs are torch.float32, must be torch.complex64. If the inputs are torch.float64, must be torch.complex128.

In [135]:
import torch
real = torch.tensor([1, 2], dtype=torch.float32)
imag = torch.tensor([3, 4], dtype=torch.float32)
z = torch.complex(real, imag)
z
# z.dtype

tensor([1.+3.j, 2.+4.j])

## polar
构造一个复张量，其元素为笛卡尔坐标，对应于绝对值为abs和角为angle的极坐标。

**定义**：
torch.polar(abs, angle, *, out=None) → Tensor

**参数**：
- abs (Tensor) – The absolute value the complex tensor. Must be float or double.  复张量的绝对值

- angle (Tensor) – The angle of the complex tensor. Must be same dtype as abs.  复张量的角度

- out (Tensor) – If the inputs are torch.float32, must be torch.complex64. If the inputs are torch.float64, must be torch.complex128.

In [139]:
import numpy as np
import torch
abs = torch.tensor([1, 2], dtype=torch.float64)
angle = torch.tensor([np.pi / 2, 5 * np.pi / 4], dtype=torch.float64)
z = torch.polar(abs, angle)
z

tensor([ 6.1232e-17+1.0000j, -1.4142e+00-1.4142j], dtype=torch.complex128)

## heaviside
为输入中的每个元素计算Heaviside阶跃函数。
$$\text{heaviside}(input,values)=\begin{cases}0,&\text{if }\text{input}<0\\values,&\text{if }\mathrm{input}==0\\ 1,&\text{if }\operatorname{input}>0\end{cases}$$

**定义**：
torch.heaviside(input, values, *, out=None) → Tensor

**参数**：
- input (Tensor) – the input tensor.  输入张量

- values (Tensor) – The values to use where input is zero.  用于输入为零的值

- out (Tensor, optional) – the output tensor.  将创建的tensor赋值给out，共享内存

In [145]:
import torch
input = torch.tensor([-1.5, 0, 2.0])
values = torch.tensor([0.5])
torch.heaviside(input, values)
values = torch.tensor([1.2, -2.0, 3.5])
torch.heaviside(input, values)

tensor([ 0., -2.,  1.])

# 索引，切片，连接，变异操作

## adjoint
返回共轭张量的视图，并将最后两个维度转置。

**定义**：
torch.adjoint(Tensor) → Tensor

In [147]:
import torch
x = torch.arange(4, dtype=torch.float)
A = torch.complex(x, x).reshape(2, 2)
print(A)
print(A.adjoint())
(A.adjoint() == A.mH).all()

tensor([[0.+0.j, 1.+1.j],
        [2.+2.j, 3.+3.j]])
tensor([[0.-0.j, 2.-2.j],
        [1.-1.j, 3.-3.j]])


tensor(True)

## argwhere
返回一个张量，包含输入中所有非零元素的下标

**定义**：
torch.argwhere(input) → Tensor

In [150]:
import torch
t = torch.tensor([1, 0, 1])
torch.argwhere(t)
t = torch.tensor([[1, 0, 1], 
                  [0, 1, 1]])
torch.argwhere(t)

tensor([[0, 0],
        [0, 2],
        [1, 1],
        [1, 2]])

## cat/concat/concatenate
在给定维度中连接给定序列的seq张量。

**定义**：
torch.cat(tensors, dim=0, *, out=None) → Tensor

**参数**：
tensors (sequence of Tensors) – any python sequence of tensors of the same type. Non-empty tensors provided must have the same shape, except in the cat dimension.  任何相同类型的python张量序列

dim (int, optional) – the dimension over which the tensors are concatenated  连接张量的维度

out (Tensor, optional) – the output tensor.  将创建的tensor赋值给out，共享内存

In [154]:
import torch
x = torch.arange(9).reshape(3,3)
x
torch.cat((x, x, x), 0)
torch.concat((x, x, x), 0)
torch.concatenate((x, x, x), 0)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8],
        [0, 1, 2],
        [3, 4, 5],
        [6, 7, 8],
        [0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

## conj
用于计算输入张量的复共轭

**定义**：
torch.conj(input) → Tensor

In [157]:
import torch
x = torch.tensor([-1 + 1j, -2 + 2j, 3 - 3j])
x.is_conj()
y = torch.conj(x)
y.is_conj()

True

## chunk
尝试将一个张量分割为指定数量的块。每个块都是输入张量的一个视图。

**定义**：
torch.chunk(input, chunks, dim=0) → List of Tensors

**参数**：
- input (Tensor) – the tensor to split  要分割的张量

- chunks (int) – number of chunks to return  返回的chunk个数

- dim (int) – dimension along which to split the tensor  分割张量的维度

In [162]:
import torch
torch.arange(11).chunk(3)

(tensor([0, 1, 2, 3]), tensor([4, 5, 6, 7]), tensor([ 8,  9, 10]))

## dsplit
根据indices_or_sections将输入的三维或多维张量深度分割为多个张量。每个分割都是一个输入视图。

**定义**：
torch.dsplit(input, sections) → List of Tensors

**参数**：
- input (Tensor) – tensor to split.  要分割的张量。

- sections (int or list or tuple of ints) – See argument in torch.tensor_split().

**图解**：
<p align="center">
<img src="./imgs/dsplit.svg"
    width="1000" /></p>

In [36]:
t = torch.arange(32.0).reshape(4,4,2)
print(t)
torch.dsplit(t, sections=2)

tensor([[[ 0.,  1.],
         [ 2.,  3.],
         [ 4.,  5.],
         [ 6.,  7.]],

        [[ 8.,  9.],
         [10., 11.],
         [12., 13.],
         [14., 15.]],

        [[16., 17.],
         [18., 19.],
         [20., 21.],
         [22., 23.]],

        [[24., 25.],
         [26., 27.],
         [28., 29.],
         [30., 31.]]])


(tensor([[[ 0.],
          [ 2.],
          [ 4.],
          [ 6.]],
 
         [[ 8.],
          [10.],
          [12.],
          [14.]],
 
         [[16.],
          [18.],
          [20.],
          [22.]],
 
         [[24.],
          [26.],
          [28.],
          [30.]]]),
 tensor([[[ 1.],
          [ 3.],
          [ 5.],
          [ 7.]],
 
         [[ 9.],
          [11.],
          [13.],
          [15.]],
 
         [[17.],
          [19.],
          [21.],
          [23.]],
 
         [[25.],
          [27.],
          [29.],
          [31.]]]))

## column_stack
通过水平叠加张量来创建一个新的张量。

**定义**：
torch.column_stack(tensors, *, out=None) → Tensor

**参数**：
- tensors (sequence of Tensors) – sequence of tensors to concatenate  要连接的张量序列

- out (Tensor, optional) – the output tensor.  将创建的tensor赋值给out，共享内存

In [176]:
import torch
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])
torch.column_stack((a, b))
# a = torch.arange(5)
# b = torch.arange(10).reshape(5, 2)
# torch.column_stack((a, b, b))

tensor([[1, 4],
        [2, 5],
        [3, 6]])

## dstack
按顺序深度堆叠张量(沿第三个轴)。

**定义**：
torch.dstack(tensors, *, out=None) → Tensor

**参数**：
tensors (sequence of Tensors) – sequence of tensors to concatenate  要连接的张量序列

out (Tensor, optional) – the output tensor.  将创建的tensor赋值给out，共享内存

In [181]:
import torch
a = torch.arange(9).reshape(3,3,1) #HWC
b = torch.arange(9).reshape(3,3,1)*10
a
# a = torch.tensor([1, 2, 3])
# b = torch.tensor([4, 5, 6])
torch.dstack((a,b))
# a = torch.tensor([[1],[2],[3]])
# b = torch.tensor([[4],[5],[6]])
# torch.dstack((a,b))

tensor([[[ 0,  0],
         [ 1, 10],
         [ 2, 20]],

        [[ 3, 30],
         [ 4, 40],
         [ 5, 50]],

        [[ 6, 60],
         [ 7, 70],
         [ 8, 80]]])

## gather
沿着dim指定的轴收集值。

**定义**：
torch.gather(input, dim, index, *, sparse_grad=False, out=None) → Tensor

**参数**：
input (Tensor) – the source tensor

dim (int) – the axis along which to index

index (LongTensor) – the indices of elements to gather

sparse_grad (bool, optional) – If True, gradient w.r.t. input will be a sparse tensor.

out (Tensor, optional) – the destination tensor

**图解**：
<p align="center">
<img src="./imgs/20230313191028.png"
    width="700" /></p>

<p align="center">
<img src="./imgs/20230313191047.png"
    width="700" /></p>

https://machinelearningknowledge.ai/how-to-use-torch-gather-function-in-pytorch-with-examples/

In [226]:
import torch
input = torch.tensor([[0, 1, 2],
                      [3, 4, 5],
                      [6, 7, 8]]) 

print(torch.gather(input, dim=0, index=torch.tensor([[0, 1, 2],
                                                     [2, 1, 0]])))

print(torch.gather(input, dim=1, index=torch.tensor([[2, 1, 0],
                                                     [0, 2, 1]])))


tensor([[0, 4, 8],
        [6, 4, 2]])
tensor([[2, 1, 0],
        [3, 5, 4]])


## hsplit
在水平方向上切分，相当于是竖着切

**定义**：
torch.hsplit(input, sections) → List of Tensors

**参数**：
input (Tensor) – tensor to split.

indices_or_sections (int or list or tuple of ints) – See argument in torch.tensor_split().

**图解**：
<p align="center">
<img src="./imgs/hsplit.svg"
    width="800" /></p>

In [41]:
import torch
t = torch.arange(16.0).reshape(4,4)
print(t)
torch.hsplit(t, sections=2)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]])


(tensor([[ 0.,  1.],
         [ 4.,  5.],
         [ 8.,  9.],
         [12., 13.]]),
 tensor([[ 2.,  3.],
         [ 6.,  7.],
         [10., 11.],
         [14., 15.]]))

## vsplit
在竖直方向上切分，相当于是横着切

**定义**：
torch.vsplit(input, indices_or_sections) → List of Tensors

**参数**：
input (Tensor) – tensor to split.

indices_or_sections (int or list or tuple of ints) – See argument in torch.tensor_split().

**图解**：
<p align="center">
<img src="./imgs/hsplit.svg"
    width="800" /></p>

In [273]:
import torch
t = torch.arange(16.0).reshape(4,4)
print(t)
torch.vsplit(t, sections=2)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]])


(tensor([[0., 1., 2., 3.],
         [4., 5., 6., 7.]]),
 tensor([[ 8.,  9., 10., 11.],
         [12., 13., 14., 15.]]))

## hstack
水平方向上拼接

**定义**：
torch.hstack(tensors, *, out=None) → Tensor

**参数**：
- tensors (sequence of Tensors) – sequence of tensors to concatenate

- out (Tensor, optional) – the output tensor.


In [44]:
import torch
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])
torch.hstack((a, b))
a = torch.tensor([[1],
                  [2],
                  [3]])
b = torch.tensor([[4],
                  [5],
                  [6]])
torch.hstack((a, b))


tensor([[1, 4],
        [2, 5],
        [3, 6]])

## vstack
水平方向上拼接

**定义**：
torch.vstack(tensors, *, out=None) → Tensor

**参数**：
- tensors (sequence of Tensors) – sequence of tensors to concatenate

- out (Tensor, optional) – the output tensor.


In [274]:
import torch
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])
torch.vstack((a, b))
a = torch.tensor([[1],
                  [2],
                  [3]])
b = torch.tensor([[4],
                  [5],
                  [6]])
torch.vstack((a, b))


tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])

## index_add
按照索引给张量加减值。

**定义**：
Tensor.index_add_(dim, index, source, *, alpha=1) → Tensor


**参数**：
- dim (int) – dimension along which to index  索引的维度

- index (Tensor) – indices of source to select from, should have dtype either torch.int64 or torch.int32  索引

- source (Tensor) – the tensor containing values to add 要加减多少

- alpha - 控制 src的倍数，即alpha * src  默认alpha=1


In [59]:
import torch
x = torch.ones(5, 3)
source = torch.tensor([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]], dtype=torch.float)
index = torch.tensor([0, 4, 2])
x.index_add_(0, index, t)
# x.index_add_(0, index, source, alpha=-1)
x

tensor([[ 2.,  3.,  4.],
        [ 1.,  1.,  1.],
        [ 8.,  9., 10.],
        [ 1.,  1.,  1.],
        [ 5.,  6.,  7.]])

## index_copy
按照索引给张量拷贝值。

**定义**：
Tensor.index_copy_(dim, index, tensor) → Tensor


**参数**：
- dim (int) – dimension along which to index  索引的维度

- index (LongTensor) – indices of tensor to select from  索引

- tensor (Tensor) – the tensor containing values to copy  包含要复制的值的张量


In [79]:
import torch
x = torch.zeros(5, 3)
t = torch.tensor([[1, 2, 3], 
                  [4, 5, 6], 
                  [7, 8, 9]], dtype=torch.float)
index = torch.tensor([0, 4, 2])
x.index_copy_(0, index, t)
x

tensor([[1., 2., 3.],
        [0., 0., 0.],
        [7., 8., 9.],
        [0., 0., 0.],
        [4., 5., 6.]])

## index_reduce


**定义**：
Tensor.index_reduce_(dim, index, source, reduce, *, include_self=True) → Tensor


**参数**：
- dim (int) – dimension along which to index  索引的维度

- index (Tensor) – indices of source to select from, should have dtype either torch.int64 or torch.int32  索引

- source (FloatTensor) – the tensor containing values to accumulate  包含要累积的值的张量

- reduce (str) – the reduction operation to apply ("prod", "mean", "amax", "amin")  应用的reduction操作

- include_self (bool) – whether the elements from the self tensor are included in the reduction
self张量中的元素是否包含在reduction中



In [89]:
import torch
x = torch.empty(5, 3).fill_(2)
t = torch.tensor([[1, 2, 3], 
                  [4, 5, 6], 
                  [7, 8, 9], 
                  [10, 11, 12]], dtype=torch.float)
index = torch.tensor([0, 4, 2, 0])
x.index_reduce_(0, index, t, 'prod')
# x = torch.empty(5, 3).fill_(1)
x.index_reduce_(0, index, t, 'prod', include_self=False)

tensor([[10., 22., 36.],
        [ 2.,  2.,  2.],
        [ 7.,  8.,  9.],
        [ 2.,  2.,  2.],
        [ 4.,  5.,  6.]])

In [87]:
import torch
x = torch.empty(5, 3).fill_(2)
t = torch.tensor([[1, 2, 3], 
                  [4, 5, 6], 
                  [7, 8, 9], 
                  [10, 11, 12]], dtype=torch.float)
index = torch.tensor([0, 4, 2, 0])
x.index_reduce_(0, index, t, 'prod')

tensor([[20., 44., 72.],
        [ 2.,  2.,  2.],
        [14., 16., 18.],
        [ 2.,  2.,  2.],
        [ 8., 10., 12.]])

## index_select
返回一个新的张量，该张量使用索引中的项(LongTensor)沿dim维度索引输入张量。

**定义**：
torch.index_select(input, dim, index, *, out=None) → Tensor

**参数**：
- input (Tensor) – the input tensor.  输入张量

- dim (int) – the dimension in which we index  索引

- index (IntTensor or LongTensor) – the 1-D tensor containing the indices to index  包含索引索引的一维张量

- out (Tensor, optional) – the output tensor.  输出张量


In [100]:
import torch
x = torch.randn(3, 4)
print(x)
indices = torch.tensor([0, 2])
torch.index_select(x, 0, indices)
torch.index_select(x, 1, indices)

tensor([[ 0.3960, -0.3405,  1.9604,  0.6839],
        [-1.1725,  0.6119, -3.0097, -0.2486],
        [ 0.8733,  0.0302, -0.0827, -0.1217]])


tensor([[ 0.3960,  1.9604],
        [-1.1725, -3.0097],
        [ 0.8733, -0.0827]])

## masked_select
返回一个新的一维张量，根据布尔掩码mask (boolean tensor)对输入张量进行索引。

**定义**：
torch.masked_select(input, mask, *, out=None) → Tensor

**参数**：
- input (Tensor) – the input tensor.

- mask (BoolTensor) – the tensor containing the binary mask to index with

- out (Tensor, optional) – the output tensor.  输出张量。

In [106]:
import torch
x = torch.randn(3, 4)
print(x)
mask = x.ge(0.5)
print(mask)
torch.masked_select(x, mask)

tensor([[ 1.1306, -0.4987,  0.2276, -0.5090],
        [-0.1216,  1.5538,  0.6814,  0.6978],
        [-0.2731, -1.4790,  0.8621,  0.6601]])
tensor([[ True, False, False, False],
        [False,  True,  True,  True],
        [False, False,  True,  True]])


tensor([1.1306, 1.5538, 0.6814, 0.6978, 0.8621, 0.6601])

## movedim/moveaxis
将输入的维度从源的位置移动到目标的位置。

**定义**：
torch.movedim(input, source, destination) → Tensor

**参数**：
- input (Tensor) – the input tensor.  输入张量

- source (int or tuple of ints) – Original positions of the dims to move. These must be unique.  原始位置

- destination (int or tuple of ints) – Destination positions for each of the original dims. These must also be unique.  目标位置


In [113]:
import torch
t = torch.arange(6).reshape(3,2,1)
print(t)

print(torch.movedim(t, 1, 0))
print(torch.movedim(t, 1, 0).shape)

tensor([[[0],
         [1]],

        [[2],
         [3]],

        [[4],
         [5]]])
tensor([[[0],
         [2],
         [4]],

        [[1],
         [3],
         [5]]])
torch.Size([2, 3, 1])


In [115]:
import torch
t = torch.arange(6).reshape(3,2,1)
print(t)
print(torch.movedim(t, (1, 2), (0, 1)).shape) #1换0， 2换1
print(torch.movedim(t, (1, 2), (0, 1)))

tensor([[[0],
         [1]],

        [[2],
         [3]],

        [[4],
         [5]]])
torch.Size([2, 1, 3])
tensor([[[0, 2, 4]],

        [[1, 3, 5]]])


## narrow
返回一个新的张量，它是输入张量的缩小版本。尺寸dim是从开始到开始的输入+长度。返回的张量和输入张量共享相同的底层存储空间。

**定义**：
torch.narrow(input, dim, start, length) → Tensor

**参数**：
- input (Tensor) – the tensor to narrow   要窄化的张量

- dim (int) – the dimension along which to narrow  沿着哪个维度窄化

- start (Tensor or int) – the starting dimension  起始位置

- length (int) – the distance to the ending dimension  长度

**图解**：
<p align="center">
<img src="./imgs/narrow.svg"
    width="1000" /></p>

In [128]:
import torch
x = torch.arange(16.0).reshape(4, 4)
print(x)
torch.narrow(x, dim=0, start=1, length=2)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]])


tensor([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [132]:
import torch
x = torch.arange(16.0).reshape(4, 4)
print(x)
torch.narrow(x, dim=1, start=2, length=2)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]])


tensor([[ 2.,  3.],
        [ 6.,  7.],
        [10., 11.],
        [14., 15.]])

## nonzero
返回一个张量，包含输入中所有非零元素的下标。

**定义**：
torch.nonzero(input, *, out=None, as_tuple=False) → LongTensor or tuple of LongTensors



In [137]:
import torch
torch.nonzero(torch.tensor([1, 1, 1, 0, 1]))
torch.nonzero(torch.tensor([[0.6, 0.0, 0.0, 0.0],
                            [0.0, 0.4, 0.0, 0.0],
                            [0.0, 0.0, 1.2, 0.0],
                            [0.0, 0.0, 0.0,-0.4]]))
# torch.nonzero(torch.tensor([1, 1, 1, 0, 1]), as_tuple=True)
# torch.nonzero(torch.tensor([[0.6, 0.0, 0.0, 0.0],
#                             [0.0, 0.4, 0.0, 0.0],
#                             [0.0, 0.0, 1.2, 0.0],
#                             [0.0, 0.0, 0.0,-0.4]]), as_tuple=True)
# # torch.nonzero(torch.tensor(5), as_tuple=True)

tensor([[0, 0],
        [1, 1],
        [2, 2],
        [3, 3]])

## permute
函数通过重排张量的轴顺序来实现维度变换，它不会改变张量中元素的顺序

**定义**：
torch.permute(input, dims) → Tensor

**参数**：
- input (Tensor) – the input tensor.  输入张量

- dims (tuple of python:int) – The desired ordering of dimensions  所需的维度顺序


In [144]:
import torch
x = torch.arange(6).reshape(3,2,1)
print(x)
print(x.size())
print("===========")
y= torch.permute(x, (1, 0, 2)) #可以对所有的轴进行重排序
print(y)
print(y.size())

tensor([[[0],
         [1]],

        [[2],
         [3]],

        [[4],
         [5]]])
torch.Size([3, 2, 1])
tensor([[[0],
         [2],
         [4]],

        [[1],
         [3],
         [5]]])
torch.Size([2, 3, 1])


## reshape
返回一个张量，其数据和元素数量与输入相同，但具有指定的形状。如果可能的话，返回的张量将是输入的视图。否则，它将是一个副本。

**定义**：
torch.reshape(input, shape) → Tensor

**参数**：
- input (Tensor) – the tensor to be reshaped  需要重塑的张量

- shape (tuple of python:int) – the new shape  新的形状


In [150]:
import torch
a = torch.arange(4.)
print(a)
torch.reshape(a, (2, 2))
# b = torch.tensor([[0, 1], [2, 3]])
# torch.reshape(b, (-1,))

tensor([0., 1., 2., 3.])


tensor([[0., 1.],
        [2., 3.]])

## vstack/row_stack
按竖直顺序(按行)堆叠张量。

**定义**：
torch.vstack(tensors, *, out=None) → Tensor

**参数**：
- tensors (sequence of Tensors) – sequence of tensors to concatenate  要连接的张量序列

- out (Tensor, optional) – the output tensor.  输出张量。

In [151]:
import torch
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])
torch.vstack((a,b))
# a = torch.tensor([[1],[2],[3]])
# b = torch.tensor([[4],[5],[6]])
# torch.vstack((a,b))

tensor([[1, 2, 3],
        [4, 5, 6]])

## select
在给定的索引处沿选定的维度对输入张量进行切片。这个函数返回去掉给定维度后原始张量的视图。
select() is equivalent to slicing.

**定义**：
torch.select(input, dim, index) → Tensor

**参数**：
- input (Tensor) – the input tensor.

- dim (int) – the dimension to slice

- index (int) – the index to select with


In [155]:
import torch

x = torch.arange(16.0).reshape(4, 4)
print(x)

selected = torch.select(x, dim=1, index=1)

print(selected.shape)
print(selected)


tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]])
torch.Size([4])
tensor([ 1.,  5.,  9., 13.])


## scatter
在索引张量中指定的索引处，将张量src中的所有值写入

**定义**：
torch.scatter(input, dim, index, src) → Tensor

**参数**：
- dim (int) – the axis along which to index

- index (LongTensor) – the indices of elements to scatter, can be either empty or of the same dimensionality as src. When empty, the operation returns self unchanged.

- src (Tensor or float) – the source element(s) to scatter.

- reduce (str, optional) – reduction operation to apply, can be either 'add' or 'multiply'.


In [158]:
import torch
src = torch.arange(1, 11).reshape((2, 5))
print(src)
index = torch.tensor([[0, 1, 2, 0]])
torch.zeros(3, 5, dtype=src.dtype).scatter_(0, index, src)

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])


tensor([[1, 0, 0, 4, 0],
        [0, 2, 0, 0, 0],
        [0, 0, 3, 0, 0]])

In [159]:
import torch
src = torch.arange(1, 11).reshape((2, 5))
print(src)
index = torch.tensor([[0, 1, 2], [0, 1, 4]])
torch.zeros(3, 5, dtype=src.dtype).scatter_(1, index, src)

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])


tensor([[1, 2, 3, 0, 0],
        [6, 7, 0, 0, 8],
        [0, 0, 0, 0, 0]])

In [161]:
import torch
src = torch.arange(1, 11).reshape((2, 5))
print(src)

torch.full((2, 4), 2.).scatter_(1, torch.tensor([[2], [3]]), 1.23, reduce='multiply')
# torch.full((2, 4), 2.).scatter_(1, torch.tensor([[2], [3]]),
#            1.23, reduce='add')

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])


tensor([[2.0000, 2.0000, 2.4600, 2.0000],
        [2.0000, 2.0000, 2.0000, 2.4600]])

## diagonal_scatter
将src张量的值沿输入的对角线元素嵌入到输入中，相对于dim1和dim2。

**定义**：
torch.diagonal_scatter(input, src, offset=0, dim1=0, dim2=1) → Tensor

**参数**：
input (Tensor) – the input tensor. Must be at least 2-dimensional.  输入张量。至少是二维的。

src (Tensor) – the tensor to embed into input.  要嵌入到输入中的张量。

offset (int, optional) – which diagonal to consider. Default: 0 (main diagonal).  考虑哪条对角线。默认值:0(主对角线)。

dim1 (int, optional) – first dimension with respect to which to take diagonal. Default: 0.  对角线的第一个维度。默认值:0。

dim2 (int, optional) – second dimension with respect to which to take diagonal. Default: 1.  对其进行对角线处理的第二个维度。默认值:1。


In [165]:
import torch
a = torch.zeros(3, 3)+10
a
torch.diagonal_scatter(a, torch.ones(3))


tensor([[ 1., 10., 10.],
        [10.,  1., 10.],
        [10., 10.,  1.]])

## select_scatter
将src张量的值嵌入到给定索引处的输入中。这个函数返回一个有新存储空间的张量;它不创建视图。

**定义**：
torch.select_scatter(input, src, dim, index) → Tensor

**参数**：
- input (Tensor) – the input tensor.  输入张量

- src (Tensor) – The tensor to embed into input  要嵌入到输入中的张量

- dim (int) – the dimension to insert the slice into.  插入切片的维度

- index (int) – the index to select with  选择的索引


In [174]:
import torch
a = torch.tensor([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9],
                  ])
src = torch.ones(3)
a.select_scatter(src = src, dim = 1, index = 0)


tensor([[1, 2, 3],
        [1, 5, 6],
        [1, 8, 9]])

## slice_scatter
将src张量的值嵌入到给定维度的输入中。这个函数返回一个有新存储空间的张量;它不创建视图。

**定义**：
torch.slice_scatter(input, src, dim=0, start=None, end=None, step=1) → Tensor

**参数**：
- input (Tensor) – the input tensor.  输入张量

- src (Tensor) – The tensor to embed into input  要嵌入到输入中的张量

- dim (int) – the dimension to insert the slice into  插入切片的维度

- start (Optional[int]) – the start index of where to insert the slice  开始位置

- end (Optional[int]) – the end index of where to insert the slice  结束为止

- step (int) – the how many elements to skip in  步长


In [198]:
import torch
a = torch.zeros(8, 8)
src = torch.ones(3,8)
a.slice_scatter(src, start=0,end=6,step=2)


tensor([[1., 1., 1., 1., 1., 1., 1., 1.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]])

## scatter_add
将张量src中的所有值添加到self中

**定义**：
torch.scatter_add(input, dim, index, src) → Tensor

**参数**：
- dim (int) – the axis along which to index  索引的轴

- index (LongTensor) – the indices of elements to scatter and add, can be either empty or of the same dimensionality as src. When empty, the operation returns self unchanged.

- src (Tensor) – the source elements to scatter and add

In [202]:
import torch
src = torch.ones((2, 5))
index = torch.tensor([[0, 1, 2, 0, 0]])
(torch.ones(3, 5, dtype=src.dtype)*100).scatter_add_(0, index, src)
# index = torch.tensor([[0, 1, 2, 0, 0], [0, 1, 2, 2, 2]])
# torch.zeros(3, 5, dtype=src.dtype).scatter_add_(0, index, src)

tensor([[101., 100., 100., 101., 101.],
        [100., 101., 100., 100., 100.],
        [100., 100., 101., 100., 100.]])

## scatter_reduce
将src张量中的所有值reduce到self张量中

**定义**：
torch.scatter_reduce(input, dim, index, src, reduce, *, include_self=True) → Tensor

**参数**：
- dim (int) – the axis along which to index  索引的轴

- index (LongTensor) – the indices of elements to scatter and reduce.

- src (Tensor) – the source elements to scatter and reduce

- reduce (str) – the reduction operation to apply for non-unique indices ("sum", "prod", "mean", "amax", "amin")

- include_self (bool) – whether elements from the self tensor are included in the reduction


In [224]:
import torch
input = torch.tensor([1., 2., 3., 4., 5, 6, 7])*10
src = torch.tensor([1., 2., 3., 4., 5., 6.])
index = torch.tensor([5, 1, 0, 1, 2, 1])
input.scatter_reduce(0, index, src, reduce="sum")  # input[5]+=src[0] 即60+1=61
# input.scatter_reduce(0, index, src, reduce="sum", include_self=False)
# input2 = torch.tensor([5., 4., 3., 2.])
# input2.scatter_reduce(0, index, src, reduce="amax")
# input2.scatter_reduce(0, index, src, reduce="amax", include_self=False)


tensor([13., 32., 35., 40., 50., 61., 70.])

## split
把张量分成若干块。每个块都是原始张量的一个视图。

**定义**：
torch.split(tensor, split_size_or_sections, dim=0)

**参数**：
- tensor (Tensor) – tensor to split.

- split_size_or_sections (int) or (list(int)) – size of a single chunk or list of sizes for each chunk  单个块的大小或每个块的大小列表

- dim (int) – dimension along which to split the tensor.  分割张量的维度。


In [260]:
import torch
a = torch.arange(10).reshape(5,2)
print(a)
torch.split(a, split_size_or_sections=2)
# torch.split(a, [1,4])

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


(tensor([[0, 1],
         [2, 3]]),
 tensor([[4, 5],
         [6, 7]]),
 tensor([[8, 9]]))

## squeeze
返回一个删除了所有大小为1的输入维度的张量。

**定义**：
torch.squeeze(input, dim=None) → Tensor

**参数**：
input (Tensor) – the input tensor.

dim (int, optional) – if given, the input will be squeezed only in this dimension  如果给定，输入将只压缩到这个维度


In [235]:
import torch
x = torch.zeros(2, 1, 2, 1, 2)
print(x.size())
y1 = torch.squeeze(x)
print(y1.size())
y2 = torch.squeeze(x, 0)
print(y2.size())
y3 = torch.squeeze(x, 1)
print(y3.size())

torch.Size([2, 1, 2, 1, 2])
torch.Size([2, 2, 2])
torch.Size([2, 1, 2, 1, 2])
torch.Size([2, 2, 1, 2])


## stack
沿着一个新的维度连接一个张量序列。所有张量的大小必须相同。

**定义**：
torch.stack(tensors, dim=0, *, out=None) → Tensor

**参数**：
- tensors (sequence of Tensors) – sequence of tensors to concatenate

- dim (int) – dimension to insert. Has to be between 0 and the number of dimensions of concatenated tensors (inclusive)

- out (Tensor, optional) – the output tensor.


In [242]:
import torch
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])
print(torch.stack((a,b),dim=0))
print(torch.stack((a,b),dim=1))

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [249]:
import torch
a = torch.arange(16).reshape(4,4)
b = torch.arange(16).reshape(4,4)*100
print(torch.stack((a,b),dim=0))
print(torch.stack((a,b),dim=1))
print(torch.stack((a,b),dim=2))

tensor([[[   0,    1,    2,    3],
         [   4,    5,    6,    7],
         [   8,    9,   10,   11],
         [  12,   13,   14,   15]],

        [[   0,  100,  200,  300],
         [ 400,  500,  600,  700],
         [ 800,  900, 1000, 1100],
         [1200, 1300, 1400, 1500]]])
tensor([[[   0,    1,    2,    3],
         [   0,  100,  200,  300]],

        [[   4,    5,    6,    7],
         [ 400,  500,  600,  700]],

        [[   8,    9,   10,   11],
         [ 800,  900, 1000, 1100]],

        [[  12,   13,   14,   15],
         [1200, 1300, 1400, 1500]]])
tensor([[[   0,    0],
         [   1,  100],
         [   2,  200],
         [   3,  300]],

        [[   4,  400],
         [   5,  500],
         [   6,  600],
         [   7,  700]],

        [[   8,  800],
         [   9,  900],
         [  10, 1000],
         [  11, 1100]],

        [[  12, 1200],
         [  13, 1300],
         [  14, 1400],
         [  15, 1500]]])


## transpose/swapaxes/swapdims/t
返回一个张量，它是输入的转置版本。给定的维度dim0和dim1被交换。

**定义**：
torch.transpose(input, dim0, dim1) → Tensor

**参数**：
- input (Tensor) – the input tensor.  输入张量

- dim0 (int) – the first dimension to be transposed  要转置的第一个维度

- dim1 (int) – the second dimension to be transposed  要转置的第二个维度


In [251]:
import torch
x = torch.arange(16).reshape(4,4)
print(x)
torch.transpose(x, 0, 1)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])


tensor([[ 0,  4,  8, 12],
        [ 1,  5,  9, 13],
        [ 2,  6, 10, 14],
        [ 3,  7, 11, 15]])

## take
返回一个新的张量，其中包含给定下标处的输入元素。输入张量被看作是一个一维张量。

**定义**：
torch.take(input, index) → Tensor

**参数**：
- input (Tensor) – the input tensor.

- index (LongTensor) – the indices into tensor

In [252]:
import torch
src = torch.tensor([[4, 3, 5],
                    [6, 7, 8]])
torch.take(src, torch.tensor([0, 2, 5]))

tensor([4, 5, 8])

## take_along_dim
从给定dim沿线的索引中选择1维索引处的输入值。

**定义**：
torch.take_along_dim(input, indices, dim, *, out=None) → Tensor

**参数**：
- input (Tensor) – the input tensor.

- indices (tensor) – the indices into input. Must have long dtype.

- dim (int) – dimension to select along.

- out (Tensor, optional) – the output tensor.


In [255]:
import torch
t = torch.tensor([[10, 30, 20], 
                  [60, 40, 50]])
max_idx = torch.argmax(t)
print(max_idx)
torch.take_along_dim(t, max_idx)

tensor(3)


tensor([60])

In [257]:
import torch
t = torch.tensor([[10, 30, 20], 
                  [60, 40, 50]])
sorted_idx = torch.argsort(t, dim=1)
print(sorted_idx)
torch.take_along_dim(t, sorted_idx, dim=1)

tensor([[0, 2, 1],
        [1, 2, 0]])


tensor([[10, 20, 30],
        [40, 50, 60]])

## tensor_split


**定义**：
torch.tensor_split(input, indices_or_sections, dim=0) → List of Tensors

**参数**：
- input (Tensor) – the tensor to split  要分割的张量

- indices_or_sections (Tensor, int or list or tuple of ints) – 分成几个部分

- dim (int, optional) – dimension along which to split the tensor. Default: 0  分割张量的维度


In [262]:
import torch
a = torch.arange(10).reshape(5,2)
print(a)
torch.tensor_split(a, sections=2)
# torch.split(a, [1,4])

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


(tensor([[0, 1],
         [2, 3],
         [4, 5]]),
 tensor([[6, 7],
         [8, 9]]))

## tile
通过重复输入元素来构造一个张量。参数dims指定每个维度中的重复次数。

**定义**：
torch.tile(input, dims) → Tensor

**参数**：
- input (Tensor) – the tensor whose elements to repeat.  需要重复其元素的张量。

- dims (tuple) – the number of repetitions per dimension.  每个维度的重复次数。


In [263]:
import torch
x = torch.tensor([1, 2, 3])
print(x.tile((2,)))
y = torch.tensor([[1, 2], 
                  [3, 4]])
print(torch.tile(y, (2, 2)))

tensor([1, 2, 3, 1, 2, 3])
tensor([[1, 2, 1, 2],
        [3, 4, 3, 4],
        [1, 2, 1, 2],
        [3, 4, 3, 4]])


## unbind
移除一个张量维数。

**定义**：
torch.unbind(input, dim=0) → seq

**参数**：
- input (Tensor) – the tensor to unbind

- dim (int) – dimension to remove


In [270]:
import torch
torch.unbind(torch.tensor([[1, 2, 3],
                           [4, 5, 6],
                           [7, 8, 9]]))

(tensor([1, 2, 3]), tensor([4, 5, 6]), tensor([7, 8, 9]))

## unsqueeze
返回一个插入到指定位置的新张量，其维数为1。

**定义**：
torch.unsqueeze(input, dim) → Tensor

**参数**：
- input (Tensor) – the input tensor.  输入张量

- dim (int) – the index at which to insert the singleton dimension  插入单维度的索引


In [272]:
import torch
x = torch.tensor([1, 2, 3, 4])
torch.unsqueeze(x, 0)
# torch.unsqueeze(x, 1)

tensor([[1, 2, 3, 4]])

## where
返回从x或y中选择的元素的张量，这取决于条件。

$$\operatorname{out}_i=\begin{cases}\mathrm x_i&\text{if condition}_i\\ \mathrm y_i&\text{otherwise}\end{cases}$$

**定义**：
torch.where(condition, x, y) → Tensor

**参数**：
- condition (BoolTensor) – When True (nonzero), yield x, otherwise yield y

- x (Tensor or Scalar) – value (if x is a scalar) or values selected at indices where condition is True

- y (Tensor or Scalar) – value (if y is a scalar) or values selected at indices where condition is False


In [276]:
import torch
x = torch.randn(3, 2)
y = torch.ones(3, 2)
x
torch.where(x > 0, x, y)
# x = torch.randn(2, 2, dtype=torch.double)
# x
# torch.where(x > 0, x, 0.)

tensor([[1.0000, 1.0000],
        [1.2312, 1.0000],
        [1.0000, 0.2993]])

## xxx


**定义**：


**参数**：



## xxx


**定义**：


**参数**：



## xxx


**定义**：


**参数**：

