[![](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/itmorn/AI.handbook/blob/main/DL/torch/nn/Sparse/EmbeddingBag.ipynb)

# EmbeddingBag
在Embedding的基础上做一些reduce操作

**定义**：   
torch.nn.EmbeddingBag(num_embeddings, embedding_dim, max_norm=None, norm_type=2.0, scale_grad_by_freq=False, mode='mean', sparse=False, _weight=None, include_last_offset=False, padding_idx=None, device=None, dtype=None)

**参数**（这里只列举Embedding之外的）：   
- mode (str, optional) – "sum", "mean" or "max". Specifies the way to reduce the bag. "sum" computes the weighted sum, taking per_sample_weights into consideration. "mean" computes the average of the values in the bag, "max" computes the max value over each bag. Default: "mean"  汇总的时候采用的方式



# 图解建表查表
    
<p align="center">
<img src="./imgs/EmbeddingBag.svg"
    width="1000" /></p>


In [44]:
# 调包计算
import torch
import torch.nn as nn
torch.manual_seed(666)
embedding_sum = nn.EmbeddingBag(num_embeddings=5, embedding_dim=3, mode='sum')
print("embedding_sum.weight:\n", embedding_sum.weight, "\n")

input = torch.tensor([3,4,1,2,0], dtype=torch.long)
print("input:\n", input, "\n")

offsets = torch.tensor([0,2,3], dtype=torch.long)
print("offsets group example:\n", embedding_sum(input, offsets), "\n")



embedding_sum.weight:
 Parameter containing:
tensor([[-2.1188,  0.0635, -1.4555],
        [-0.0126, -0.1548, -0.0927],
        [ 2.5916,  0.4542, -0.6890],
        [-0.9962,  0.1856,  0.1476],
        [ 0.8628,  0.2379, -0.5260]], requires_grad=True) 

input:
 tensor([3, 4, 1, 2, 0]) 

offsets group example:
 tensor([[-0.1333,  0.4235, -0.3784],
        [-0.0126, -0.1548, -0.0927],
        [ 0.4728,  0.5177, -2.1445]], grad_fn=<EmbeddingBagBackward0>) 

