[![](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/itmorn/AI.handbook/blob/main/DL/torch/nn/Recurrent/Bilinear.ipynb)

# Bilinear

**定义**：   
torch.nn.Bilinear(in1_features, in2_features, out_features, bias=True, device=None, dtype=None)

**公式**：   
对输入数据应用线性变换:
$$y = x_1^T A x_2 + b$$


**参数**：  
- in1_features (int) – size of each first input sample  第1个输入样本的尺寸

- in2_features (int) – size of each second input sample  第2个输入样本的尺寸

- out_features (int) – size of each output sample  每个输出样本的大小

- bias (bool) – If set to False, the layer will not learn an additive bias. Default: True  如果设置为False，该层将不会学习偏置项。默认值:True


# 图解
假设input1有5个特征，input2有4个特征，Bilinear就是让其两两线性组合，然后相加求和，得到一个值，这就需要有5 * 4个权重。如果指定了out_features，则需要的权重个数为out_features * 5 * 4。
<p align="center">
<img src="./imgs/Bilinear.svg"
    width="700" /></p>

In [14]:
# 调包计算
import torch
import torch.nn as nn
torch.manual_seed(666)

in1_features = 5
in2_features = 4
out_features = 3

input1 = torch.randn(in1_features)
input2 = torch.randn(in2_features)
print("input1:\n", input1, "\n")
print("input2:\n", input2, "\n")

m = nn.Bilinear(in1_features=in1_features, in2_features=in2_features,
                out_features=out_features, bias=True)

print("weight:\n", m.weight, "\n")
print("bias:\n", m.bias, "\n")


output = m(input1, input2)
print("output:\n", output, "\n")


input1:
 tensor([-2.1188,  0.0635, -1.4555, -0.0126, -0.1548]) 

input2:
 tensor([-0.0927,  2.5916,  0.4542, -0.6890]) 

weight:
 Parameter containing:
tensor([[[-0.2116, -0.1177,  0.0031,  0.3657],
         [-0.1070,  0.2271, -0.0749, -0.4392],
         [-0.3878,  0.2782, -0.2086, -0.3934],
         [-0.1719, -0.1892,  0.3502,  0.1000],
         [-0.0857, -0.0380, -0.0867, -0.4229]],

        [[ 0.4011, -0.0096, -0.2735, -0.4184],
         [-0.4034,  0.0349,  0.0544,  0.0158],
         [ 0.2236, -0.0063, -0.0386, -0.2313],
         [-0.0917, -0.1879, -0.1451, -0.3280],
         [-0.0393,  0.2454, -0.1102,  0.1806]],

        [[ 0.0521,  0.3119, -0.1256,  0.3413],
         [ 0.1178,  0.1721, -0.3395,  0.3917],
         [ 0.1595,  0.1653, -0.2504, -0.0383],
         [ 0.1044, -0.0887, -0.2302, -0.4004],
         [-0.0453, -0.1547, -0.2963,  0.0656]]], requires_grad=True) 

bias:
 Parameter containing:
tensor([-0.1685, -0.2100,  0.1036], requires_grad=True) 

output:
 tensor([-0.3567, -0

In [35]:
# 手工计算
import torch
input1 = torch.tensor([[-2.1188,  0.0635, -1.4555, -0.0126, -0.1548]])
print(input1.shape)
input2 = torch.tensor([[-0.0927,  2.5916,  0.4542, -0.6890]]).T
weight = torch.tensor([[[-0.2116, -0.1177,  0.0031,  0.3657],
                        [-0.1070,  0.2271, -0.0749, -0.4392],
                        [-0.3878,  0.2782, -0.2086, -0.3934],
                        [-0.1719, -0.1892,  0.3502,  0.1000],
                        [-0.0857, -0.0380, -0.0867, -0.4229]],

                       [[0.4011, -0.0096, -0.2735, -0.4184],
                        [-0.4034,  0.0349,  0.0544,  0.0158],
                        [0.2236, -0.0063, -0.0386, -0.2313],
                        [-0.0917, -0.1879, -0.1451, -0.3280],
                        [-0.0393,  0.2454, -0.1102,  0.1806]],

                       [[0.0521,  0.3119, -0.1256,  0.3413],
                        [0.1178,  0.1721, -0.3395,  0.3917],
                        [0.1595,  0.1653, -0.2504, -0.0383],
                        [0.1044, -0.0887, -0.2302, -0.4004],
                        [-0.0453, -0.1547, -0.2963,  0.0656]]])
bias = torch.tensor([-0.1685, -0.2100,  0.1036])
print(weight[0].shape)
print(torch.mm(input1, weight[0]))
torch.mm(torch.mm(input1, weight[0]),input2)+bias[0]

# torch.mm(torch.mm(input1, weight),input2)+bias  # 可以看到 结果是一致的


torch.Size([1, 5])
torch.Size([5, 4])
tensor([[ 1.0214, -0.1329,  0.3013, -0.1659]])


tensor([[-0.3563]])

# 参考资料
[Understanding LSTM Networks](https://colah.github.io/posts/2015-08-Understanding-LSTMs/)