[![](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/itmorn/AI.handbook/blob/main/DL/torch/nn/Recurrent/Linear.ipynb)

# Linear
全连接层，对输入做线性变换。

**定义**：   
torch.nn.Linear(in_features, out_features, bias=True, device=None, dtype=None)

**公式**：   
对输入数据应用线性变换:
$$y = xA^T + b$$


**参数**：  
- in_features (int) – size of each input sample  每个输入样本的大小

- out_features (int) – size of each output sample  每个输出样本的大小

- bias (bool) – If set to False, the layer will not learn an additive bias. Default: True  如果设置为False，该层将不会学习偏置项。默认值:True


# 图解
<p align="center">
<img src="./imgs/Linear.svg"
    width="700" /></p>

In [6]:
# 调包计算
import torch
import torch.nn as nn
torch.manual_seed(666)

in_features = 5
out_features = 2 

input = torch.randn(in_features) 
print("input:\n", input, "\n")

m = nn.Linear(in_features=in_features,out_features=out_features,bias=True)

print("weight:\n", m.weight, "\n")
print("bias:\n", m.bias, "\n")


output = m(input)
print("output:\n", output, "\n")


input:
 tensor([-2.1188,  0.0635, -1.4555, -0.0126, -0.1548]) 

weight:
 Parameter containing:
tensor([[ 0.3385,  0.0252, -0.0035,  0.4286,  0.0731],
        [-0.0112, -0.3891,  0.2242, -0.2116, -0.1177]], requires_grad=True) 

bias:
 Parameter containing:
tensor([0.0031, 0.3657], requires_grad=True) 

output:
 tensor([-0.7241,  0.0593], grad_fn=<AddBackward0>) 



In [12]:
# 手工计算
import torch
input = torch.tensor([[-2.1188,  0.0635, -1.4555, -0.0126, -0.1548]])
weight = torch.tensor([[0.3385,  0.0252, -0.0035,  0.4286,  0.0731],
                       [-0.0112, -0.3891,  0.2242, -0.2116, -0.1177]]).T
bias = torch.tensor([[0.0031, 0.3657]])
torch.mm(input,weight)+bias #可以看到 结果是一致的

tensor([[-0.7241,  0.0593]])

# 参考资料
[Understanding LSTM Networks](https://colah.github.io/posts/2015-08-Understanding-LSTMs/)