[![](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/itmorn/AI.handbook/blob/main/DL/torch/nn/DistanceFunction/CosineSimilarity.ipynb)

# CosineSimilarity

**公式**：   
$$\text{similarity} = \dfrac{x_1 \cdot x_2}{\max(\Vert x_1 \Vert _2 \cdot \Vert x_2 \Vert _2, \epsilon)}.$$

**定义**：   
torch.nn.CosineSimilarity(dim=1, eps=1e-08)

**参数**：  
- dim (int, optional) – Dimension where cosine similarity is computed. Default: 1  计算余弦相似度的维度。默认值:1

- eps (float, optional) – Small value to avoid division by zero. Default: 1e-8  避免被0整除。默认值:1 e-8



In [23]:
# 调包计算
import torch
import torch.nn as nn
torch.manual_seed(666)
input1 = torch.randn(5, 3)
input2 = torch.randn(5, 3)
print("input1:\n", input1, "\n")
print("input2:\n", input2, "\n")

cos = nn.CosineSimilarity(dim=1, eps=1e-8)
output = cos(input1, input2)
print("output:\n", output, "\n")

# 手工计算
fenzi = (input1*input2).sum(dim=1)
fenmu = ((input1**2).sum(dim=1)**0.5)*((input2**2).sum(dim=1)**0.5)
fenmu[fenmu<1e-8]=1e-8
fenzi/fenmu # 可以看到和调包结果一致

input1:
 tensor([[-2.1188,  0.0635, -1.4555],
        [-0.0126, -0.1548, -0.0927],
        [ 2.5916,  0.4542, -0.6890],
        [-0.9962,  0.1856,  0.1476],
        [ 0.8628,  0.2379, -0.5260]]) 

input2:
 tensor([[-0.1043, -0.5187,  0.1231],
        [ 0.0755,  0.7091, -1.0812],
        [-0.6668, -0.8967,  0.7272],
        [ 1.4582, -0.0018,  0.6660],
        [ 1.4064, -0.1019, -0.1370]]) 

output:
 tensor([ 0.0063, -0.0447, -0.7270, -0.8252,  0.8576]) 



tensor([ 0.0063, -0.0447, -0.7270, -0.8252,  0.8576])

# 参考资料
[Understanding LSTM Networks](https://colah.github.io/posts/2015-08-Understanding-LSTMs/)