[![](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/itmorn/AI.handbook/blob/main/DL/torch/nn/DistanceFunction/PairwiseDistance.ipynb)

# PairwiseDistance
计算输入向量之间或输入矩阵列之间的成对距离。


**公式**：   
$$\mathrm{dist}\left(x, y\right) = \left\Vert x-y + \epsilon e \right\Vert_p,$$
where $e$ is the vector of ones and the $p$-norm is given by:
$$\Vert x \Vert _p = \left( \sum_{i=1}^n  \vert x_i \vert ^ p \right) ^ {1/p}$$

**定义**：   
torch.nn.CosineSimilarity(dim=1, eps=1e-08)

**参数**：  
- p (real, optional) – the norm degree. Can be negative. Default: 2  标准度。可以是负的。默认值:2

- eps (float, optional) – Small value to avoid division by zero. Default: 1e-6  小值，避免被0整除。默认值:1e-6

- keepdim (bool, optional) – Determines whether or not to keep the vector dimension. Default: False  决定是否保留向量维度。默认值:False

In [10]:
# 调包计算
import torch
import torch.nn as nn
torch.manual_seed(666)
input1 = torch.randn(5, 3)
input2 = torch.randn(5, 3)
print("input1:\n", input1, "\n")
print("input2:\n", input2, "\n")

p=2
pdist = nn.PairwiseDistance(p=p)
output = pdist(input1, input2)

print("output:\n", output, "\n")

# # 手工计算
((input1-input2+1e-8).abs()**p).sum(dim=1)**(1/p) # 可以看到和调包结果一致

input1:
 tensor([[-2.1188,  0.0635, -1.4555],
        [-0.0126, -0.1548, -0.0927],
        [ 2.5916,  0.4542, -0.6890],
        [-0.9962,  0.1856,  0.1476],
        [ 0.8628,  0.2379, -0.5260]]) 

input2:
 tensor([[-0.1043, -0.5187,  0.1231],
        [ 0.0755,  0.7091, -1.0812],
        [-0.6668, -0.8967,  0.7272],
        [ 1.4582, -0.0018,  0.6660],
        [ 1.4064, -0.1019, -0.1370]]) 

output:
 tensor([2.6247, 1.3158, 3.8010, 2.5155, 0.7498]) 



tensor([2.6247, 1.3158, 3.8010, 2.5155, 0.7498])

# 参考资料
[Understanding LSTM Networks](https://colah.github.io/posts/2015-08-Understanding-LSTMs/)