[![](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/itmorn/AI.handbook/blob/main/DL/torch/nn/LossFunction/BCELoss.ipynb)

# BCELoss
创建一个标准来测量目标和输入概率之间的二进制交叉熵（Binary Cross Entropy）。

**定义**：  
torch.nn.BCELoss(weight=None, size_average=None, reduce=None, reduction='mean')

**参数**:  
- weight (Tensor, optional) – a manual rescaling weight given to each class. If given, has to be a Tensor of size C  给每个类一个手动缩放的权重。如果给定，必须是一个大小为C的张量

- reduction (str, optional) – Specifies the reduction to apply to the output: 'none' | 'mean' | 'sum'.   指定应用于输出的缩减:'none' | 'mean' | 'sum'。

In [18]:
import torch
import torch.nn as nn
torch.manual_seed(666)

m = nn.Sigmoid()
loss = nn.BCELoss()
input = torch.randn(3, requires_grad=True)
print("input:\n", input, "\n")

target = torch.empty(3).random_(2)
print("target:\n", target, "\n")

pred = m(input)
print("pred:\n", pred, "\n")

loss = loss(pred, target)
loss.backward()
print("loss:\n", loss, "\n")

# // Binary cross entropy tensor is defined by the equation:
# https://github.com/pytorch/pytorch/blob/c0fa0669f66b697995389cc80dea8990b792de16/aten/src/ATen/native/Loss.cpp
# // L = -w (y ln(x) + (1-y) ln(1-x))
x = input.sigmoid()
print("pred_hand:\n", x, "可以看到和pred一致\n")
print("loss_hand:\n", -(x.log()*target+(1-x).log()*(1-target)).mean(), "可以看到和loss一致\n")



input:
 tensor([-2.1188,  0.0635, -1.4555], requires_grad=True) 

target:
 tensor([0., 1., 1.]) 

pred:
 tensor([0.1073, 0.5159, 0.1892], grad_fn=<SigmoidBackward0>) 

loss:
 tensor(0.8135, grad_fn=<BinaryCrossEntropyBackward0>) 

pred_hand:
 tensor([0.1073, 0.5159, 0.1892], grad_fn=<SigmoidBackward0>) 可以看到和pred一致

loss_hand:
 tensor(0.8135, grad_fn=<NegBackward0>) 可以看到和loss一致

