[![](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/itmorn/AI.handbook/blob/main/DL/torch/nn/LossFunction/MarginRankingLoss.ipynb)

# MarginRankingLoss
 如果y = 1，那么它假设第一个输入的值应该比第二个输入的值更高(值更大)，反之亦然。

$$\text{loss}(x1, x2, y) = \max(0, -y * (x1 - x2) + \text{margin})$$


**定义**：  
torch.nn.MarginRankingLoss(margin=0.0, size_average=None, reduce=None, reduction='mean')

**参数**:  
- margin (float, optional) – Has a default value of 0.

- reduction (str, optional) – Specifies the reduction to apply to the output: 'none' | 'mean' | 'sum'.   指定应用于输出的reduce方式:'none' | 'mean' | 'sum'。

In [18]:
import torch
import torch.nn as nn
torch.manual_seed(666)
margin=1
loss = nn.MarginRankingLoss(margin=margin)
input1 = torch.randn(3, requires_grad=True) #一个batch中有3个样本
input2 = torch.randn(3, requires_grad=True)
target = torch.randn(3).sign()
print("input1:\n", input1, "\n")
print("input2:\n", input2, "\n")
print("target:\n", target, "\n")

output = loss(input1, input2, target)
print("output:\n", output, "\n")

(-target * (input1 - input2) + margin).clip(min=0).mean()

input1:
 tensor([-2.1188,  0.0635, -1.4555], requires_grad=True) 

input2:
 tensor([-0.0126, -0.1548, -0.0927], requires_grad=True) 

target:
 tensor([ 1.,  1., -1.]) 

output:
 tensor(1.2960, grad_fn=<MeanBackward0>) 



tensor(1.2960, grad_fn=<MeanBackward0>)