[![](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/itmorn/AI.handbook/blob/main/DL/torch/nn/Vision/PixelShuffle.ipynb)

# PixelShuffle
PixelShuffle是PyTorch中的一种视觉层，它可以将一个高通道、低分辨率的输入张量转换成一个低通道、高分辨率的输出张量，从而可以用于超分辨率图像重建等任务。

可以将( * , C × r^2, H, W) 转为 (*, C, H × r, W × r).其中r是一个缩放因子。

**定义**：  
torch.nn.PixelShuffle(upscale_factor)

**参数**:  
- upscale_factor (int) – factor to increase spatial resolution by  增加空间分辨率的缩放因子。

# PixelUnshuffle
PixelShuffle的逆向操作。可以将一个低通道、高分辨率的输入张量转换成一个高通道、低分辨率的输出张量。PixelUnshuffle的作用类似于图像降采样，通常用于图像压缩等任务。

**定义**：  
torch.nn.PixelUnshuffle(downscale_factor)

**参数**:  
- downscale_factor (int) – factor to decrease spatial resolution by  降低空间分辨率的缩放因子。

# 图解PixelShuffle和PixelUnshuffle
<p align="center">
<img src="./imgs/PixelShuffle.svg"
    width="1000" /></p>

In [1]:
# 单个样本简单举例
import torch
import torch.nn as nn
torch.manual_seed(666)

pixel_shuffle = nn.PixelShuffle(upscale_factor=2)
input = torch.randn(1, 4, 2, 2)
print("input:\n", input, "\n")
output_shuffle = pixel_shuffle(input)
print("output_shuffle:\n", output_shuffle, "\n")

pixel_unshuffle = nn.PixelUnshuffle(downscale_factor=2)
output_unshuffle = pixel_unshuffle(output_shuffle)
print("output_unshuffle:\n", output_unshuffle, "\n")

input:
 tensor([[[[-0.7747,  0.7926],
          [-0.0062, -0.4377]],

         [[ 0.4657, -0.1880],
          [-0.8975,  0.4169]],

         [[-0.3840,  0.0394],
          [ 0.4869, -0.1476]],

         [[-0.4459, -0.0336],
          [ 0.0221, -0.0550]]]]) 

output_shuffle:
 tensor([[[[-0.7747,  0.4657,  0.7926, -0.1880],
          [-0.3840, -0.4459,  0.0394, -0.0336],
          [-0.0062, -0.8975, -0.4377,  0.4169],
          [ 0.4869,  0.0221, -0.1476, -0.0550]]]]) 

output_unshuffle:
 tensor([[[[-0.7747,  0.7926],
          [-0.0062, -0.4377]],

         [[ 0.4657, -0.1880],
          [-0.8975,  0.4169]],

         [[-0.3840,  0.0394],
          [ 0.4869, -0.1476]],

         [[-0.4459, -0.0336],
          [ 0.0221, -0.0550]]]]) 

