[![](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/itmorn/AI.handbook/blob/main/DL/torch/nn/Vision/Upsample.ipynb)

# Upsample
上采样

**定义**：  
torch.nn.Upsample(size=None, scale_factor=None, mode='nearest', align_corners=None, recompute_scale_factor=None)

**参数**:  
- size (int or Tuple[int] or Tuple[int, int] or Tuple[int, int, int], optional) – output spatial sizes  输出空间大小

- scale_factor (float or Tuple[float] or Tuple[float, float] or Tuple[float, float, float], optional) – multiplier for spatial size. Has to match input size if it is a tuple.  空间大小的乘数

- align_corners (bool, optional) – if True, the corner pixels of the input and output tensors are aligned, and thus preserving the values at those pixels. This only has effect when mode is 'linear', 'bilinear', 'bicubic', or 'trilinear'. Default: False  如果为True，输入和输出张量的角像素是对齐的，从而保留这些像素的值。这只在模式为“线性”、“双线性”、“双三线性”时才有效。默认值:假

注意：align_corners的方式，一般来说不会影响到最终模型的效果，参考https://github.com/pytorch/vision/issues/1708

# 图解PixelShuffle和PixelUnshuffle
<p align="center">
<img src="./imgs/align_corners.svg"
    width="2000" /></p>

In [2]:
# 单个样本简单举例
import torch
import torch.nn as nn
torch.manual_seed(66666)

input = torch.randint(0,10,(1,1,4,4)).float()
print("input:\n", input, "\n")

m = nn.Upsample(scale_factor=2, mode='nearest')
print("nearest:\n", m(input), "\n")

m = nn.Upsample(scale_factor=2, mode='bilinear', align_corners=False)
print("bilinear:\n", m(input), "\n")

m = nn.Upsample(scale_factor=2, mode='bilinear', align_corners=True)
print("bilinear:\n", m(input), "\n")

input:
 tensor([[[[2., 6., 4., 3.],
          [4., 0., 7., 6.],
          [8., 8., 7., 5.],
          [9., 0., 3., 1.]]]]) 

nearest:
 tensor([[[[2., 2., 6., 6., 4., 4., 3., 3.],
          [2., 2., 6., 6., 4., 4., 3., 3.],
          [4., 4., 0., 0., 7., 7., 6., 6.],
          [4., 4., 0., 0., 7., 7., 6., 6.],
          [8., 8., 8., 8., 7., 7., 5., 5.],
          [8., 8., 8., 8., 7., 7., 5., 5.],
          [9., 9., 0., 0., 3., 3., 1., 1.],
          [9., 9., 0., 0., 3., 3., 1., 1.]]]]) 

bilinear:
 tensor([[[[2.0000, 3.0000, 5.0000, 5.5000, 4.5000, 3.7500, 3.2500, 3.0000],
          [2.5000, 3.0000, 4.0000, 4.5625, 4.6875, 4.5000, 4.0000, 3.7500],
          [3.5000, 3.0000, 2.0000, 2.6875, 5.0625, 6.0000, 5.5000, 5.2500],
          [5.0000, 4.2500, 2.7500, 3.2500, 5.7500, 6.6875, 6.0625, 5.7500],
          [7.0000, 6.7500, 6.2500, 6.2500, 6.7500, 6.5625, 5.6875, 5.2500],
          [8.2500, 7.6875, 6.5625, 6.0000, 6.0000, 5.5000, 4.5000, 4.0000],
          [8.7500, 7.0625, 3.6875, 2.5000

# UpsamplingBilinear2d
It is equivalent to nn.functional.interpolate(..., mode='bilinear', align_corners=True)

# UpsamplingNearest2d
等价于nn.Upsample(..., mode='nearest')

input = torch.arange(1, 5, dtype=torch.float32).view(1, 1, 2, 2)
input
tensor([[[[1., 2.],
          [3., 4.]]]])

m = nn.UpsamplingNearest2d(scale_factor=2)
m(input)
tensor([[[[1., 1., 2., 2.],
          [1., 1., 2., 2.],
          [3., 3., 4., 4.],
          [3., 3., 4., 4.]]]])

# 参考资料
https://www.bilibili.com/video/BV1Xy4y1i7hy

https://discuss.pytorch.org/t/what-we-should-use-align-corners-false/22663/9