[![](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/itmorn/AI.handbook/blob/main/DL/torch/nn/MathOperations/MathOperations.ipynb)

# 按元素操作(Pointwise Ops)

## abs/absolute
计算输入中每个元素的绝对值。
$$\text{out}_i=|\text{input}_i|$$

**定义**：  
torch.abs(input, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- out (Tensor, optional) – the output tensor.  输出张量

In [1]:
import torch

torch.abs(torch.tensor([-1, -2, 3]))

tensor([1, 2, 3])

## acos/arccos
计算输入中每个元素的逆余弦。

$$\text{out}_i=\cos^{-1}(\operatorname{input}_i)$$

**定义**：  
torch.acos(input, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- out (Tensor, optional) – the output tensor.  输出张量

In [7]:
import torch
a = torch.randn(4)
print(a)
torch.acos(a)

tensor([-0.3200,  0.1387, -3.0484, -0.4391])


tensor([1.8965, 1.4316,    nan, 2.0254])

## acosh/arccosh
返回输入元素的反双曲余弦的新张量。
$$\text{out}_i=\cosh^{-1}(\operatorname{input}_i)$$

**定义**：  
torch.acosh(input, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- out (Tensor, optional) – the output tensor.  输出张量

In [9]:
import torch
a = torch.randn(4).uniform_(1, 2)
a
torch.acosh(a)

tensor([0.7808, 1.1149, 0.9426, 1.2994])

## add

$$\text{out}_i=\text{input}_i+\text{alpha}\times\text{other}_i$$

**定义**：  
torch.add(input, other, *, alpha=1, out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- other (Tensor or Number) – the tensor or number to add to input.  要添加到输入中的张量或数字

- alpha (Number) – the multiplier for other.  other的乘数

- out (Tensor, optional) – the output tensor.  输出张量

In [15]:
import torch
a = torch.arange(10)
print(a)
torch.add(input=a, other=100)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


tensor([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [16]:
import torch
a = torch.arange(10)
b = torch.ones_like(a)
torch.add(input=a, other=b, alpha=100)

tensor([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

## addcdiv
执行tensor1与tensor2的逐元素除法，将结果乘以标量值并将其添加到输入中。

$$\text{out}_i=\text{input}_i+\text{value}\times\dfrac{\text{tensor}1_i}{\text{tensor}2_i}$$

**定义**：  
torch.addcdiv(input, tensor1, tensor2, *, value=1, out=None) → Tensor

**参数**：  
- input (Tensor) – the tensor to be added  要加的张量

- tensor1 (Tensor) – the numerator tensor  分子张量

- tensor2 (Tensor) – the denominator tensor  分母张量

- value (Number, optional) – multiplier for tensor1 / tensor2.   tensor1 / tensor2的乘子

- out (Tensor, optional) – the output tensor.  输出张量。

In [20]:
import torch
t = torch.randn(1, 3)
t1 = torch.randn(3, 1)
t2 = torch.randn(1, 3)
torch.addcdiv(t, t1, t2, value=0.1)

tensor([[1.7674, 1.3758, 0.6647],
        [1.2805, 1.1478, 0.7561],
        [0.7085, 0.8800, 0.8634]])

## addcmul
执行tensor1与tensor2的元素乘法，将结果乘以标量值并将其添加到输入中。
$$\text{out}_i=\mathrm{input}_i+\mathrm{value}\times\mathrm{tensor1}_i\times\mathrm{tensor2}_i$$

**定义**：  
torch.addcmul(input, tensor1, tensor2, *, value=1, out=None) → Tensor

**参数**：  
- input (Tensor) – the tensor to be added   要加的张量

- tensor1 (Tensor) – the tensor to be multiplied  要乘的张量

- tensor2 (Tensor) – the tensor to be multiplied  要乘的张量

- value (Number, optional) – multiplier for tensor1∗tensor2.  tensor1∗tensor2的乘子

- out (Tensor, optional) – the output tensor.  输出张量。

In [24]:
import torch
t = torch.randn(1, 3)
t1 = torch.randn(3, 1)
t2 = torch.randn(1, 3)
torch.addcmul(t, t1, t2, value=0.1)

tensor([[-1.5827, -0.7309,  2.5973],
        [-1.6367, -0.8269,  2.6584],
        [-1.6840, -0.9110,  2.7119]])

## angle
计算给定输入张量的元素角度(弧度)。
$$\text{out}_i=angle(\operatorname{input}_i)$$

**定义**：  
torch.angle(input, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- out (Tensor, optional) – the output tensor.  输出张量

In [25]:
import torch
torch.angle(torch.tensor([-1 + 1j, -2 + 2j, 3 - 3j]))*180/3.14159

tensor([135.0001, 135.0001, -45.0000])

## asin/arcsin
返回一个带有输入元素arcsin的新张量。

$$\text{out}_i=\sin^{-1}(\operatorname{input}_i)$$

**定义**：  
torch.asin(input, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- out (Tensor, optional) – the output tensor.  输出张量

In [27]:
import torch
a = torch.randn(4)
torch.asin(a)

tensor([   nan, 0.2574, 0.8200, 0.9444])

## asinh/arcsinh

$$\text{out}_i=\sinh^{-1}(\operatorname{input}_i)$$

**定义**：  
torch.asinh(input, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- out (Tensor, optional) – the output tensor.  输出张量

In [28]:
import torch
a = torch.randn(4)
a
torch.asinh(a)

tensor([-0.1693,  1.0191, -0.1025, -0.0610])

## atan/arctan


返回一个带有输入元素arctan值的新张量。

$$\text{out}_i=\tan^{-1}(\operatorname{input}_i)$$

**定义**：  
torch.atan(input, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- out (Tensor, optional) – the output tensor.  输出张量

In [29]:
import torch
a = torch.randn(4)
a
torch.atan(a)

tensor([ 0.7518, -0.7453, -0.4551,  0.6872])

## atanh/arctanh
返回输入元素的反双曲正切的新张量。

$$\text{out}_i=\tanh^{-1}(\text{input}_i)$$

**定义**：  
torch.atanh(input, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- out (Tensor, optional) – the output tensor.  输出张量

In [30]:
import torch
a = torch.randn(4).uniform_(-1, 1)
a
torch.atanh(a)

tensor([-0.0184, -0.6261, -1.1195, -0.7628])

## atan2/arctan2

$$\operatorname{atan2}(y,x)=\begin{cases}\arctan(\frac yx)&\text{if }x>0,\\ \arctan(\frac yx)+\pi&\text{if }x<0\text{ and }y\ge0,\\\arctan(\frac yx)-\pi&\text{if }{x<0}\text{ and }y<0,\\ +\frac\pi2&\text{if }x=0\text{ and }y>0,\\ -\frac\pi2&\operatorname{if }x=0\operatorname{ and }{y<0},\\ \operatorname{undefined}&\text{if }{x=0}\text{ and }y=0.\end{cases}$$

https://stackoverflow.com/questions/35749246/python-atan-or-atan2-what-should-i-use

**定义**：  
torch.atan2(input, other, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the first input tensor  第一个输入张量

- other (Tensor) – the second input tensor  第二个输入张量

- out (Tensor, optional) – the output tensor.  输出张量

In [31]:
import torch
a = torch.randn(4)
a
torch.atan2(a, torch.randn(4))

tensor([-2.7770, -0.7276, -0.1640,  2.9073])

## bitwise_not/logical_not

计算给定输入张量的位NOT。输入张量必须为整型或布尔型。对于bool张量，它计算逻辑NOT。

**定义**：  
torch.bitwise_not(input, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- out (Tensor, optional) – the output tensor.  输出张量


In [47]:
import torch
torch.bitwise_not(torch.tensor([0, 1, 2], dtype=torch.uint8))
# 0000 0000 -> 1111 1111
# 0000 0001 -> 1111 1110
# 0000 0010 -> 1111 1101 

tensor([255, 254, 253], dtype=torch.uint8)

## bitwise_and/logical_and

计算输入和其他的位与。输入张量必须为整型或布尔型。对于bool张量，它计算逻辑与。

**定义**：  
torch.bitwise_and(input, other, *, out=None) → Tensor

**参数**：  
- input – the first input tensor  第一个输入张量

- other – the second input tensor  第二个输入张量

- out (Tensor, optional) – the output tensor.  输出张量


In [48]:
import torch
torch.bitwise_and(torch.tensor([-1, -2, 3], dtype=torch.int8),
                  torch.tensor([1, 0, 3], dtype=torch.int8))
torch.bitwise_and(torch.tensor([True, True, False]),
                  torch.tensor([False, True, False]))


tensor([False,  True, False])

## bitwise_or/logical_or

计算输入和其他的位或。输入张量必须为整型或布尔型。对于bool张量，它计算逻辑或。

**定义**：  
torch.bitwise_or(input, other, *, out=None) → Tensor

**参数**：  
- input – the first input tensor  第一个输入张量

- other – the second input tensor  第二个输入张量

- out (Tensor, optional) – the output tensor.  输出张量


In [49]:
import torch
torch.bitwise_or(torch.tensor([-1, -2, 3], dtype=torch.int8),
                  torch.tensor([1, 0, 3], dtype=torch.int8))
torch.bitwise_or(torch.tensor([True, True, False]),
                  torch.tensor([False, True, False]))


tensor([ True,  True, False])

## bitwise_xor/logical_xor

计算输入和其他的位异或。输入张量必须为整型或布尔型。对于bool张量，它计算逻辑异或。

**定义**：  
torch.bitwise_xor(input, other, *, out=None) → Tensor

**参数**：  
- input – the first input tensor  第一个输入张量

- other – the second input tensor  第二个输入张量

- out (Tensor, optional) – the output tensor.  输出张量


In [50]:
import torch
torch.bitwise_xor(torch.tensor([-1, -2, 3], dtype=torch.int8),
                  torch.tensor([1, 0, 3], dtype=torch.int8))
torch.bitwise_xor(torch.tensor([True, True, False]),
                  torch.tensor([False, True, False]))


tensor([ True, False, False])

## bitwise_left_shift
计算输入的左算术移位。输入张量必须是整型的。
$$\text{out}_i=\text{input}_i<<\text{other}_i$$

**定义**：  
torch.bitwise_left_shift(input, other, *, out=None) → Tensor

**参数**：  
- input – the first input tensor  第一个输入张量

- other – the second input tensor  第二个输入张量

- out (Tensor, optional) – the output tensor.  输出张量


In [51]:
import torch
print(3<<3)
torch.bitwise_left_shift(torch.tensor([-1, -2, 3], dtype=torch.int8),
                         torch.tensor([1, 0, 3], dtype=torch.int8))


tensor([-2, -2, 24], dtype=torch.int8)

## bitwise_right_shift
计算输入的右算术移位。输入张量必须是整型的。
$$\text{out}_i=\text{input}_i>>\text{other}_i$$

**定义**：  
torch.bitwise_right_shift(input, other, *, out=None) → Tensor

**参数**：  
- input – the first input tensor  第一个输入张量

- other – the second input tensor  第二个输入张量

- out (Tensor, optional) – the output tensor.  输出张量


In [55]:
import torch
print(31 >> 3)
torch.bitwise_right_shift(torch.tensor([-2, -7, 31], dtype=torch.int8),
                          torch.tensor([1, 0, 3], dtype=torch.int8))

3


tensor([-1, -7,  3], dtype=torch.int8)

## ceil
向上取整

$$\text{out}_i=\lceil\operatorname{input}_i\rceil$$

**定义**：  
torch.ceil(input, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- out (Tensor, optional) – the output tensor.  输出张量


In [57]:
import torch
a = torch.randn(4)
print(a)
torch.ceil(a)

tensor([-0.3689, -0.0410,  1.4594, -1.5169])


tensor([-0., -0.,  2., -1.])

## clamp/clip
夹住.  
将输入的所有元素固定在[min, max]范围内

$$y_i=\min(\max(x_i,\min\text{value}_i),\max\text{value}_i)$$

**定义**：  
torch.clamp(input, min=None, max=None, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- min (Number or Tensor, optional) – lower-bound of the range to be clamped to  要夹紧的范围的下限

- max (Number or Tensor, optional) – upper-bound of the range to be clamped to  要夹紧的范围的上限

- out (Tensor, optional) – the output tensor.  输出张量


In [1]:
import torch
a = torch.randn(4)
print(a)
print(torch.clamp(a, min=-0.5, max=0.5))

min = torch.linspace(-1, 1, steps=4)
print(min)
torch.clamp(a, min=min)

tensor([-0.2149,  0.7258,  0.5111, -2.4046])
tensor([-0.2149,  0.5000,  0.5000, -0.5000])
tensor([-1.0000, -0.3333,  0.3333,  1.0000])


tensor([-0.2149,  0.7258,  0.5111,  1.0000])

## conj_physical
计算给定输入张量的元素共轭。

$$\text{out}_i=conj(\text{input}_i)$$

**定义**：  
torch.conj_physical(input, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- out (Tensor, optional) – the output tensor.  输出张量


In [2]:
import torch
torch.conj_physical(torch.tensor([-1 + 1j, -2 + 2j, 3 - 3j]))

tensor([-1.-1.j, -2.-2.j,  3.+3.j])

## copysign
用input的大小和other的符号创建一个新的浮点张量。
$$\operatorname{out}_i=\begin{cases}-|\operatorname{input}_i|&\text{if other}_i\leq-0.0\\ |\operatorname{imput}_i|&\text{if other}_i\geq0.0\end{cases}$$

**定义**：  
torch.copysign(input, other, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- out (Tensor, optional) – the output tensor.  输出张量


In [4]:
import torch
a = torch.randn(4)
print(a)
b = torch.randn(4)
print(b)

torch.copysign(a, b)

tensor([-0.2094, -0.7962,  0.0462,  0.0176])
tensor([-0.3092, -0.5713,  0.0554, -0.6485])


tensor([-0.2094, -0.7962,  0.0462, -0.0176])

## cos

$$\text{out}_i=\cos(\text{input}_i)$$

**定义**：  
torch.cos(input, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- out (Tensor, optional) – the output tensor.  输出张量


In [7]:
import torch
a = torch.randn(4)
torch.cos(a)

tensor([ 0.9805, -0.2416,  0.9493,  0.9866])

## cosh
返回一个包含输入元素的双曲余弦的新张量。

$$\text{out}_i=\cosh(\operatorname{input}_i)$$

**定义**：  
torch.cosh(input, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- out (Tensor, optional) – the output tensor.  输出张量


In [8]:
import torch
a = torch.randn(4)
torch.cosh(a)

tensor([1.0995, 1.3152, 1.9244, 1.8898])

## deg2rad
返回一个新的张量，其中输入的每个元素都从角度转换为弧度。

**定义**：  
torch.deg2rad(input, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- out (Tensor, optional) – the output tensor.  输出张量


In [9]:
import torch
a = torch.tensor([[180.0, -180.0], [360.0, -360.0], [90.0, -90.0]])
torch.deg2rad(a)

tensor([[ 3.1416, -3.1416],
        [ 6.2832, -6.2832],
        [ 1.5708, -1.5708]])

## div/divide/true_divide
将输入输入的每个元素除以其他输入的相应元素。

true_divide和 torch.div() with rounding_mode=None一致.

$$\text{out}_i=\dfrac{\text{input}_i}{\text{other}_i}$$

**定义**：  
torch.div(input, other, *, rounding_mode=None, out=None) → Tensor

**参数**：  
- input (Tensor) – the dividend 被除数

- other (Tensor or Number) – the divisor 除数

- out (Tensor, optional) – the output tensor.  输出张量

- rounding_mode (str, optional) – None、trunc、floor 

In [10]:
import torch
x = torch.tensor([ 0.3810,  1.2774, -0.2972, -0.3719,  0.4637])
print(torch.div(x, 0.5))

a = torch.tensor([[-0.3711, -1.9353, -0.4605, -0.2917],
                  [ 0.1815, -1.0111,  0.9805, -1.5923],
                  [ 0.1062,  1.4581,  0.7759, -1.2344],
                  [-0.1830, -0.0313,  1.1908, -1.4757]])
b = torch.tensor([ 0.8032,  0.2930, -0.8113, -0.2308])
print(torch.div(a, b))

print(torch.div(a, b, rounding_mode='trunc'))

print(torch.div(a, b, rounding_mode='floor'))

tensor([ 0.7620,  2.5548, -0.5944, -0.7438,  0.9274])
tensor([[-0.4620, -6.6051,  0.5676,  1.2639],
        [ 0.2260, -3.4509, -1.2086,  6.8990],
        [ 0.1322,  4.9764, -0.9564,  5.3484],
        [-0.2278, -0.1068, -1.4678,  6.3938]])
tensor([[-0., -6.,  0.,  1.],
        [ 0., -3., -1.,  6.],
        [ 0.,  4., -0.,  5.],
        [-0., -0., -1.,  6.]])
tensor([[-1., -7.,  0.,  1.],
        [ 0., -4., -2.,  6.],
        [ 0.,  4., -1.,  5.],
        [-1., -1., -2.,  6.]])


## exp

$$y_i=e^{x_i}$$

**定义**：  
torch.exp(input, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- out (Tensor, optional) – the output tensor.  输出张量


In [11]:
import torch
import math

torch.exp(torch.tensor([0, math.log(2.)]))

tensor([1., 2.])

## trunc/fix

返回一个新的张量，包含输入元素的截断整数值。

**定义**：  
torch.trunc(input, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- out (Tensor, optional) – the output tensor.  输出张量


In [13]:
import torch
a = torch.randn(4)
print(a)
torch.trunc(a)

tensor([ 1.0509, -1.0209, -0.1938, -0.1570])


tensor([ 1., -1., -0., -0.])

## float_power
提高输入的指数次幂

**定义**：  
torch.float_power(input, exponent, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- exponent (Tensor or Number) – the exponent value(s)  指数值

- out (Tensor, optional) – the output tensor.  输出张量


In [14]:
import torch
a = torch.arange(1, 5)
print(a)
exp = torch.tensor([2, -3, 4, -5])
torch.float_power(a, exp)

tensor([1, 2, 3, 4])


tensor([1.0000e+00, 1.2500e-01, 8.1000e+01, 9.7656e-04], dtype=torch.float64)

## floor

$$\text{out}_i=\lfloor\operatorname{input}_i\rfloor$$

**定义**：  
torch.floor(input, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- out (Tensor, optional) – the output tensor.  输出张量


In [15]:
import torch
a = torch.randn(4)
print(a)
torch.floor(a)

tensor([ 1.2759,  1.7243, -1.9898,  0.4412])


tensor([ 1.,  1., -2.,  0.])

## floor_divide

$$\text{out}_i=\text{floor}\left(\dfrac{\text{input}_i}{\text{other}_i}\right)$$

**定义**：  
torch.floor_divide(input, other, *, out=None) → Tensor

**参数**：  
- input (Tensor or Number) – the dividend 被除数

- other (Tensor or Number) – the divisor  除数

- out (Tensor, optional) – the output tensor.  输出张量


In [18]:
import torch
a = torch.tensor([4.0, 3.0])
b = torch.tensor([2.0, 2.0])
print(torch.floor_divide(a, b))
print(torch.floor_divide(a, 1.4))

tensor([2., 1.])
tensor([2., 2.])


## frac

计算输入中每个元素的小数部分。

$$\text{out}_i=\text{input}_i-\lfloor|\text{input}_i|\rfloor*\text{sgn}(\text{input}_i)$$

**定义**：  
torch.frac(input, *, out=None) → Tensor

In [19]:
import torch
torch.frac(torch.tensor([1, 2.5, -3.2]))

tensor([ 0.0000,  0.5000, -0.2000])

## frexp
将输入分解为尾数和指数张量

$$\mathrm{input}=\mathrm{mantissa}\times2^{\mathrm{exponent}}.$$

**定义**：  
torch.frexp(input, *, out=None) -> (Tensor mantissa, Tensor exponent)

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- out (Tensor, optional) – the output tensor.  输出张量


In [20]:
import torch
x = torch.arange(9.)
mantissa, exponent = torch.frexp(x)
print(mantissa)
print(exponent)

tensor([0.0000, 0.5000, 0.5000, 0.7500, 0.5000, 0.6250, 0.7500, 0.8750, 0.5000])
tensor([0, 1, 2, 2, 3, 3, 3, 3, 4], dtype=torch.int32)


## ldexp

$$\text{out}_i=\operatorname{input}_i*2_i^{\operatorname{other}}$$

**定义**：  
torch.ldexp(input, other, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- other (Tensor) – a tensor of exponents, typically integers.  一个指数张量，通常是整数。

- out (Tensor, optional) – the output tensor.  输出张量


In [25]:
import torch
# torch.ldexp(torch.tensor([1.]), torch.tensor([1]))
torch.ldexp(torch.tensor([1.0]), torch.tensor([1, 2, 3, 4]))

tensor([ 2.,  4.,  8., 16.])

## lerp
torch.lerp的全称是“torch linear interpolation”，它是PyTorch中的一个函数，用于对两个张量进行线性插值。

$$\text{out}_i=\text{start}_i+\text{weight}_i\times(\text{end}_i-\text{start}_i)$$

**定义**：  
torch.lerp(input, end, weight, *, out=None)

**参数**：  
- input (Tensor) – the tensor with the starting points  起始点的张量

- end (Tensor) – the tensor with the ending points  带有端点的张量

- weight (float or tensor) – the weight for the interpolation formula  插值公式的权重

- out (Tensor, optional) – the output tensor.  输出张量


In [26]:
import torch
start = torch.arange(1., 5.)
end = torch.empty(4).fill_(10)
print(start)
print(end)
torch.lerp(start, end, 0.5)
# torch.lerp(start, end, torch.full_like(start, 0.5))

tensor([1., 2., 3., 4.])
tensor([10., 10., 10., 10.])


tensor([5.5000, 6.0000, 6.5000, 7.0000])

## lgamma

$$\operatorname{out}_i=\ln\Gamma(|\operatorname{input}_i|)$$

**定义**：  
torch.lgamma(input, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- out (Tensor, optional) – the output tensor.  输出张量


In [27]:
import torch
a = torch.arange(0.5, 2, 0.5)
torch.lgamma(a)

tensor([ 0.5724,  0.0000, -0.1208])

## log

$$y_i=\log_e(x_i)$$

**定义**：  
torch.log(input, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- out (Tensor, optional) – the output tensor.  输出张量


In [32]:
import torch
a = torch.arange(5)
print(torch.log(a))

tensor([  -inf, 0.0000, 0.6931, 1.0986, 1.3863])


## log10

$$y_i=\log_{10}(x_i)$$

**定义**：  
torch.log10(input, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- out (Tensor, optional) – the output tensor.  输出张量

In [33]:
import torch
a = torch.arange(5)
print(torch.log10(a))

tensor([  -inf, 0.0000, 0.3010, 0.4771, 0.6021])


## log2

$$y_i=\log_2(x_i)$$

**定义**：  
torch.log2(input, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- out (Tensor, optional) – the output tensor.  输出张量

In [34]:
import torch
a = torch.arange(5)
print(torch.log2(a))

tensor([  -inf, 0.0000, 1.0000, 1.5850, 2.0000])


## logaddexp

$$\log\left(e^x+e^y\right)$$

**定义**：  
torch.logaddexp(input, other, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- other (Tensor) – the second input tensor  第二个输入张量

- out (Tensor, optional) – the output tensor.  输出张量


In [38]:
import torch
torch.logaddexp(torch.tensor([-1.0]), torch.tensor([-1.0, -2, -3]))
torch.logaddexp(torch.tensor([100.0, -200, -300]), torch.tensor([-1.0, -2, -3]))
# torch.logaddexp(torch.tensor([1.0, 2000, 30000]), torch.tensor([-1.0, -2, -3]))

tensor([100.,  -2.,  -3.])

## logaddexp2

$$\log\left(2^x+2^y\right)$$

**定义**：  
torch.logaddexp2(input, other, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- other (Tensor) – the second input tensor  第二个输入张量

- out (Tensor, optional) – the output tensor.  输出张量


In [39]:
import torch
torch.logaddexp2(torch.tensor([-1.0]), torch.tensor([-1.0, -2, -3]))
torch.logaddexp2(torch.tensor([100.0, -200, -300]), torch.tensor([-1.0, -2, -3]))
# torch.logaddexp(torch.tensor([1.0, 2000, 30000]), torch.tensor([-1.0, -2, -3]))

tensor([100.,  -2.,  -3.])

## hypot
hypot是“hypotenuse”的缩写，意思是直角三角形斜边的长度。

$$\text{out}_i=\sqrt{\text{input}_i^2+\text{other}_i^2}$$

**定义**：  
torch.hypot(input, other, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the first input tensor  第一个输入张量

- other (Tensor) – the second input tensor  第二个输入张量

- out (Tensor, optional) – the output tensor.  输出张量


In [41]:
import torch
torch.hypot(torch.tensor([4.0]), torch.tensor([3.0, 4.0, 5.0]))

tensor([5.0000, 5.6569, 6.4031])

## mul/multiply

$$\text{out}_i=\operatorname{input}_i\times\operatorname{other}_i$$

**定义**：  
torch.mul(input, other, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the first input tensor  第一个输入张量

- other (Tensor) – the second input tensor  第二个输入张量

- out (Tensor, optional) – the output tensor.  输出张量


In [42]:
import torch
a = torch.randn(3)
a
torch.mul(a, 100)

b = torch.randn(4, 1)
b
c = torch.randn(1, 4)
c
torch.mul(b, c)

tensor([[-0.3786, -0.4678,  0.3203, -0.0144],
        [-0.1728, -0.2135,  0.1462, -0.0066],
        [ 0.4906,  0.6061, -0.4150,  0.0187],
        [-0.9309, -1.1501,  0.7874, -0.0355]])

## nan_to_num

**定义**：  
torch.nan_to_num(input, nan=0.0, posinf=None, neginf=None, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- nan (Number, optional) – the value to replace NaNs with. Default is zero.  要替换的nan的值。默认值为0。

- posinf (Number, optional) – if a Number, the value to replace positive infinity values with. If None, positive infinity values are replaced with the greatest finite value representable by input’s dtype. Default is None.  如果是Number，则用该值替换正无穷大值。

- neginf (Number, optional) – if a Number, the value to replace negative infinity values with. If None, negative infinity values are replaced with the lowest finite value representable by input’s dtype. Default is None.  如果是Number，则用该值替换负无穷大值。

- out (Tensor, optional) – the output tensor.  输出张量


In [44]:
import torch
x = torch.tensor([float('nan'), float('inf'), -float('inf'), 3.14])
print(torch.nan_to_num(x))
print(torch.nan_to_num(x, nan=2.0))
print(torch.nan_to_num(x, nan=2.0, posinf=1.0))

tensor([ 0.0000e+00,  3.4028e+38, -3.4028e+38,  3.1400e+00])
tensor([ 2.0000e+00,  3.4028e+38, -3.4028e+38,  3.1400e+00])
tensor([ 2.0000e+00,  1.0000e+00, -3.4028e+38,  3.1400e+00])


## neg/negative

使用torch.neg函数可以比使用乘以-1的方式更快速地实现元素取相反数的操作，这是因为torch.neg函数使用了底层的硬件加速库，能够充分利用现代计算机的SIMD（Single Instruction, Multiple Data）指令集来进行并行计算。而直接通过乘以-1实现元素取相反数的操作则需要在Python解释器中执行循环，速度相对较慢。

$$\text{out}=-1\times\text{input}$$

**定义**：  
torch.neg(input, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- out (Tensor, optional) – the output tensor.  输出张量


In [47]:
import torch
import time

# 生成一个包含1亿个元素的随机张量
x = torch.randn(100000000)

In [68]:
# 直接乘以-1实现元素取相反数
start_time = time.time()
for i in range(10):
    z = x * -1
print("multiply by -1 elapsed time: ", time.time() - start_time)

# 使用torch.neg函数实现元素取相反数
start_time = time.time()
for i in range(10):
    y = torch.neg(x)
print("torch.neg elapsed time: ", time.time() - start_time)

# 直接乘以-1实现元素取相反数
start_time = time.time()
for i in range(10):
    z = x * -1
print("multiply by -1 elapsed time: ", time.time() - start_time)

multiply by -1 elapsed time:  1.286275863647461
torch.neg elapsed time:  1.156123161315918
multiply by -1 elapsed time:  1.2272710800170898


## nextafter

torch.nextafter(input, other, *, out=None)是一个PyTorch中的数学函数，用于返回一个张量，在给定输入张量input的方向上，接近另一个张量other的浮点数。

**定义**：  
torch.nextafter(input, other, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the first input tensor  第一个输入张量

- other (Tensor) – the second input tensor  第二个输入张量

- out (Tensor, optional) – the output tensor.  输出张量


In [71]:
import torch
eps = torch.finfo(torch.float32).eps
print(eps)
torch.nextafter(torch.tensor([1.0, 2.0]), torch.tensor([2.0, 1.0]))# == torch.tensor([eps + 1, 2 - eps])


1.1920928955078125e-07


tensor([1.0000, 2.0000])

## pow
取输入中每个元素的指数幂，并将结果返回一个张量。

$$\text { out }_{i}=x_{i}^{\text {exponent }}$$

**定义**：  
torch.pow(input, exponent, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- exponent (float or tensor) – the exponent value  指数

- out (Tensor, optional) – the output tensor.  输出张量


In [3]:
import torch
exp = torch.arange(1., 5.)
a = torch.arange(1., 5.)
torch.pow(a, exp)

tensor([  1.,   4.,  27., 256.])

## rad2deg
从弧度角度转换为角度。

**定义**：  
torch.rad2deg(input, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- out (Tensor, optional) – the output tensor.  输出张量


In [4]:
import torch
a = torch.tensor([[3.142, -3.142], [6.283, -6.283], [1.570, -1.570]])
torch.rad2deg(a)

tensor([[ 180.0233, -180.0233],
        [ 359.9894, -359.9894],
        [  89.9544,  -89.9544]])

## real
返回张量实值的新张量

**定义**：  
torch.real(input) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- out (Tensor, optional) – the output tensor.  输出张量


In [6]:
import torch
x=torch.randn(4, dtype=torch.cfloat)
print(x)
x.real

tensor([-0.5457-0.3526j, -0.0999-1.4083j, -1.2670+0.4616j,  0.2325+0.0278j])


tensor([-0.5457, -0.0999, -1.2670,  0.2325])

## reciprocal
返回一个带有输入元素倒数的新张量

$$\text { out }_{i}=\frac{1}{\text { input }_{i}}$$

**定义**：  
torch.reciprocal(input, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- out (Tensor, optional) – the output tensor.  输出张量

In [14]:
import torch
a = torch.randn(4)
print(a)
torch.reciprocal(a)

tensor([-0.5763, -0.0010,  0.2238, -0.6988])


tensor([   -1.7352, -1047.4005,     4.4684,    -1.4311])

## remainder
剩余部分

torch.remainder(a, b) == a - a.div(b, rounding_mode="floor") * b

**定义**：  
torch.remainder(input, other, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- out (Tensor, optional) – the output tensor.  输出张量


In [19]:
import torch
a = torch.tensor([1,2,3])
b = torch.tensor([1.1,2,3])
torch.remainder(a, b) == a - a.div(b, rounding_mode="floor") * b


tensor([True, True, True])

## round
输入元素舍入到最接近的整数。

**定义**：  
torch.round(input, *, decimals=0, out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- decimals (int) – Number of decimal places to round to (default: 0). If decimals is negative, it specifies the number of positions to the left of the decimal point.  要四舍五入的小数位数(默认值:0)。如果decimals为负，则指定小数点左侧的位置数。

- out (Tensor, optional) – the output tensor.  输出张量


In [20]:
import torch
torch.round(torch.tensor((4.7, -2.3, 9.1, -7.7)))

# Values equidistant from two integers are rounded towards the
#   the nearest even value (zero is treated as even)
torch.round(torch.tensor([-0.5, 0.5, 1.5, 2.5]))

# A positive decimals argument rounds to the to that decimal place
torch.round(torch.tensor([0.1234567]), decimals=3)

# A negative decimals argument rounds to the left of the decimal
torch.round(torch.tensor([1200.1234567]), decimals=-3)

tensor([1000.])

## rsqrt
返回一个新的张量，它是输入的每个元素的平方根(square-root)的倒数。

$$\mathrm{out}_{i}={\frac{1}{\sqrt{\mathrm{input}_{i}}}}$$

**定义**：  
torch.rsqrt(input, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- out (Tensor, optional) – the output tensor.  输出张量


In [21]:
import torch
a = torch.randn(4)
print(a)
torch.rsqrt(a)

tensor([-0.1304,  1.1480,  1.3253, -0.2133])


tensor([   nan, 0.9333, 0.8687,    nan])

## sign

$$\mathrm{out}_{i}=\mathrm{sgn}(\mathrm{input}_{i})$$


**定义**：  
torch.sign(input, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- out (Tensor, optional) – the output tensor.  输出张量


In [23]:
import torch
a = torch.tensor([0.7, -1.2, 0., 2.3])
torch.sign(a)

tensor([ 1., -1.,  0.,  1.])

## signbit
测试输入的每个元素是否设置了符号位。

**定义**：  
torch.signbit(input, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- out (Tensor, optional) – the output tensor.  输出张量


In [28]:
import torch
a = torch.tensor([0.7, -1.2, 0., 2.3])
torch.signbit(a)
a = torch.tensor([-0.0, 0.0])
torch.signbit(a)

tensor([ True, False])

## sin
返回一个包含输入元素正弦值的新张量。


$$\mathrm{out}_{i}=\mathrm{sin}(\mathrm{input}_{i})$$

**定义**：  
torch.sin(input, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- out (Tensor, optional) – the output tensor.  输出张量


In [43]:
import torch
a = torch.randn(4)
a
torch.sin(a)

tensor([-0.5208,  0.6776,  0.8882, -0.0439])

## sinh

$$\mathrm{out}_{i}=\mathrm{sinh}(\mathrm{input}_{i})$$

**定义**：  
torch.sinh(input, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- out (Tensor, optional) – the output tensor.  输出张量


In [44]:
import torch
a = torch.randn(4)
a
torch.sinh(a)

tensor([-0.9483, -0.2341, -0.2973,  0.5988])

## sqrt

$$\mathrm{out}_{i}=\sqrt{\mathrm{input}_{i}}$$

**定义**：  
torch.sqrt(input, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- out (Tensor, optional) – the output tensor.  输出张量


In [45]:
import torch
a = torch.randn(4)
a
torch.sqrt(a)

tensor([1.1565, 0.4610,    nan, 0.9043])

## square

$$\mathrm{out}_{i}=\mathrm{input}_{i}^2$$

**定义**：  
torch.square(input, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- out (Tensor, optional) – the output tensor.  输出张量


In [46]:
import torch
a = torch.randn(4)
a
torch.square(a)

tensor([0.8419, 0.1745, 0.8047, 0.2729])

## sub/subtract

$$\mathrm{out}_{i}=\mathrm{input}_{i}-\mathrm{alpha}\times\mathrm{other}_{i}$$

**定义**：  
torch.sub(input, other, *, alpha=1, out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- other (Tensor or Number) – the tensor or number to subtract from input.  从输入中减去的张量或数字

- alpha (Number) – the multiplier for other.  乘数

- out (Tensor, optional) – the output tensor.  输出张量


In [47]:
import torch
a = torch.tensor((1, 2))
b = torch.tensor((0, 1))
torch.sub(a, b, alpha=2)

tensor([1, 0])

## tan
返回一个带有输入元素正切值的新张量。

$$\mathrm{out}_{i}=\tan{(\mathrm{input}_{i})}$$


**定义**：  
torch.tan(input, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- out (Tensor, optional) – the output tensor.  输出张量


In [48]:
import torch
a = torch.randn(4)
a
torch.tan(a)

tensor([-2.9891e-03, -9.0448e-01, -1.2860e-01,  4.1826e+00])

## tanh
返回一个带有输入元素的双曲正切的新张量。

$$\mathrm{out}_{i}=\tanh{(\mathrm{input}_{i})}$$


**定义**：  
torch.tanh(input, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- out (Tensor, optional) – the output tensor.  输出张量


In [ ]:
import torch
a = torch.randn(4)
a
torch.tanh(a)

tensor([-2.9891e-03, -9.0448e-01, -1.2860e-01,  4.1826e+00])

## trunc
返回一个新的张量，包含输入元素的截断整数值。

**定义**：  
torch.trunc(input, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- out (Tensor, optional) – the output tensor.  输出张量


In [ ]:
import torch


## xx

$$xxxx$$

**定义**：  


**参数**：  
- input (Tensor) – the input tensor.  输入张量

- out (Tensor, optional) – the output tensor.  输出张量


In [ ]:
import torch


## xx

$$xxxx$$

**定义**：  


**参数**：  
- input (Tensor) – the input tensor.  输入张量

- out (Tensor, optional) – the output tensor.  输出张量


In [ ]:
import torch


## xx

$$xxxx$$

**定义**：  


**参数**：  
- input (Tensor) – the input tensor.  输入张量

- out (Tensor, optional) – the output tensor.  输出张量


In [ ]:
import torch


## xx

$$xxxx$$

**定义**：  


**参数**：  
- input (Tensor) – the input tensor.  输入张量

- out (Tensor, optional) – the output tensor.  输出张量


In [ ]:
import torch


## xx

$$xxxx$$

**定义**：  


**参数**：  
- input (Tensor) – the input tensor.  输入张量

- out (Tensor, optional) – the output tensor.  输出张量


In [ ]:
import torch
