[![](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/itmorn/AI.handbook/blob/main/DL/torch/nn/MathOperations/MathOperations.ipynb)

# 按元素操作(Pointwise Ops)

## abs/absolute
计算输入中每个元素的绝对值。
$$\text{out}_i=|\text{input}_i|$$

**定义**：  
torch.abs(input, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- out (Tensor, optional) – the output tensor.  输出张量

In [1]:
import torch

torch.abs(torch.tensor([-1, -2, 3]))

tensor([1, 2, 3])

## acos/arccos
计算输入中每个元素的逆余弦。

$$\text{out}_i=\cos^{-1}(\operatorname{input}_i)$$

**定义**：  
torch.acos(input, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- out (Tensor, optional) – the output tensor.  输出张量

In [7]:
import torch
a = torch.randn(4)
print(a)
torch.acos(a)

tensor([-0.3200,  0.1387, -3.0484, -0.4391])


tensor([1.8965, 1.4316,    nan, 2.0254])

## acosh/arccosh
返回输入元素的反双曲余弦的新张量。
$$\text{out}_i=\cosh^{-1}(\operatorname{input}_i)$$

**定义**：  
torch.acosh(input, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- out (Tensor, optional) – the output tensor.  输出张量

In [9]:
import torch
a = torch.randn(4).uniform_(1, 2)
a
torch.acosh(a)

tensor([0.7808, 1.1149, 0.9426, 1.2994])

## add

$$\text{out}_i=\text{input}_i+\text{alpha}\times\text{other}_i$$

**定义**：  
torch.add(input, other, *, alpha=1, out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- other (Tensor or Number) – the tensor or number to add to input.  要添加到输入中的张量或数字

- alpha (Number) – the multiplier for other.  other的乘数

- out (Tensor, optional) – the output tensor.  输出张量

In [15]:
import torch
a = torch.arange(10)
print(a)
torch.add(input=a, other=100)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


tensor([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [16]:
import torch
a = torch.arange(10)
b = torch.ones_like(a)
torch.add(input=a, other=b, alpha=100)

tensor([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

## addcdiv
执行tensor1与tensor2的逐元素除法，将结果乘以标量值并将其添加到输入中。

$$\text{out}_i=\text{input}_i+\text{value}\times\dfrac{\text{tensor}1_i}{\text{tensor}2_i}$$

**定义**：  
torch.addcdiv(input, tensor1, tensor2, *, value=1, out=None) → Tensor

**参数**：  
- input (Tensor) – the tensor to be added  要加的张量

- tensor1 (Tensor) – the numerator tensor  分子张量

- tensor2 (Tensor) – the denominator tensor  分母张量

- value (Number, optional) – multiplier for tensor1 / tensor2.   tensor1 / tensor2的乘子

- out (Tensor, optional) – the output tensor.  输出张量。

In [20]:
import torch
t = torch.randn(1, 3)
t1 = torch.randn(3, 1)
t2 = torch.randn(1, 3)
torch.addcdiv(t, t1, t2, value=0.1)

tensor([[1.7674, 1.3758, 0.6647],
        [1.2805, 1.1478, 0.7561],
        [0.7085, 0.8800, 0.8634]])

## addcmul
执行tensor1与tensor2的元素乘法，将结果乘以标量值并将其添加到输入中。
$$\text{out}_i=\mathrm{input}_i+\mathrm{value}\times\mathrm{tensor1}_i\times\mathrm{tensor2}_i$$

**定义**：  
torch.addcmul(input, tensor1, tensor2, *, value=1, out=None) → Tensor

**参数**：  
- input (Tensor) – the tensor to be added   要加的张量

- tensor1 (Tensor) – the tensor to be multiplied  要乘的张量

- tensor2 (Tensor) – the tensor to be multiplied  要乘的张量

- value (Number, optional) – multiplier for tensor1∗tensor2.  tensor1∗tensor2的乘子

- out (Tensor, optional) – the output tensor.  输出张量。

In [24]:
import torch
t = torch.randn(1, 3)
t1 = torch.randn(3, 1)
t2 = torch.randn(1, 3)
torch.addcmul(t, t1, t2, value=0.1)

tensor([[-1.5827, -0.7309,  2.5973],
        [-1.6367, -0.8269,  2.6584],
        [-1.6840, -0.9110,  2.7119]])

## angle
计算给定输入张量的元素角度(弧度)。
$$\text{out}_i=angle(\operatorname{input}_i)$$

**定义**：  
torch.angle(input, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- out (Tensor, optional) – the output tensor.  输出张量

In [25]:
import torch
torch.angle(torch.tensor([-1 + 1j, -2 + 2j, 3 - 3j]))*180/3.14159

tensor([135.0001, 135.0001, -45.0000])

## asin/arcsin
返回一个带有输入元素arcsin的新张量。

$$\text{out}_i=\sin^{-1}(\operatorname{input}_i)$$

**定义**：  
torch.asin(input, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- out (Tensor, optional) – the output tensor.  输出张量

In [27]:
import torch
a = torch.randn(4)
torch.asin(a)

tensor([   nan, 0.2574, 0.8200, 0.9444])

## asinh/arcsinh

$$\text{out}_i=\sinh^{-1}(\operatorname{input}_i)$$

**定义**：  
torch.asinh(input, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- out (Tensor, optional) – the output tensor.  输出张量

In [28]:
import torch
a = torch.randn(4)
a
torch.asinh(a)

tensor([-0.1693,  1.0191, -0.1025, -0.0610])

## atan/arctan


返回一个带有输入元素arctan值的新张量。

$$\text{out}_i=\tan^{-1}(\operatorname{input}_i)$$

**定义**：  
torch.atan(input, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- out (Tensor, optional) – the output tensor.  输出张量

In [29]:
import torch
a = torch.randn(4)
a
torch.atan(a)

tensor([ 0.7518, -0.7453, -0.4551,  0.6872])

## atanh/arctanh
返回输入元素的反双曲正切的新张量。

$$\text{out}_i=\tanh^{-1}(\text{input}_i)$$

**定义**：  
torch.atanh(input, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- out (Tensor, optional) – the output tensor.  输出张量

In [30]:
import torch
a = torch.randn(4).uniform_(-1, 1)
a
torch.atanh(a)

tensor([-0.0184, -0.6261, -1.1195, -0.7628])

## atan2/arctan2

$$\operatorname{atan2}(y,x)=\begin{cases}\arctan(\frac yx)&\text{if }x>0,\\ \arctan(\frac yx)+\pi&\text{if }x<0\text{ and }y\ge0,\\\arctan(\frac yx)-\pi&\text{if }{x<0}\text{ and }y<0,\\ +\frac\pi2&\text{if }x=0\text{ and }y>0,\\ -\frac\pi2&\operatorname{if }x=0\operatorname{ and }{y<0},\\ \operatorname{undefined}&\text{if }{x=0}\text{ and }y=0.\end{cases}$$

https://stackoverflow.com/questions/35749246/python-atan-or-atan2-what-should-i-use

**定义**：  
torch.atan2(input, other, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the first input tensor  第一个输入张量

- other (Tensor) – the second input tensor  第二个输入张量

- out (Tensor, optional) – the output tensor.  输出张量

In [31]:
import torch
a = torch.randn(4)
a
torch.atan2(a, torch.randn(4))

tensor([-2.7770, -0.7276, -0.1640,  2.9073])

## bitwise_not/logical_not

计算给定输入张量的位NOT。输入张量必须为整型或布尔型。对于bool张量，它计算逻辑NOT。

**定义**：  
torch.bitwise_not(input, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- out (Tensor, optional) – the output tensor.  输出张量


In [47]:
import torch
torch.bitwise_not(torch.tensor([0, 1, 2], dtype=torch.uint8))
# 0000 0000 -> 1111 1111
# 0000 0001 -> 1111 1110
# 0000 0010 -> 1111 1101 

tensor([255, 254, 253], dtype=torch.uint8)

## bitwise_and/logical_and

计算输入和其他的位与。输入张量必须为整型或布尔型。对于bool张量，它计算逻辑与。

**定义**：  
torch.bitwise_and(input, other, *, out=None) → Tensor

**参数**：  
- input – the first input tensor  第一个输入张量

- other – the second input tensor  第二个输入张量

- out (Tensor, optional) – the output tensor.  输出张量


In [48]:
import torch
torch.bitwise_and(torch.tensor([-1, -2, 3], dtype=torch.int8),
                  torch.tensor([1, 0, 3], dtype=torch.int8))
torch.bitwise_and(torch.tensor([True, True, False]),
                  torch.tensor([False, True, False]))


tensor([False,  True, False])

## bitwise_or/logical_or

计算输入和其他的位或。输入张量必须为整型或布尔型。对于bool张量，它计算逻辑或。

**定义**：  
torch.bitwise_or(input, other, *, out=None) → Tensor

**参数**：  
- input – the first input tensor  第一个输入张量

- other – the second input tensor  第二个输入张量

- out (Tensor, optional) – the output tensor.  输出张量


In [49]:
import torch
torch.bitwise_or(torch.tensor([-1, -2, 3], dtype=torch.int8),
                  torch.tensor([1, 0, 3], dtype=torch.int8))
torch.bitwise_or(torch.tensor([True, True, False]),
                  torch.tensor([False, True, False]))


tensor([ True,  True, False])

## bitwise_xor/logical_xor

计算输入和其他的位异或。输入张量必须为整型或布尔型。对于bool张量，它计算逻辑异或。

**定义**：  
torch.bitwise_xor(input, other, *, out=None) → Tensor

**参数**：  
- input – the first input tensor  第一个输入张量

- other – the second input tensor  第二个输入张量

- out (Tensor, optional) – the output tensor.  输出张量


In [50]:
import torch
torch.bitwise_xor(torch.tensor([-1, -2, 3], dtype=torch.int8),
                  torch.tensor([1, 0, 3], dtype=torch.int8))
torch.bitwise_xor(torch.tensor([True, True, False]),
                  torch.tensor([False, True, False]))


tensor([ True, False, False])

## bitwise_left_shift
计算输入的左算术移位。输入张量必须是整型的。
$$\text{out}_i=\text{input}_i<<\text{other}_i$$

**定义**：  
torch.bitwise_left_shift(input, other, *, out=None) → Tensor

**参数**：  
- input – the first input tensor  第一个输入张量

- other – the second input tensor  第二个输入张量

- out (Tensor, optional) – the output tensor.  输出张量


In [51]:
import torch
print(3<<3)
torch.bitwise_left_shift(torch.tensor([-1, -2, 3], dtype=torch.int8),
                         torch.tensor([1, 0, 3], dtype=torch.int8))


tensor([-2, -2, 24], dtype=torch.int8)

## bitwise_right_shift
计算输入的右算术移位。输入张量必须是整型的。
$$\text{out}_i=\text{input}_i>>\text{other}_i$$

**定义**：  
torch.bitwise_right_shift(input, other, *, out=None) → Tensor

**参数**：  
- input – the first input tensor  第一个输入张量

- other – the second input tensor  第二个输入张量

- out (Tensor, optional) – the output tensor.  输出张量


In [55]:
import torch
print(31 >> 3)
torch.bitwise_right_shift(torch.tensor([-2, -7, 31], dtype=torch.int8),
                          torch.tensor([1, 0, 3], dtype=torch.int8))

3


tensor([-1, -7,  3], dtype=torch.int8)

## ceil
向上取整

$$\text{out}_i=\lceil\operatorname{input}_i\rceil$$

**定义**：  
torch.ceil(input, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- out (Tensor, optional) – the output tensor.  输出张量


In [57]:
import torch
a = torch.randn(4)
print(a)
torch.ceil(a)

tensor([-0.3689, -0.0410,  1.4594, -1.5169])


tensor([-0., -0.,  2., -1.])

## clamp/clip
夹住.  
将输入的所有元素固定在[min, max]范围内

$$y_i=\min(\max(x_i,\min\text{value}_i),\max\text{value}_i)$$

**定义**：  
torch.clamp(input, min=None, max=None, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- min (Number or Tensor, optional) – lower-bound of the range to be clamped to  要夹紧的范围的下限

- max (Number or Tensor, optional) – upper-bound of the range to be clamped to  要夹紧的范围的上限

- out (Tensor, optional) – the output tensor.  输出张量


In [1]:
import torch
a = torch.randn(4)
print(a)
print(torch.clamp(a, min=-0.5, max=0.5))

min = torch.linspace(-1, 1, steps=4)
print(min)
torch.clamp(a, min=min)

tensor([-0.2149,  0.7258,  0.5111, -2.4046])
tensor([-0.2149,  0.5000,  0.5000, -0.5000])
tensor([-1.0000, -0.3333,  0.3333,  1.0000])


tensor([-0.2149,  0.7258,  0.5111,  1.0000])

## conj_physical
计算给定输入张量的元素共轭。

$$\text{out}_i=conj(\text{input}_i)$$

**定义**：  
torch.conj_physical(input, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- out (Tensor, optional) – the output tensor.  输出张量


In [2]:
import torch
torch.conj_physical(torch.tensor([-1 + 1j, -2 + 2j, 3 - 3j]))

tensor([-1.-1.j, -2.-2.j,  3.+3.j])

## copysign
用input的大小和other的符号创建一个新的浮点张量。
$$\operatorname{out}_i=\begin{cases}-|\operatorname{input}_i|&\text{if other}_i\leq-0.0\\ |\operatorname{imput}_i|&\text{if other}_i\geq0.0\end{cases}$$

**定义**：  
torch.copysign(input, other, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- out (Tensor, optional) – the output tensor.  输出张量


In [4]:
import torch
a = torch.randn(4)
print(a)
b = torch.randn(4)
print(b)

torch.copysign(a, b)

tensor([-0.2094, -0.7962,  0.0462,  0.0176])
tensor([-0.3092, -0.5713,  0.0554, -0.6485])


tensor([-0.2094, -0.7962,  0.0462, -0.0176])

## cos

$$\text{out}_i=\cos(\text{input}_i)$$

**定义**：  
torch.cos(input, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- out (Tensor, optional) – the output tensor.  输出张量


In [7]:
import torch
a = torch.randn(4)
torch.cos(a)

tensor([ 0.9805, -0.2416,  0.9493,  0.9866])

## cosh
返回一个包含输入元素的双曲余弦的新张量。

$$\text{out}_i=\cosh(\operatorname{input}_i)$$

**定义**：  
torch.cosh(input, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- out (Tensor, optional) – the output tensor.  输出张量


In [8]:
import torch
a = torch.randn(4)
torch.cosh(a)

tensor([1.0995, 1.3152, 1.9244, 1.8898])

## deg2rad
返回一个新的张量，其中输入的每个元素都从角度转换为弧度。

**定义**：  
torch.deg2rad(input, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- out (Tensor, optional) – the output tensor.  输出张量


In [9]:
import torch
a = torch.tensor([[180.0, -180.0], [360.0, -360.0], [90.0, -90.0]])
torch.deg2rad(a)

tensor([[ 3.1416, -3.1416],
        [ 6.2832, -6.2832],
        [ 1.5708, -1.5708]])

## div/divide/true_divide
将输入输入的每个元素除以其他输入的相应元素。

true_divide和 torch.div() with rounding_mode=None一致.

$$\text{out}_i=\dfrac{\text{input}_i}{\text{other}_i}$$

**定义**：  
torch.div(input, other, *, rounding_mode=None, out=None) → Tensor

**参数**：  
- input (Tensor) – the dividend 被除数

- other (Tensor or Number) – the divisor 除数

- out (Tensor, optional) – the output tensor.  输出张量

- rounding_mode (str, optional) – None、trunc、floor 

In [10]:
import torch
x = torch.tensor([ 0.3810,  1.2774, -0.2972, -0.3719,  0.4637])
print(torch.div(x, 0.5))

a = torch.tensor([[-0.3711, -1.9353, -0.4605, -0.2917],
                  [ 0.1815, -1.0111,  0.9805, -1.5923],
                  [ 0.1062,  1.4581,  0.7759, -1.2344],
                  [-0.1830, -0.0313,  1.1908, -1.4757]])
b = torch.tensor([ 0.8032,  0.2930, -0.8113, -0.2308])
print(torch.div(a, b))

print(torch.div(a, b, rounding_mode='trunc'))

print(torch.div(a, b, rounding_mode='floor'))

tensor([ 0.7620,  2.5548, -0.5944, -0.7438,  0.9274])
tensor([[-0.4620, -6.6051,  0.5676,  1.2639],
        [ 0.2260, -3.4509, -1.2086,  6.8990],
        [ 0.1322,  4.9764, -0.9564,  5.3484],
        [-0.2278, -0.1068, -1.4678,  6.3938]])
tensor([[-0., -6.,  0.,  1.],
        [ 0., -3., -1.,  6.],
        [ 0.,  4., -0.,  5.],
        [-0., -0., -1.,  6.]])
tensor([[-1., -7.,  0.,  1.],
        [ 0., -4., -2.,  6.],
        [ 0.,  4., -1.,  5.],
        [-1., -1., -2.,  6.]])


## exp

$$y_i=e^{x_i}$$

**定义**：  
torch.exp(input, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- out (Tensor, optional) – the output tensor.  输出张量


In [11]:
import torch
import math

torch.exp(torch.tensor([0, math.log(2.)]))

tensor([1., 2.])

## trunc/fix

返回一个新的张量，包含输入元素的截断整数值。

**定义**：  
torch.trunc(input, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- out (Tensor, optional) – the output tensor.  输出张量


In [13]:
import torch
a = torch.randn(4)
print(a)
torch.trunc(a)

tensor([ 1.0509, -1.0209, -0.1938, -0.1570])


tensor([ 1., -1., -0., -0.])

## float_power
提高输入的指数次幂

**定义**：  
torch.float_power(input, exponent, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- exponent (Tensor or Number) – the exponent value(s)  指数值

- out (Tensor, optional) – the output tensor.  输出张量


In [14]:
import torch
a = torch.arange(1, 5)
print(a)
exp = torch.tensor([2, -3, 4, -5])
torch.float_power(a, exp)

tensor([1, 2, 3, 4])


tensor([1.0000e+00, 1.2500e-01, 8.1000e+01, 9.7656e-04], dtype=torch.float64)

## floor

$$\text{out}_i=\lfloor\operatorname{input}_i\rfloor$$

**定义**：  
torch.floor(input, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- out (Tensor, optional) – the output tensor.  输出张量


In [15]:
import torch
a = torch.randn(4)
print(a)
torch.floor(a)

tensor([ 1.2759,  1.7243, -1.9898,  0.4412])


tensor([ 1.,  1., -2.,  0.])

## floor_divide

$$\text{out}_i=\text{floor}\left(\dfrac{\text{input}_i}{\text{other}_i}\right)$$

**定义**：  
torch.floor_divide(input, other, *, out=None) → Tensor

**参数**：  
- input (Tensor or Number) – the dividend 被除数

- other (Tensor or Number) – the divisor  除数

- out (Tensor, optional) – the output tensor.  输出张量


In [18]:
import torch
a = torch.tensor([4.0, 3.0])
b = torch.tensor([2.0, 2.0])
print(torch.floor_divide(a, b))
print(torch.floor_divide(a, 1.4))

tensor([2., 1.])
tensor([2., 2.])


## frac

计算输入中每个元素的小数部分。

$$\text{out}_i=\text{input}_i-\lfloor|\text{input}_i|\rfloor*\text{sgn}(\text{input}_i)$$

**定义**：  
torch.frac(input, *, out=None) → Tensor

In [19]:
import torch
torch.frac(torch.tensor([1, 2.5, -3.2]))

tensor([ 0.0000,  0.5000, -0.2000])

## frexp
将输入分解为尾数和指数张量

$$\mathrm{input}=\mathrm{mantissa}\times2^{\mathrm{exponent}}.$$

**定义**：  
torch.frexp(input, *, out=None) -> (Tensor mantissa, Tensor exponent)

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- out (Tensor, optional) – the output tensor.  输出张量


In [20]:
import torch
x = torch.arange(9.)
mantissa, exponent = torch.frexp(x)
print(mantissa)
print(exponent)

tensor([0.0000, 0.5000, 0.5000, 0.7500, 0.5000, 0.6250, 0.7500, 0.8750, 0.5000])
tensor([0, 1, 2, 2, 3, 3, 3, 3, 4], dtype=torch.int32)


## ldexp

$$\text{out}_i=\operatorname{input}_i*2_i^{\operatorname{other}}$$

**定义**：  
torch.ldexp(input, other, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- other (Tensor) – a tensor of exponents, typically integers.  一个指数张量，通常是整数。

- out (Tensor, optional) – the output tensor.  输出张量


In [25]:
import torch
# torch.ldexp(torch.tensor([1.]), torch.tensor([1]))
torch.ldexp(torch.tensor([1.0]), torch.tensor([1, 2, 3, 4]))

tensor([ 2.,  4.,  8., 16.])

## lerp
torch.lerp的全称是“torch linear interpolation”，它是PyTorch中的一个函数，用于对两个张量进行线性插值。

$$\text{out}_i=\text{start}_i+\text{weight}_i\times(\text{end}_i-\text{start}_i)$$

**定义**：  
torch.lerp(input, end, weight, *, out=None)

**参数**：  
- input (Tensor) – the tensor with the starting points  起始点的张量

- end (Tensor) – the tensor with the ending points  带有端点的张量

- weight (float or tensor) – the weight for the interpolation formula  插值公式的权重

- out (Tensor, optional) – the output tensor.  输出张量


In [26]:
import torch
start = torch.arange(1., 5.)
end = torch.empty(4).fill_(10)
print(start)
print(end)
torch.lerp(start, end, 0.5)
# torch.lerp(start, end, torch.full_like(start, 0.5))

tensor([1., 2., 3., 4.])
tensor([10., 10., 10., 10.])


tensor([5.5000, 6.0000, 6.5000, 7.0000])

## lgamma

$$\operatorname{out}_i=\ln\Gamma(|\operatorname{input}_i|)$$

**定义**：  
torch.lgamma(input, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- out (Tensor, optional) – the output tensor.  输出张量


In [27]:
import torch
a = torch.arange(0.5, 2, 0.5)
torch.lgamma(a)

tensor([ 0.5724,  0.0000, -0.1208])

## log

$$y_i=\log_e(x_i)$$

**定义**：  
torch.log(input, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- out (Tensor, optional) – the output tensor.  输出张量


In [32]:
import torch
a = torch.arange(5)
print(torch.log(a))

tensor([  -inf, 0.0000, 0.6931, 1.0986, 1.3863])


## log10

$$y_i=\log_{10}(x_i)$$

**定义**：  
torch.log10(input, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- out (Tensor, optional) – the output tensor.  输出张量

In [33]:
import torch
a = torch.arange(5)
print(torch.log10(a))

tensor([  -inf, 0.0000, 0.3010, 0.4771, 0.6021])


## log2

$$y_i=\log_2(x_i)$$

**定义**：  
torch.log2(input, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- out (Tensor, optional) – the output tensor.  输出张量

In [34]:
import torch
a = torch.arange(5)
print(torch.log2(a))

tensor([  -inf, 0.0000, 1.0000, 1.5850, 2.0000])


## logaddexp

$$\log\left(e^x+e^y\right)$$

**定义**：  
torch.logaddexp(input, other, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- other (Tensor) – the second input tensor  第二个输入张量

- out (Tensor, optional) – the output tensor.  输出张量


In [38]:
import torch
torch.logaddexp(torch.tensor([-1.0]), torch.tensor([-1.0, -2, -3]))
torch.logaddexp(torch.tensor([100.0, -200, -300]), torch.tensor([-1.0, -2, -3]))
# torch.logaddexp(torch.tensor([1.0, 2000, 30000]), torch.tensor([-1.0, -2, -3]))

tensor([100.,  -2.,  -3.])

## logaddexp2

$$\log\left(2^x+2^y\right)$$

**定义**：  
torch.logaddexp2(input, other, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- other (Tensor) – the second input tensor  第二个输入张量

- out (Tensor, optional) – the output tensor.  输出张量


In [39]:
import torch
torch.logaddexp2(torch.tensor([-1.0]), torch.tensor([-1.0, -2, -3]))
torch.logaddexp2(torch.tensor([100.0, -200, -300]), torch.tensor([-1.0, -2, -3]))
# torch.logaddexp(torch.tensor([1.0, 2000, 30000]), torch.tensor([-1.0, -2, -3]))

tensor([100.,  -2.,  -3.])

## hypot
hypot是“hypotenuse”的缩写，意思是直角三角形斜边的长度。

$$\text{out}_i=\sqrt{\text{input}_i^2+\text{other}_i^2}$$

**定义**：  
torch.hypot(input, other, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the first input tensor  第一个输入张量

- other (Tensor) – the second input tensor  第二个输入张量

- out (Tensor, optional) – the output tensor.  输出张量


In [41]:
import torch
torch.hypot(torch.tensor([4.0]), torch.tensor([3.0, 4.0, 5.0]))

tensor([5.0000, 5.6569, 6.4031])

## mul/multiply

$$\text{out}_i=\operatorname{input}_i\times\operatorname{other}_i$$

**定义**：  
torch.mul(input, other, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the first input tensor  第一个输入张量

- other (Tensor) – the second input tensor  第二个输入张量

- out (Tensor, optional) – the output tensor.  输出张量


In [42]:
import torch
a = torch.randn(3)
a
torch.mul(a, 100)

b = torch.randn(4, 1)
b
c = torch.randn(1, 4)
c
torch.mul(b, c)

tensor([[-0.3786, -0.4678,  0.3203, -0.0144],
        [-0.1728, -0.2135,  0.1462, -0.0066],
        [ 0.4906,  0.6061, -0.4150,  0.0187],
        [-0.9309, -1.1501,  0.7874, -0.0355]])

## nan_to_num

**定义**：  
torch.nan_to_num(input, nan=0.0, posinf=None, neginf=None, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- nan (Number, optional) – the value to replace NaNs with. Default is zero.  要替换的nan的值。默认值为0。

- posinf (Number, optional) – if a Number, the value to replace positive infinity values with. If None, positive infinity values are replaced with the greatest finite value representable by input’s dtype. Default is None.  如果是Number，则用该值替换正无穷大值。

- neginf (Number, optional) – if a Number, the value to replace negative infinity values with. If None, negative infinity values are replaced with the lowest finite value representable by input’s dtype. Default is None.  如果是Number，则用该值替换负无穷大值。

- out (Tensor, optional) – the output tensor.  输出张量


In [44]:
import torch
x = torch.tensor([float('nan'), float('inf'), -float('inf'), 3.14])
print(torch.nan_to_num(x))
print(torch.nan_to_num(x, nan=2.0))
print(torch.nan_to_num(x, nan=2.0, posinf=1.0))

tensor([ 0.0000e+00,  3.4028e+38, -3.4028e+38,  3.1400e+00])
tensor([ 2.0000e+00,  3.4028e+38, -3.4028e+38,  3.1400e+00])
tensor([ 2.0000e+00,  1.0000e+00, -3.4028e+38,  3.1400e+00])


## neg/negative

使用torch.neg函数可以比使用乘以-1的方式更快速地实现元素取相反数的操作，这是因为torch.neg函数使用了底层的硬件加速库，能够充分利用现代计算机的SIMD（Single Instruction, Multiple Data）指令集来进行并行计算。而直接通过乘以-1实现元素取相反数的操作则需要在Python解释器中执行循环，速度相对较慢。

$$\text{out}=-1\times\text{input}$$

**定义**：  
torch.neg(input, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- out (Tensor, optional) – the output tensor.  输出张量


In [47]:
import torch
import time

# 生成一个包含1亿个元素的随机张量
x = torch.randn(100000000)

In [68]:
# 直接乘以-1实现元素取相反数
start_time = time.time()
for i in range(10):
    z = x * -1
print("multiply by -1 elapsed time: ", time.time() - start_time)

# 使用torch.neg函数实现元素取相反数
start_time = time.time()
for i in range(10):
    y = torch.neg(x)
print("torch.neg elapsed time: ", time.time() - start_time)

# 直接乘以-1实现元素取相反数
start_time = time.time()
for i in range(10):
    z = x * -1
print("multiply by -1 elapsed time: ", time.time() - start_time)

multiply by -1 elapsed time:  1.286275863647461
torch.neg elapsed time:  1.156123161315918
multiply by -1 elapsed time:  1.2272710800170898


## nextafter

torch.nextafter(input, other, *, out=None)是一个PyTorch中的数学函数，用于返回一个张量，在给定输入张量input的方向上，接近另一个张量other的浮点数。

**定义**：  
torch.nextafter(input, other, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the first input tensor  第一个输入张量

- other (Tensor) – the second input tensor  第二个输入张量

- out (Tensor, optional) – the output tensor.  输出张量


In [71]:
import torch
eps = torch.finfo(torch.float32).eps
print(eps)
torch.nextafter(torch.tensor([1.0, 2.0]), torch.tensor([2.0, 1.0]))# == torch.tensor([eps + 1, 2 - eps])


1.1920928955078125e-07


tensor([1.0000, 2.0000])

## pow
取输入中每个元素的指数幂，并将结果返回一个张量。

$$\text { out }_{i}=x_{i}^{\text {exponent }}$$

**定义**：  
torch.pow(input, exponent, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- exponent (float or tensor) – the exponent value  指数

- out (Tensor, optional) – the output tensor.  输出张量


In [3]:
import torch
exp = torch.arange(1., 5.)
a = torch.arange(1., 5.)
torch.pow(a, exp)

tensor([  1.,   4.,  27., 256.])

## rad2deg
从弧度角度转换为角度。

**定义**：  
torch.rad2deg(input, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- out (Tensor, optional) – the output tensor.  输出张量


In [4]:
import torch
a = torch.tensor([[3.142, -3.142], [6.283, -6.283], [1.570, -1.570]])
torch.rad2deg(a)

tensor([[ 180.0233, -180.0233],
        [ 359.9894, -359.9894],
        [  89.9544,  -89.9544]])

## real
返回张量实值的新张量

**定义**：  
torch.real(input) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- out (Tensor, optional) – the output tensor.  输出张量


In [6]:
import torch
x=torch.randn(4, dtype=torch.cfloat)
print(x)
x.real

tensor([-0.5457-0.3526j, -0.0999-1.4083j, -1.2670+0.4616j,  0.2325+0.0278j])


tensor([-0.5457, -0.0999, -1.2670,  0.2325])

## reciprocal
返回一个带有输入元素倒数的新张量

$$\text { out }_{i}=\frac{1}{\text { input }_{i}}$$

**定义**：  
torch.reciprocal(input, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- out (Tensor, optional) – the output tensor.  输出张量

In [14]:
import torch
a = torch.randn(4)
print(a)
torch.reciprocal(a)

tensor([-0.5763, -0.0010,  0.2238, -0.6988])


tensor([   -1.7352, -1047.4005,     4.4684,    -1.4311])

## remainder
剩余部分

torch.remainder(a, b) == a - a.div(b, rounding_mode="floor") * b

**定义**：  
torch.remainder(input, other, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- out (Tensor, optional) – the output tensor.  输出张量


In [19]:
import torch
a = torch.tensor([1,2,3])
b = torch.tensor([1.1,2,3])
torch.remainder(a, b) == a - a.div(b, rounding_mode="floor") * b


tensor([True, True, True])

## round
输入元素舍入到最接近的整数。

**定义**：  
torch.round(input, *, decimals=0, out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- decimals (int) – Number of decimal places to round to (default: 0). If decimals is negative, it specifies the number of positions to the left of the decimal point.  要四舍五入的小数位数(默认值:0)。如果decimals为负，则指定小数点左侧的位置数。

- out (Tensor, optional) – the output tensor.  输出张量


In [20]:
import torch
torch.round(torch.tensor((4.7, -2.3, 9.1, -7.7)))

# Values equidistant from two integers are rounded towards the
#   the nearest even value (zero is treated as even)
torch.round(torch.tensor([-0.5, 0.5, 1.5, 2.5]))

# A positive decimals argument rounds to the to that decimal place
torch.round(torch.tensor([0.1234567]), decimals=3)

# A negative decimals argument rounds to the left of the decimal
torch.round(torch.tensor([1200.1234567]), decimals=-3)

tensor([1000.])

## rsqrt
返回一个新的张量，它是输入的每个元素的平方根(square-root)的倒数。

$$\mathrm{out}_{i}={\frac{1}{\sqrt{\mathrm{input}_{i}}}}$$

**定义**：  
torch.rsqrt(input, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- out (Tensor, optional) – the output tensor.  输出张量


In [21]:
import torch
a = torch.randn(4)
print(a)
torch.rsqrt(a)

tensor([-0.1304,  1.1480,  1.3253, -0.2133])


tensor([   nan, 0.9333, 0.8687,    nan])

## sign

$$\mathrm{out}_{i}=\mathrm{sgn}(\mathrm{input}_{i})$$


**定义**：  
torch.sign(input, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- out (Tensor, optional) – the output tensor.  输出张量


In [23]:
import torch
a = torch.tensor([0.7, -1.2, 0., 2.3])
torch.sign(a)

tensor([ 1., -1.,  0.,  1.])

## signbit
测试输入的每个元素是否设置了符号位。

**定义**：  
torch.signbit(input, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- out (Tensor, optional) – the output tensor.  输出张量


In [28]:
import torch
a = torch.tensor([0.7, -1.2, 0., 2.3])
torch.signbit(a)
a = torch.tensor([-0.0, 0.0])
torch.signbit(a)

tensor([ True, False])

## sin
返回一个包含输入元素正弦值的新张量。


$$\mathrm{out}_{i}=\mathrm{sin}(\mathrm{input}_{i})$$

**定义**：  
torch.sin(input, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- out (Tensor, optional) – the output tensor.  输出张量


In [43]:
import torch
a = torch.randn(4)
a
torch.sin(a)

tensor([-0.5208,  0.6776,  0.8882, -0.0439])

## sinh

$$\mathrm{out}_{i}=\mathrm{sinh}(\mathrm{input}_{i})$$

**定义**：  
torch.sinh(input, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- out (Tensor, optional) – the output tensor.  输出张量


In [44]:
import torch
a = torch.randn(4)
a
torch.sinh(a)

tensor([-0.9483, -0.2341, -0.2973,  0.5988])

## sqrt

$$\mathrm{out}_{i}=\sqrt{\mathrm{input}_{i}}$$

**定义**：  
torch.sqrt(input, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- out (Tensor, optional) – the output tensor.  输出张量


In [45]:
import torch
a = torch.randn(4)
a
torch.sqrt(a)

tensor([1.1565, 0.4610,    nan, 0.9043])

## square

$$\mathrm{out}_{i}=\mathrm{input}_{i}^2$$

**定义**：  
torch.square(input, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- out (Tensor, optional) – the output tensor.  输出张量


In [46]:
import torch
a = torch.randn(4)
a
torch.square(a)

tensor([0.8419, 0.1745, 0.8047, 0.2729])

## sub/subtract

$$\mathrm{out}_{i}=\mathrm{input}_{i}-\mathrm{alpha}\times\mathrm{other}_{i}$$

**定义**：  
torch.sub(input, other, *, alpha=1, out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- other (Tensor or Number) – the tensor or number to subtract from input.  从输入中减去的张量或数字

- alpha (Number) – the multiplier for other.  乘数

- out (Tensor, optional) – the output tensor.  输出张量


In [47]:
import torch
a = torch.tensor((1, 2))
b = torch.tensor((0, 1))
torch.sub(a, b, alpha=2)

tensor([1, 0])

## tan
返回一个带有输入元素正切值的新张量。

$$\mathrm{out}_{i}=\tan{(\mathrm{input}_{i})}$$


**定义**：  
torch.tan(input, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- out (Tensor, optional) – the output tensor.  输出张量


In [48]:
import torch
a = torch.randn(4)
a
torch.tan(a)

tensor([-2.9891e-03, -9.0448e-01, -1.2860e-01,  4.1826e+00])

## tanh
返回一个带有输入元素的双曲正切的新张量。

$$\mathrm{out}_{i}=\tanh{(\mathrm{input}_{i})}$$


**定义**：  
torch.tanh(input, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- out (Tensor, optional) – the output tensor.  输出张量


In [ ]:
import torch
a = torch.randn(4)
a
torch.tanh(a)

tensor([-2.9891e-03, -9.0448e-01, -1.2860e-01,  4.1826e+00])

## trunc
返回一个新的张量，包含输入元素的截断整数值。

**定义**：  
torch.trunc(input, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- out (Tensor, optional) – the output tensor.  输出张量


In [50]:
import torch
a = torch.randn(4)
a
torch.trunc(a)

tensor([ 2., -1., -0., -1.])

# 归约操作(Reduction Ops)

## argmax
返回输入张量中所有元素最大值的下标。

**定义**：  
torch.argmax(input) → LongTensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- dim (int) – the dimension to reduce. If None, the argmax of the flattened input is returned.  要缩减的维度。如果为None，则返回扁平输入的argmax。

- keepdim (bool) – whether the output tensor has dim retained or not. Ignored if dim=None.  输出张量是否保留dim。如果dim=None则忽略。

In [55]:
import torch
a = torch.randn(4, 4)
print(a)
torch.argmax(a)

tensor([[ 1.1409, -0.7183,  0.3690, -0.4920],
        [ 1.2581, -1.4586,  0.4036, -1.6532],
        [-0.5653, -1.8931, -0.4605, -1.4034],
        [-2.0344, -1.8739, -1.4650,  1.7580]])


tensor(15)

In [60]:
import torch
a = torch.randn(4, 5)
print(a)
torch.argmax(a, dim=1)

tensor([[-2.1566,  0.7073, -1.2339,  0.6396,  0.7272],
        [-0.4054, -0.8575,  0.6742,  0.3118,  0.2698],
        [ 0.4580, -1.6358, -0.6473, -1.4467,  0.8581],
        [ 0.1854,  1.0184, -0.2967,  0.0136,  0.8025]])


tensor([4, 2, 4, 1])

## argmin
返回输入张量中所有元素最小值的下标。

**定义**：  
torch.argmin(input) → LongTensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- dim (int) – the dimension to reduce. If None, the argmax of the flattened input is returned.  要缩减的维度。如果为None，则返回扁平输入的argmax。

- keepdim (bool) – whether the output tensor has dim retained or not. Ignored if dim=None.  输出张量是否保留dim。如果dim=None则忽略。

In [61]:
import torch
a = torch.randn(4, 4)
print(a)
torch.argmin(a)

tensor([[ 1.5267,  0.3005,  1.0553,  0.3932],
        [-0.9219,  0.2772,  1.1358, -0.2273],
        [ 1.4570, -0.4484, -2.3515,  0.4772],
        [-0.8745, -0.5868,  0.2526, -1.8395]])


tensor(10)

In [62]:
import torch
a = torch.randn(4, 5)
print(a)
torch.argmin(a, dim=1)

tensor([[ 1.2819,  0.7548,  0.4725, -0.1861,  0.5957],
        [ 0.6694,  2.1737, -0.6378,  0.7197,  0.3884],
        [-0.8662,  1.7931, -0.0273, -0.6162,  0.7632],
        [-0.0275,  0.2515, -0.1027, -0.9140, -1.6479]])


tensor([3, 2, 0, 4])

## amax
返回给定维度中输入张量的每个切片的最大值。

**定义**：  
torch.amax(input, dim, keepdim=False, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- dim (int) – the dimension to reduce. If None, the argmax of the flattened input is returned.  要缩减的维度。如果为None，则返回扁平输入的argmax。

- keepdim (bool) – whether the output tensor has dim retained or not. Ignored if dim=None.  输出张量是否保留dim。如果dim=None则忽略。

Amax /amin在相等的值之间均匀分布梯度，而max(dim)/min(dim)只将梯度传播到源张量中的单个索引。

In [67]:
import torch
a = torch.randn(4, 4)
print(a)
torch.amax(a, 1)

tensor([[ 0.0504,  1.9840,  0.8018, -1.2797],
        [ 1.0845,  0.7170, -0.0696, -1.2218],
        [ 0.9092,  0.2599,  1.5456, -1.1065],
        [-0.6432,  0.2562, -1.3550, -1.4312]])


tensor([1.9840, 1.0845, 1.5456, 0.2562])

## amin
返回给定维度中输入张量的每个切片的最大值。

**定义**：  
torch.amin(input, dim, keepdim=False, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- dim (int) – the dimension to reduce. If None, the argmax of the flattened input is returned.  要缩减的维度。如果为None，则返回扁平输入的argmax。

- keepdim (bool) – whether the output tensor has dim retained or not. Ignored if dim=None.  输出张量是否保留dim。如果dim=None则忽略。

Amax /amin在相等的值之间均匀分布梯度，而max(dim)/min(dim)只将梯度传播到源张量中的单个索引。

In [68]:
import torch
a = torch.randn(4, 4)
print(a)
torch.amin(a, 1)

tensor([[ 1.5521, -0.9138,  1.4119, -0.1798],
        [ 0.0393,  0.4365,  1.3324, -1.0595],
        [-0.5021,  0.2343,  0.7334, -0.6955],
        [-0.4820,  0.1076, -0.9012, -2.6091]])


tensor([-0.9138, -1.0595, -0.6955, -2.6091])

## aminmax

**定义**：  
torch.aminmax(input, *, dim=None, keepdim=False, out=None) -> (Tensor min, Tensor max)

**参数**：  
- dim (Optional[int]) – The dimension along which to compute the values. If None, computes the values over the entire input tensor. Default is None.  计算值的维度。如果为None，则计算整个输入张量的值。默认为None。

- keepdim (bool) – If True, the reduced dimensions will be kept in the output tensor as dimensions with size 1 for broadcasting, otherwise they will be removed, as if calling (torch.squeeze()). Default is False.  如果为True，减少的维度将在输出张量中保留为大小为1的维度用于广播，否则它们将被删除

- out (Optional[Tuple[Tensor, Tensor]]) – Optional tensors on which to write the result. Must have the same shape and dtype as the expected output. Default is None.  可选的可写入结果的张量。必须具有与预期输出相同的形状和dtype。默认为None。

In [75]:
import torch
torch.aminmax(torch.tensor([1, -3, 5]))

# aminmax propagates NaNs
# t = torch.aminmax(torch.tensor([1, -3, 5, torch.nan]))
# t
# torch.arange(10).view(2, 5)
# t.aminmax(dim=0, keepdim=True)

torch.return_types.aminmax(
min=tensor(-3),
max=tensor(5))

## all
测试输入中的所有元素是否都为True。

**定义**：  
torch.all(input) → Tensor

In [77]:
import torch
a = torch.rand(1, 2).bool()
a
torch.all(a)

a = torch.arange(0, 3)
a
torch.all(a)

tensor(False)

## any

测试输入中的存在元素的计算结果是否为True。

**定义**：  
torch.any(input) → Tensor

In [79]:
import torch
a = torch.rand(1, 2).bool()
a
torch.any(a)
a = torch.arange(0, 3)
a
torch.any(a)

tensor(True)

## max
返回输入张量中所有元素的最大值。

**定义**：  
torch.max(input) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- dim (int) – the dimension to reduce.  要缩减的维度

- keepdim (bool) – whether the output tensor has dim retained or not. Default: False.  输出张量是否保留dim

- out (tuple, optional) – the result tuple of two output tensors (max, max_indices)  两个输出张量的结果元组(max, max_indexes)

In [82]:
import torch
a = torch.randn(4, 4)
a
torch.max(a, 1)

torch.return_types.max(
values=tensor([1.4123, 0.3300, 1.9050, 2.7678]),
indices=tensor([2, 0, 2, 3]))

## min
返回输入张量中所有元素的最小值。

**定义**：  
torch.min(input) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- dim (int) – the dimension to reduce.  要缩减的维度

- keepdim (bool) – whether the output tensor has dim retained or not. Default: False.  输出张量是否保留dim

- out (tuple, optional) – the result tuple of two output tensors (max, max_indices)  两个输出张量的结果元组(max, max_indexes)

In [84]:
import torch
a = torch.randn(4, 4)
a
torch.min(a, 1)

torch.return_types.min(
values=tensor([-0.5533, -0.7688, -1.4919, -0.6106]),
indices=tensor([1, 2, 2, 0]))

## dist
返回input 和 other的距离。

**定义**：  
torch.dist(input, other, p=2) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- other (Tensor) – the Right-hand-side input tensor  输入张量

- p (float, optional) – the norm to be computed  要计算的范数

In [112]:
import torch
torch.manual_seed(666)
x = torch.randn(4)
print(x)
y = torch.randn(4)
print(y)
p=2
print(torch.dist(x, y, p))
print(((x-y)**p).abs().sum()**(1/p))

tensor([-2.1188,  0.0635, -1.4555, -0.0126])
tensor([-0.1548, -0.0927,  2.5916,  0.4542])
tensor(4.5253)
tensor(4.5253)


tensor(6.6340)

## logsumexp
返回给定维度dim中输入张量的每一行的指数和的对数。计算在数值上是稳定的。

$$\mathrm{logsumexp}(x)_{i}=\log\sum_{j}\exp(x_{i j})$$

**定义**：  
torch.logsumexp(input, dim, keepdim=False, *, out=None)

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- dim (int or tuple of ints, optional) – the dimension or dimensions to reduce. If None, all dimensions are reduced.  要缩减的维度。如果为None，则减少所有维度。

- keepdim (bool) – whether the output tensor has dim retained or not.  输出张量是否保留dim。

- out (Tensor, optional) – the output tensor.  输出张量。

In [118]:
import torch
torch.manual_seed(666)
a = torch.randn(3, 3)
print(torch.logsumexp(a, 1))
# torch.dist(torch.logsumexp(a, 1), torch.log(torch.sum(torch.exp(a), 1)))
print(torch.log(torch.sum(torch.exp(a), 1)))

tensor([0.3500, 1.0136, 2.7362])
tensor([0.3500, 1.0136, 2.7362])


## mean
返回输入张量中所有元素的平均值。

**定义**：  
torch.mean(input, *, dtype=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- dtype (torch.dtype, optional) – the desired data type of returned tensor. If specified, the input tensor is casted to dtype before the operation is performed. This is useful for preventing data type overflows. Default: None.  返回张量的期望数据类型


In [120]:
import torch
a = torch.randn(1, 3)
a
torch.mean(a)

tensor(0.1916)

## nanmean
计算所有非nan元素在指定维度上的平均值。

**定义**：  
torch.nanmean(input, dim=None, keepdim=False, *, dtype=None, out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- dim (int or tuple of ints, optional) – the dimension or dimensions to reduce. If None, all dimensions are reduced.  要缩减的维度

- keepdim (bool) – whether the output tensor has dim retained or not.  输出张量是否保留dim。

- dtype (torch.dtype, optional) – the desired data type of returned tensor. If specified, the input tensor is casted to dtype before the operation is performed. This is useful for preventing data type overflows. Default: None.  返回张量的期望数据类型

- out (Tensor, optional) – the output tensor.  输出张量。

In [122]:
import torch
x = torch.tensor([[torch.nan, 1, 2], [1, 2, 3]])
x.mean()
x.nanmean()
# x.mean(dim=0)
# x.nanmean(dim=0)

# torch.tensor([torch.nan]).nanmean()

tensor(1.8000)

## median
返回输入值的中位数。

**定义**：  
torch.median(input) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- dim (int) – the dimension to reduce.  要缩减的维度

- keepdim (bool) – whether the output tensor has dim retained or not.  输出张量是否保留dim

- out ((Tensor, Tensor), optional) – The first tensor will be populated with the median values and the second tensor, which must have dtype long, with their indices in the dimension dim of input.

In [124]:
import torch
a = torch.randn(1, 3)
print(a)
torch.median(a)

tensor([[ 0.0755,  0.7091, -1.0812]])


tensor(0.0755)

## nanmedian
返回输入值的中位数，忽略NaN值。

**定义**：  
torch.nanmedian(input) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- dim (int) – the dimension to reduce.  要缩减的维度

- keepdim (bool) – whether the output tensor has dim retained or not.  输出张量是否保留dim

- out ((Tensor, Tensor), optional) – The first tensor will be populated with the median values and the second tensor, which must have dtype long, with their indices in the dimension dim of input.

In [125]:
import torch
a = torch.tensor([[2, 3, 1], [float('nan'), 1, float('nan')]])
a
a.median(0)
a.nanmedian(0)

torch.return_types.nanmedian(
values=tensor([2., 1., 1.]),
indices=tensor([0, 1, 0]))

## mode
返回输入值的中位数，忽略NaN值。

**定义**：  
torch.mode(input, dim=- 1, keepdim=False, *, out=None)

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- dim (int) – the dimension to reduce.  要缩减的维度

- keepdim (bool) – whether the output tensor has dim retained or not.  输出张量是否保留dim

- out (tuple, optional) – the result tuple of two output tensors (values, indices)  两个输出张量(值，索引)的结果元组

In [135]:
import torch
torch.manual_seed(666)
a = torch.randint(10, (5,))
print(a)
torch.mode(a,0)

tensor([0, 4, 9, 8, 4])


torch.return_types.mode(
values=tensor(4),
indices=tensor(4))

## norm
返回给定张量的矩阵范数或向量范数。

**定义**：  
torch.norm(input, p='fro', dim=None, keepdim=False, out=None, dtype=None)

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- p (int, float, inf, -inf, 'fro', 'nuc', optional) – fro(Frobenius norm)、nuc(nuclear norm)、Number(sum(abs(x)**ord)**(1./ord))

- dim (int, tuple of ints, list of ints, optional) – Specifies which dimension or dimensions of input to calculate the norm across. If dim is None, the norm will be calculated across all dimensions of input. If the norm type indicated by p does not support the specified number of dimensions, an error will occur.  指定在输入的哪个或哪个维度上计算范数

- keepdim (bool, optional) – whether the output tensors have dim retained or not. Ignored if dim = None and out = None. Default: False  输出张量是否保留dim

- out (Tensor, optional) – the output tensor. Ignored if dim = None and out = None.  输出张量

- dtype (torch.dtype, optional) – the desired data type of returned tensor. If specified, the input tensor is casted to dtype while performing the operation. Default: None.  返回张量的期望数据类型


In [139]:
import torch
import torch
a = torch.tensor([[3., 4],
                  [1, 3]])
torch.norm(a, dim=1)

tensor([5.0000, 3.1623])

## nansum
返回所有元素的和，将非数字(nan)处理为零。

**定义**：  
torch.nansum(input, *, dtype=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- dim (int or tuple of ints, optional) – the dimension or dimensions to reduce. If None, all dimensions are reduced.  要缩减的维度

- keepdim (bool) – whether the output tensor has dim retained or not.  输出张量是否保留dim。

- dtype (torch.dtype, optional) – the desired data type of returned tensor. If specified, the input tensor is casted to dtype before the operation is performed. This is useful for preventing data type overflows. Default: None.  返回张量的期望数据类型

In [140]:
import torch
a = torch.tensor([1., 2., float('nan'), 4.])
torch.nansum(a)

tensor(7.)

## prod
返回输入张量中所有元素的乘积。

**定义**：  
torch.prod(input, *, dtype=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- dim (int or tuple of ints, optional) – the dimension or dimensions to reduce. If None, all dimensions are reduced.  要缩减的维度

- keepdim (bool) – whether the output tensor has dim retained or not.  输出张量是否保留dim。

- dtype (torch.dtype, optional) – the desired data type of returned tensor. If specified, the input tensor is casted to dtype before the operation is performed. This is useful for preventing data type overflows. Default: None.  返回张量的期望数据类型

In [142]:
import torch
a = torch.randn(4, 2)
print(a)
torch.prod(a, 1)

tensor([[ 0.7523, -0.2576],
        [ 0.3773,  0.0753],
        [-1.1425,  0.0812],
        [-0.7525,  1.9844]])


tensor([-0.1938,  0.0284, -0.0928, -1.4934])

## quantile
计算输入张量的每一行的第q个分位数。

**定义**：  
torch.quantile(input, q, dim=None, keepdim=False, *, interpolation='linear', out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- q (float or Tensor) – a scalar or 1D tensor of values in the range [0, 1].  范围为[0,1]的标量或一维张量

- dim (int) – the dimension to reduce.  要缩减的维度

- keepdim (bool) – whether the output tensor has dim retained or not.  输出张量是否保留dim

- interpolation (str) – interpolation method to use when the desired quantile lies between two data points. Can be linear, lower, higher, midpoint and nearest. Default is linear.  当所需分位数位于两个数据点之间时使用的插值方法。

- out (Tensor, optional) – the output tensor.  输出张量。

In [146]:
import torch
torch.manual_seed(666)
a = torch.randn(2, 3)
print(a)
# q = torch.tensor([0.25, 0.5, 0.75])
# torch.quantile(a, q, dim=1, keepdim=True)


# torch.quantile(a, q, dim=1, keepdim=True).shape
# a = torch.arange(4.)
# a
# torch.quantile(a, 0.6, interpolation='linear')
# torch.quantile(a, 0.6, interpolation='lower')
# torch.quantile(a, 0.6, interpolation='higher')
# torch.quantile(a, 0.6, interpolation='midpoint')
# torch.quantile(a, 0.6, interpolation='nearest')
torch.quantile(a, 0.4, interpolation='nearest')

tensor([[-2.1188,  0.0635, -1.4555],
        [-0.0126, -0.1548, -0.0927]])


tensor(-0.1548)

## nanquantile

**定义**：  
torch.nanquantile(input, q, dim=None, keepdim=False, *, interpolation='linear', out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- q (float or Tensor) – a scalar or 1D tensor of values in the range [0, 1].  范围为[0,1]的标量或一维张量

- dim (int) – the dimension to reduce.  要缩减的维度

- keepdim (bool) – whether the output tensor has dim retained or not.  输出张量是否保留dim

- interpolation (str) – interpolation method to use when the desired quantile lies between two data points. Can be linear, lower, higher, midpoint and nearest. Default is linear.  当所需分位数位于两个数据点之间时使用的插值方法。

- out (Tensor, optional) – the output tensor.  输出张量。

In [148]:
import torch
# t = torch.tensor([float('nan'), 1, 2])
# t.quantile(0.5)
# t.nanquantile(0.5)
t = torch.tensor([[float('nan'), float('nan')], [1, 2]])
# t
# t.nanquantile(0.5, dim=0)
t.nanquantile(0.5, dim=1)

tensor([   nan, 1.5000])

## std
求标准差

**定义**：  
torch.std(input, dim=None, *, correction=1, keepdim=False, out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- dim (int or tuple of ints) – the dimension or dimensions to reduce.

- correction (int) – 默认为贝塞尔修正，修正=1。

- keepdim (bool) – whether the output tensor has dim retained or not.  输出张量是否保留dim。

- out (Tensor, optional) – the output tensor.  输出张量


In [176]:
import torch
a = torch.tensor(
    [[ 0.2035,  1.2959,  1.8101, -0.4644],
     [ 1.5027, -0.3270,  0.5905,  0.6538],
     [-1.5745,  1.3330, -0.5596, -0.6548],
     [ 0.1264, -0.5080,  1.6420,  0.1992]])
print(torch.std(a, dim=1, keepdim=True))

(((a-a.mean(dim=1,keepdim=True))**2).sum(dim=1)/(4-1))**0.5

tensor([[1.0311],
        [0.7477],
        [1.2204],
        [0.9087]])


tensor([1.0311, 0.7477, 1.2204, 0.9087])

## std_mean

求标准差和均值

**定义**：  
torch.std_mean(input, dim=None, *, correction=1, keepdim=False, out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- dim (int or tuple of ints) – the dimension or dimensions to reduce.

- correction (int) – 默认为贝塞尔修正，修正=1。

- keepdim (bool) – whether the output tensor has dim retained or not.  输出张量是否保留dim。

- out (Tensor, optional) – the output tensor.  输出张量


In [177]:
import torch
a = torch.tensor(
    [[ 0.2035,  1.2959,  1.8101, -0.4644],
     [ 1.5027, -0.3270,  0.5905,  0.6538],
     [-1.5745,  1.3330, -0.5596, -0.6548],
     [ 0.1264, -0.5080,  1.6420,  0.1992]])
print(torch.std_mean(a, dim=1, keepdim=True))

(((a-a.mean(dim=1,keepdim=True))**2).sum(dim=1)/(4-1))**0.5

(tensor([[1.0311],
        [0.7477],
        [1.2204],
        [0.9087]]), tensor([[ 0.7113],
        [ 0.6050],
        [-0.3640],
        [ 0.3649]]))


tensor([1.0311, 0.7477, 1.2204, 0.9087])

## sum
返回输入张量中所有元素的和。

**定义**：  
torch.sum(input, *, dtype=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- dtype (torch.dtype, optional) – the desired data type of returned tensor. If specified, the input tensor is casted to dtype before the operation is performed. This is useful for preventing data type overflows. Default: None.  返回张量的期望数据类型

In [178]:
import torch
a = torch.randn(1, 3)
print(a)
torch.sum(a)

tensor([[ 2.5916,  0.4542, -0.6890]])


tensor(2.3568)

## unique
返回输入张量的唯一元素。

**定义**：  
torch.unique(input, sorted=True, return_inverse=False, return_counts=False, dim=None) → Tuple[Tensor, Tensor, Tensor]

**参数**：  
- input (Tensor) – the input tensor  输入张量

- sorted (bool) – Whether to sort the unique elements in ascending order before returning as output.  是否对唯一的元素按升序排序，然后作为输出返回。

- return_inverse (bool) – Whether to also return the indices for where elements in the original input ended up in the returned unique list.  是否也返回原始输入元素在返回的唯一列表中结束位置的索引。

- return_counts (bool) – Whether to also return the counts for each unique element.  是否同时返回每个唯一元素的计数。

- dim (int) – the dimension to apply unique. If None, the unique of the flattened input is returned. default: None  应用唯一的维度。如果为None，则返回扁平输入的唯一性。默认值:无

In [179]:
import torch
output = torch.unique(torch.tensor([1, 3, 2, 3], dtype=torch.long))
output

# output, inverse_indices = torch.unique(
#     torch.tensor([1, 3, 2, 3], dtype=torch.long), sorted=True, return_inverse=True)
# output
# inverse_indices

# output, inverse_indices = torch.unique(
#     torch.tensor([[1, 3], [2, 3]], dtype=torch.long), sorted=True, return_inverse=True)
# output
# inverse_indices

tensor([1, 2, 3])

## unique_consecutive
从每组连续的等效元素中除去除第一个元素以外的所有元素。

**定义**：  
torch.unique_consecutive(*args, **kwargs)

**参数**：  
- input (Tensor) – the input tensor  输入张量

- return_inverse (bool) – Whether to also return the indices for where elements in the original input ended up in the returned unique list.  是否也返回原始输入元素在返回的唯一列表中结束位置的索引。

- return_counts (bool) – Whether to also return the counts for each unique element.  是否同时返回每个唯一元素的计数。

- dim (int) – the dimension to apply unique. If None, the unique of the flattened input is returned. default: None  应用唯一的维度。如果为None，则返回扁平输入的唯一性。默认值:无

In [180]:
import torch
x = torch.tensor([1, 1, 2, 2, 3, 1, 1, 2])
output = torch.unique_consecutive(x)
output

# output, inverse_indices = torch.unique_consecutive(x, return_inverse=True)
# output
# inverse_indices

# output, counts = torch.unique_consecutive(x, return_counts=True)
# output
# counts

tensor([1, 2, 3, 1, 2])

## var
求方差

**定义**：  
torch.var(input, dim=None, *, correction=1, keepdim=False, out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- dim (int or tuple of ints) – the dimension or dimensions to reduce.

- correction (int) – 默认为贝塞尔修正，修正=1。

- keepdim (bool) – whether the output tensor has dim retained or not.  输出张量是否保留dim。

- out (Tensor, optional) – the output tensor.  输出张量


In [182]:
import torch
a = torch.tensor(
    [[ 0.2035,  1.2959,  1.8101, -0.4644],
     [ 1.5027, -0.3270,  0.5905,  0.6538],
     [-1.5745,  1.3330, -0.5596, -0.6548],
     [ 0.1264, -0.5080,  1.6420,  0.1992]])
print(torch.var(a, dim=1, keepdim=True))

(((a-a.mean(dim=1,keepdim=True))**2).sum(dim=1)/(4-1))

tensor([[1.0631],
        [0.5590],
        [1.4893],
        [0.8258]])


tensor([1.0631, 0.5590, 1.4893, 0.8258])

## var_mean
求方差

**定义**：  
torch.var_mean(input, dim=None, *, correction=1, keepdim=False, out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- dim (int or tuple of ints) – the dimension or dimensions to reduce.

- correction (int) – 默认为贝塞尔修正，修正=1。

- keepdim (bool) – whether the output tensor has dim retained or not.  输出张量是否保留dim。

- out (Tensor, optional) – the output tensor.  输出张量


In [183]:
import torch
a = torch.tensor(
    [[ 0.2035,  1.2959,  1.8101, -0.4644],
     [ 1.5027, -0.3270,  0.5905,  0.6538],
     [-1.5745,  1.3330, -0.5596, -0.6548],
     [ 0.1264, -0.5080,  1.6420,  0.1992]])
print(torch.var_mean(a, dim=1, keepdim=True))

(((a-a.mean(dim=1,keepdim=True))**2).sum(dim=1)/(4-1))

(tensor([[1.0631],
        [0.5590],
        [1.4893],
        [0.8258]]), tensor([[ 0.7113],
        [ 0.6050],
        [-0.3640],
        [ 0.3649]]))


tensor([1.0631, 0.5590, 1.4893, 0.8258])

## count_nonzero
计数张量输入中沿着给定dim的非零值的数量。如果没有指定dim，那么张量中所有的非零值都被计数。

**定义**：  
torch.count_nonzero(input, dim=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- dim (int or tuple of ints, optional) – Dim or tuple of dims along which to count non-zeros.  用于计数非零。

In [187]:
import torch
x = torch.zeros(3,3)
x[torch.randn(3,3) > 0.5] = 1
print(x)
torch.count_nonzero(x)
# torch.count_nonzero(x, dim=0)

tensor([[1., 0., 0.],
        [0., 0., 0.],
        [0., 0., 1.]])


tensor(2)

# 对比操作(Comparison Ops)

## allclose
判读两个数组是否在误差范围内相等

$$|{\mathrm{input}}-{\mathrm{other}}|\leq{\mathrm{atol}}+{\mathrm{rtol}}\times|{\mathrm{other}}|$$

**定义**：  
torch.allclose(input, other, rtol=1e-05, atol=1e-08, equal_nan=False) → bool

**参数**：  
- input (Tensor) – first tensor to compare  第一个比较的张量

- other (Tensor) – second tensor to compare  第2个比较的张量

- atol (float, optional) – absolute tolerance. Default: 1e-08  绝对误差

- rtol (float, optional) – relative tolerance. Default: 1e-05  相对误差

- equal_nan (bool, optional) – if True, then two NaN s will be considered equal. Default: False  如果为True，则两个NaN将被视为相等。默认值:假

In [190]:
import torch
torch.allclose(torch.tensor([10000., 1e-07]), torch.tensor([10000.1, 1e-08]))
torch.allclose(torch.tensor([10000., 1e-08]), torch.tensor([10000.1, 1e-09]))
# torch.allclose(torch.tensor([1.0, float('nan')]), torch.tensor([1.0, float('nan')]))
# torch.allclose(torch.tensor([1.0, float('nan')]), torch.tensor([1.0, float('nan')]), equal_nan=True)

True

## argsort
返回沿着给定维度按值升序排序张量的索引。

**定义**：  
torch.argsort(input, dim=- 1, descending=False, stable=False) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- dim (int, optional) – the dimension to sort along  排序的维度

- descending (bool, optional) – controls the sorting order (ascending or descending)  控制排序顺序(升序或降序)

- stable (bool, optional) – controls the relative order of equivalent elements  控制相同元素的相对顺序

In [191]:
import torch
a = torch.randn(4, 4)
print(a)
torch.argsort(a, dim=1)

tensor([[-0.1762, -1.3497,  0.0790,  0.0941],
        [-0.2810,  0.4610, -0.2212,  0.1101],
        [-1.3891, -0.4976,  0.1123, -0.4616],
        [-0.2004, -2.0605, -0.0994, -0.4985]])


tensor([[1, 0, 2, 3],
        [0, 2, 3, 1],
        [0, 1, 3, 2],
        [1, 3, 0, 2]])

## eq
计算元素的相等性

**定义**：  
torch.eq(input, other, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- other (Tensor or float) – the tensor or value to compare  要比较的张量或值

- out (Tensor, optional) – the output tensor.  输出张量


In [194]:
import torch
torch.eq(torch.tensor([[1, 2], [3, 4]]), torch.tensor([[1, 1], [4, 4]]))


tensor([[ True, False],
        [False,  True]])

## equal
如果两个张量具有相同的大小和元素，则为True，否则为False。

**定义**：  
torch.equal(input, other) → bool

In [195]:
import torch
torch.equal(torch.tensor([1, 2]), torch.tensor([1, 2]))

True

## ge/greater_equal
input≥other

**定义**：  
torch.ge(input, other, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the tensor to compare  要比较的张量

- other (Tensor or float) – the tensor or value to compare  要比较的张量或值

- out (Tensor, optional) – the output tensor.  输出张量


In [196]:
import torch
torch.ge(torch.tensor([[1, 2], [3, 4]]), torch.tensor([[1, 1], [4, 4]]))

tensor([[ True,  True],
        [False,  True]])

## gt/greater

input>other 

**定义**：  
torch.gt(input, other, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the tensor to compare  要比较的张量

- other (Tensor or float) – the tensor or value to compare  要比较的张量或值

- out (Tensor, optional) – the output tensor.  输出张量

In [197]:
import torch
torch.gt(torch.tensor([[1, 2], [3, 4]]), torch.tensor([[1, 1], [4, 4]]))

tensor([[False,  True],
        [False, False]])

## isclose

$$|{\mathrm{input}}-{\mathrm{other}}|\leq{\mathrm{atol}}+{\mathrm{rtol}}\times|{\mathrm{other}}|$$

**定义**：  
torch.isclose(input, other, rtol=1e-05, atol=1e-08, equal_nan=False) → Tensor

**参数**：  
- input (Tensor) – first tensor to compare  第一个比较的张量

- other (Tensor) – second tensor to compare  第2个比较的张量

- atol (float, optional) – absolute tolerance. Default: 1e-08  绝对误差

- rtol (float, optional) – relative tolerance. Default: 1e-05  相对误差

- equal_nan (bool, optional) – if True, then two NaN s will be considered equal. Default: False  如果为True，则两个NaN将被视为相等。默认值:假

In [198]:
import torch
torch.isclose(torch.tensor((1., 2, 3)), torch.tensor((1 + 1e-10, 3, 4)))
# torch.isclose(torch.tensor((float('inf'), 4)), torch.tensor((float('inf'), 6)), rtol=.5)

tensor([ True, False, False])

## isfinite
返回一个带有布尔元素的新张量，表示每个元素是否为有限元素。

**定义**：  
torch.isfinite(input) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

In [199]:
import torch
torch.isfinite(torch.tensor([1, float('inf'), 2, float('-inf'), float('nan')]))

tensor([ True, False,  True, False, False])

## isin
测试elements中的每个元素是否都在test_elements中。返回一个与元素形状相同的布尔张量，对于test_elements中的元素为True，否则为False。

**定义**：  
torch.isin(torch.tensor([[1, 2], [3, 4]]), torch.tensor([2, 3]))

**参数**：  
- elements (Tensor or Scalar) – Input elements  输入元素

- test_elements (Tensor or Scalar) – Values against which to test for each input element  测试每个输入元素的值

- assume_unique (bool, optional) – If True, assumes both elements and test_elements contain unique elements, which can speed up the calculation. Default: False  如果为True，则假设元素和test_elements都包含唯一元素，这样可以加快计算速度。默认值:假

- invert (bool, optional) – If True, inverts the boolean return tensor, resulting in True values for elements not in test_elements. Default: False  如果为True，则反转布尔返回张量

In [200]:
import torch
torch.isin(torch.tensor([[1, 2], [3, 4]]), torch.tensor([2, 3]))

tensor([[False,  True],
        [ True, False]])

## isinf
测试每个输入元素是否为无穷大(正无穷大或负无穷大)。

**定义**：  
torch.isinf(input) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

In [201]:
import torch
torch.isinf(torch.tensor([1, float('inf'), 2, float('-inf'), float('nan')]))

tensor([False,  True, False,  True, False])

## isposinf
测试输入的每个元素是否为正无穷。

**定义**：  
torch.isposinf(input, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- out (Tensor, optional) – the output tensor.  输出张量


In [202]:
import torch
a = torch.tensor([-float('inf'), float('inf'), 1.2])
torch.isposinf(a)

tensor([False,  True, False])

## isneginf
测试输入的每个元素是否为负无穷。

**定义**：  
torch.isneginf(input, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- out (Tensor, optional) – the output tensor.  输出张量


In [203]:
import torch
a = torch.tensor([-float('inf'), float('inf'), 1.2])
torch.isneginf(a)

tensor([ True, False, False])

## isnan
返回一个新的张量，其中布尔元素表示输入的每个元素是否为NaN。当复数值的实部和/或虚部都为NaN时，则将其视为NaN。

**定义**：  
torch.isnan(input) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

In [204]:
import torch
torch.isnan(torch.tensor([1, float('nan'), 2]))

tensor([False,  True, False])

## isreal
返回一个新的张量，其中布尔元素表示输入的每个元素是否为实值。所有实值类型都被认为是实数。当复数值的虚部为0时，它们被认为是实数。

**定义**：  
torch.isreal(input) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

In [205]:
import torch
torch.isreal(torch.tensor([1, 1+1j, 2+0j]))

tensor([ True, False,  True])

## kthvalue
第k个最小元素

**定义**：  
torch.kthvalue(input, k, dim=None, keepdim=False, *, out=None)

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- k (int) – k for the k-th smallest element  k表示第k个最小的元素

- dim (int, optional) – the dimension to find the kth value along  寻找KTH值的维度

- keepdim (bool) – whether the output tensor has dim retained or not.  输出张量是否保留dim。

- out (Tensor, optional) – the output tensor.  输出张量


In [207]:
import torch
x = torch.arange(1., 6.)
print(x)
torch.kthvalue(x, 4)

# x=torch.arange(1.,7.).resize_(2,3)
# x
# torch.kthvalue(x, 2, 0, True)

tensor([1., 2., 3., 4., 5.])


torch.return_types.kthvalue(
values=tensor(4.),
indices=tensor(3))

## le/less_equal
input≤other 

**定义**：  
torch.le(input, other, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the tensor to compare  要比较的张量

- other (Tensor or Scalar) – the tensor or value to compare  要比较的张量或值
 
- out (Tensor, optional) – the output tensor.  输出张量


In [208]:
import torch
torch.le(torch.tensor([[1, 2], [3, 4]]), torch.tensor([[1, 1], [4, 4]]))

tensor([[ True, False],
        [ True,  True]])

## lt/less
input<other

**定义**：  
torch.lt(input, other, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the tensor to compare  要比较的张量

- other (Tensor or Scalar) – the tensor or value to compare  要比较的张量或值
 
- out (Tensor, optional) – the output tensor.  输出张量

In [209]:
import torch
torch.lt(torch.tensor([[1, 2], [3, 4]]), torch.tensor([[1, 1], [4, 4]]))

tensor([[False, False],
        [ True, False]])

## maximum
计算输入和其他元素的元素最大值。

**定义**：  
torch.maximum(input, other, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- other (Tensor) – the second input tensor  第二个输入张量

- out (Tensor, optional) – the output tensor.  输出张量


In [210]:
import torch
a = torch.tensor((1, 2, -1))
b = torch.tensor((3, 0, 4))
torch.maximum(a, b)

tensor([3, 2, 4])

## minimum
计算输入和其他元素的元素最小值。

**定义**：  
torch.minimum(input, other, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- other (Tensor) – the second input tensor  第二个输入张量

- out (Tensor, optional) – the output tensor.  输出张量


In [211]:
import torch
a = torch.tensor((1, 2, -1))
b = torch.tensor((3, 0, 4))
torch.minimum(a, b)

tensor([ 1,  0, -1])

## fmax
这类似于torch.maximum()，只是它处理NaN的方式不同:如果正在比较的两个元素中有一个是NaN，则将非NaN元素作为最大值。只有当两个元素都是NaN时，才会传播NaN。

**定义**：  
torch.fmax(input, other, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- other (Tensor) – the second input tensor  第二个输入张量

- out (Tensor, optional) – the output tensor.  输出张量

In [212]:
import torch
a = torch.tensor([9.7, float('nan'), 3.1, float('nan')])
b = torch.tensor([-2.2, 0.5, float('nan'), float('nan')])
torch.fmax(a, b)

tensor([9.7000, 0.5000, 3.1000,    nan])

## fmin
这类似于torch.minimum()，只是它处理NaN的方式不同:如果正在比较的两个元素中有一个是NaN，则将非NaN元素作为最小值。只有当两个元素都是NaN时，才会传播NaN。

**定义**：  
torch.fmin(input, other, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- other (Tensor) – the second input tensor  第二个输入张量

- out (Tensor, optional) – the output tensor.  输出张量

In [213]:
import torch
a = torch.tensor([2.2, float('nan'), 2.1, float('nan')])
b = torch.tensor([-9.3, 0.1, float('nan'), float('nan')])
torch.fmin(a, b)

tensor([-9.3000,  0.1000,  2.1000,     nan])

## ne/not_equal
input≠other

**定义**：  
torch.ne(input, other, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the tensor to compare  要比较的张量

- other (Tensor or float) – the tensor or value to compare  要比较的张量或值

- out (Tensor, optional) – the output tensor.  输出张量

In [214]:
import torch
torch.ne(torch.tensor([[1, 2], [3, 4]]), torch.tensor([[1, 1], [4, 4]]))

tensor([[False,  True],
        [ True, False]])

## sort

$$xxxx$$

**定义**：  
torch.sort(input, dim=- 1, descending=False, stable=False, *, out=None)

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- dim (int, optional) – the dimension to sort along  排序的维度

- descending (bool, optional) – controls the sorting order (ascending or descending)  控制排序顺序(升序或降序)

- stable (bool, optional) – makes the sorting routine stable, which guarantees that the order of equivalent elements is preserved.  稳定排序

- out (Tensor, optional) – the output tensor.  输出张量


In [217]:
import torch
torch.manual_seed(666)
x = torch.randn(3, 4)
print(x)
sorted, indices = torch.sort(x)
sorted
# indices

# sorted, indices = torch.sort(x, 0)
# sorted
# indices
# x = torch.tensor([0, 1] * 9)
# x.sort()
# x.sort(stable=True)

tensor([[-2.1188,  0.0635, -1.4555, -0.0126],
        [-0.1548, -0.0927,  2.5916,  0.4542],
        [-0.6890, -0.9962,  0.1856,  0.1476]])


tensor([[-2.1188, -1.4555, -0.0126,  0.0635],
        [-0.1548, -0.0927,  0.4542,  2.5916],
        [-0.9962, -0.6890,  0.1476,  0.1856]])

## topk
返回给定输入张量沿给定维度的k个最大元素。



**定义**：  
torch.topk(input, k, dim=None, largest=True, sorted=True, *, out=None)

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- k (int) – the k in “top-k”   前k个元素

- dim (int, optional) – the dimension to sort along  排序的维度

- largest (bool, optional) – controls whether to return largest or smallest elements  控制是否返回最大或最小的元素

- sorted (bool, optional) – controls whether to return the elements in sorted order  控制是否按排序顺序返回元素

- out (Tensor, optional) – the output tensor.  输出张量


In [219]:
import torch
x = torch.arange(1., 6.)
print(x)
torch.topk(x, 3)

tensor([1., 2., 3., 4., 5.])


torch.return_types.topk(
values=tensor([5., 4., 3.]),
indices=tensor([4, 3, 2]))

## msort
对输入张量的元素沿其第一个维度按值升序排序。
equivalent to torch.sort(t, dim=0)[0]. 


**定义**：  
torch.msort(input, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- out (Tensor, optional) – the output tensor.  输出张量

In [222]:
import torch
torch.manual_seed(666)
t = torch.randn(3, 4)
print(t)
t
torch.msort(t)

tensor([[-2.1188,  0.0635, -1.4555, -0.0126],
        [-0.1548, -0.0927,  2.5916,  0.4542],
        [-0.6890, -0.9962,  0.1856,  0.1476]])


tensor([[-2.1188, -0.9962, -1.4555, -0.0126],
        [-0.6890, -0.0927,  0.1856,  0.1476],
        [-0.1548,  0.0635,  2.5916,  0.4542]])

## xx

$$xxxx$$

**定义**：  


**参数**：  
- input (Tensor) – the input tensor.  输入张量

- out (Tensor, optional) – the output tensor.  输出张量


In [ ]:
import torch


## xx

$$xxxx$$

**定义**：  


**参数**：  
- input (Tensor) – the input tensor.  输入张量

- out (Tensor, optional) – the output tensor.  输出张量


In [ ]:
import torch


## xx

$$xxxx$$

**定义**：  


**参数**：  
- input (Tensor) – the input tensor.  输入张量

- out (Tensor, optional) – the output tensor.  输出张量


In [ ]:
import torch


## xx

$$xxxx$$

**定义**：  


**参数**：  
- input (Tensor) – the input tensor.  输入张量

- out (Tensor, optional) – the output tensor.  输出张量


In [ ]:
import torch


## xx

$$xxxx$$

**定义**：  


**参数**：  
- input (Tensor) – the input tensor.  输入张量

- out (Tensor, optional) – the output tensor.  输出张量


In [ ]:
import torch


## xx

$$xxxx$$

**定义**：  


**参数**：  
- input (Tensor) – the input tensor.  输入张量

- out (Tensor, optional) – the output tensor.  输出张量


In [ ]:
import torch


## xx

$$xxxx$$

**定义**：  


**参数**：  
- input (Tensor) – the input tensor.  输入张量

- out (Tensor, optional) – the output tensor.  输出张量


In [ ]:
import torch


## xx

$$xxxx$$

**定义**：  


**参数**：  
- input (Tensor) – the input tensor.  输入张量

- out (Tensor, optional) – the output tensor.  输出张量


In [ ]:
import torch


## xx

$$xxxx$$

**定义**：  


**参数**：  
- input (Tensor) – the input tensor.  输入张量

- out (Tensor, optional) – the output tensor.  输出张量


In [ ]:
import torch


## xx

$$xxxx$$

**定义**：  


**参数**：  
- input (Tensor) – the input tensor.  输入张量

- out (Tensor, optional) – the output tensor.  输出张量


In [ ]:
import torch


## xx

$$xxxx$$

**定义**：  


**参数**：  
- input (Tensor) – the input tensor.  输入张量

- out (Tensor, optional) – the output tensor.  输出张量


In [ ]:
import torch


## xx

$$xxxx$$

**定义**：  


**参数**：  
- input (Tensor) – the input tensor.  输入张量

- out (Tensor, optional) – the output tensor.  输出张量


In [ ]:
import torch


## xx

$$xxxx$$

**定义**：  


**参数**：  
- input (Tensor) – the input tensor.  输入张量

- out (Tensor, optional) – the output tensor.  输出张量


In [ ]:
import torch


## xx

$$xxxx$$

**定义**：  


**参数**：  
- input (Tensor) – the input tensor.  输入张量

- out (Tensor, optional) – the output tensor.  输出张量


In [ ]:
import torch


## xx

$$xxxx$$

**定义**：  


**参数**：  
- input (Tensor) – the input tensor.  输入张量

- out (Tensor, optional) – the output tensor.  输出张量


In [ ]:
import torch


## xx

$$xxxx$$

**定义**：  


**参数**：  
- input (Tensor) – the input tensor.  输入张量

- out (Tensor, optional) – the output tensor.  输出张量


In [ ]:
import torch


## xx

$$xxxx$$

**定义**：  


**参数**：  
- input (Tensor) – the input tensor.  输入张量

- out (Tensor, optional) – the output tensor.  输出张量


In [ ]:
import torch


## xx

$$xxxx$$

**定义**：  


**参数**：  
- input (Tensor) – the input tensor.  输入张量

- out (Tensor, optional) – the output tensor.  输出张量


In [ ]:
import torch


## xx

$$xxxx$$

**定义**：  


**参数**：  
- input (Tensor) – the input tensor.  输入张量

- out (Tensor, optional) – the output tensor.  输出张量


In [ ]:
import torch


## xx

$$xxxx$$

**定义**：  


**参数**：  
- input (Tensor) – the input tensor.  输入张量

- out (Tensor, optional) – the output tensor.  输出张量


In [ ]:
import torch


## xx

$$xxxx$$

**定义**：  


**参数**：  
- input (Tensor) – the input tensor.  输入张量

- out (Tensor, optional) – the output tensor.  输出张量


In [ ]:
import torch


## xx

$$xxxx$$

**定义**：  


**参数**：  
- input (Tensor) – the input tensor.  输入张量

- out (Tensor, optional) – the output tensor.  输出张量


In [ ]:
import torch
