[![](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/itmorn/AI.handbook/blob/main/DL/torch/nn/MathOperations/MathOperations.ipynb)

# 按元素操作(Pointwise Ops)

## abs/absolute
计算输入中每个元素的绝对值。
$$\text{out}_i=|\text{input}_i|$$

**定义**：  
torch.abs(input, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- out (Tensor, optional) – the output tensor.  输出张量

In [1]:
import torch

torch.abs(torch.tensor([-1, -2, 3]))

tensor([1, 2, 3])

## acos/arccos
计算输入中每个元素的逆余弦。

$$\text{out}_i=\cos^{-1}(\operatorname{input}_i)$$

**定义**：  
torch.acos(input, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- out (Tensor, optional) – the output tensor.  输出张量

In [7]:
import torch
a = torch.randn(4)
print(a)
torch.acos(a)

tensor([-0.3200,  0.1387, -3.0484, -0.4391])


tensor([1.8965, 1.4316,    nan, 2.0254])

## acosh/arccosh
返回输入元素的反双曲余弦的新张量。
$$\text{out}_i=\cosh^{-1}(\operatorname{input}_i)$$

**定义**：  
torch.acosh(input, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- out (Tensor, optional) – the output tensor.  输出张量

In [9]:
import torch
a = torch.randn(4).uniform_(1, 2)
a
torch.acosh(a)

tensor([0.7808, 1.1149, 0.9426, 1.2994])

## add

$$\text{out}_i=\text{input}_i+\text{alpha}\times\text{other}_i$$

**定义**：  
torch.add(input, other, *, alpha=1, out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- other (Tensor or Number) – the tensor or number to add to input.  要添加到输入中的张量或数字

- alpha (Number) – the multiplier for other.  other的乘数

- out (Tensor, optional) – the output tensor.  输出张量

In [15]:
import torch
a = torch.arange(10)
print(a)
torch.add(input=a, other=100)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


tensor([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [16]:
import torch
a = torch.arange(10)
b = torch.ones_like(a)
torch.add(input=a, other=b, alpha=100)

tensor([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

## addcdiv
执行tensor1与tensor2的逐元素除法，将结果乘以标量值并将其添加到输入中。

$$\text{out}_i=\text{input}_i+\text{value}\times\dfrac{\text{tensor}1_i}{\text{tensor}2_i}$$

**定义**：  
torch.addcdiv(input, tensor1, tensor2, *, value=1, out=None) → Tensor

**参数**：  
- input (Tensor) – the tensor to be added  要加的张量

- tensor1 (Tensor) – the numerator tensor  分子张量

- tensor2 (Tensor) – the denominator tensor  分母张量

- value (Number, optional) – multiplier for tensor1 / tensor2.   tensor1 / tensor2的乘子

- out (Tensor, optional) – the output tensor.  输出张量。

In [20]:
import torch
t = torch.randn(1, 3)
t1 = torch.randn(3, 1)
t2 = torch.randn(1, 3)
torch.addcdiv(t, t1, t2, value=0.1)

tensor([[1.7674, 1.3758, 0.6647],
        [1.2805, 1.1478, 0.7561],
        [0.7085, 0.8800, 0.8634]])

## addcmul
执行tensor1与tensor2的元素乘法，将结果乘以标量值并将其添加到输入中。
$$\text{out}_i=\mathrm{input}_i+\mathrm{value}\times\mathrm{tensor1}_i\times\mathrm{tensor2}_i$$

**定义**：  
torch.addcmul(input, tensor1, tensor2, *, value=1, out=None) → Tensor

**参数**：  
- input (Tensor) – the tensor to be added   要加的张量

- tensor1 (Tensor) – the tensor to be multiplied  要乘的张量

- tensor2 (Tensor) – the tensor to be multiplied  要乘的张量

- value (Number, optional) – multiplier for tensor1∗tensor2.  tensor1∗tensor2的乘子

- out (Tensor, optional) – the output tensor.  输出张量。

In [24]:
import torch
t = torch.randn(1, 3)
t1 = torch.randn(3, 1)
t2 = torch.randn(1, 3)
torch.addcmul(t, t1, t2, value=0.1)

tensor([[-1.5827, -0.7309,  2.5973],
        [-1.6367, -0.8269,  2.6584],
        [-1.6840, -0.9110,  2.7119]])

## angle
计算给定输入张量的元素角度(弧度)。
$$\text{out}_i=angle(\operatorname{input}_i)$$

**定义**：  
torch.angle(input, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- out (Tensor, optional) – the output tensor.  输出张量

In [25]:
import torch
torch.angle(torch.tensor([-1 + 1j, -2 + 2j, 3 - 3j]))*180/3.14159

tensor([135.0001, 135.0001, -45.0000])

## asin/arcsin
返回一个带有输入元素arcsin的新张量。

$$\text{out}_i=\sin^{-1}(\operatorname{input}_i)$$

**定义**：  
torch.asin(input, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- out (Tensor, optional) – the output tensor.  输出张量

In [27]:
import torch
a = torch.randn(4)
torch.asin(a)

tensor([   nan, 0.2574, 0.8200, 0.9444])

## asinh/arcsinh

$$\text{out}_i=\sinh^{-1}(\operatorname{input}_i)$$

**定义**：  
torch.asinh(input, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- out (Tensor, optional) – the output tensor.  输出张量

In [28]:
import torch
a = torch.randn(4)
a
torch.asinh(a)

tensor([-0.1693,  1.0191, -0.1025, -0.0610])

## atan/arctan


返回一个带有输入元素arctan值的新张量。

$$\text{out}_i=\tan^{-1}(\operatorname{input}_i)$$

**定义**：  
torch.atan(input, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- out (Tensor, optional) – the output tensor.  输出张量

In [29]:
import torch
a = torch.randn(4)
a
torch.atan(a)

tensor([ 0.7518, -0.7453, -0.4551,  0.6872])

## atanh/arctanh
返回输入元素的反双曲正切的新张量。

$$\text{out}_i=\tanh^{-1}(\text{input}_i)$$

**定义**：  
torch.atanh(input, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- out (Tensor, optional) – the output tensor.  输出张量

In [30]:
import torch
a = torch.randn(4).uniform_(-1, 1)
a
torch.atanh(a)

tensor([-0.0184, -0.6261, -1.1195, -0.7628])

## atan2/arctan2

$$\operatorname{atan2}(y,x)=\begin{cases}\arctan(\frac yx)&\text{if }x>0,\\ \arctan(\frac yx)+\pi&\text{if }x<0\text{ and }y\ge0,\\\arctan(\frac yx)-\pi&\text{if }{x<0}\text{ and }y<0,\\ +\frac\pi2&\text{if }x=0\text{ and }y>0,\\ -\frac\pi2&\operatorname{if }x=0\operatorname{ and }{y<0},\\ \operatorname{undefined}&\text{if }{x=0}\text{ and }y=0.\end{cases}$$

https://stackoverflow.com/questions/35749246/python-atan-or-atan2-what-should-i-use

**定义**：  
torch.atan2(input, other, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the first input tensor  第一个输入张量

- other (Tensor) – the second input tensor  第二个输入张量

- out (Tensor, optional) – the output tensor.  输出张量

In [31]:
import torch
a = torch.randn(4)
a
torch.atan2(a, torch.randn(4))

tensor([-2.7770, -0.7276, -0.1640,  2.9073])

## bitwise_not
计算给定输入张量的位NOT。输入张量必须为整型或布尔型。对于bool张量，它计算逻辑NOT。

**定义**：  
torch.bitwise_not(input, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- out (Tensor, optional) – the output tensor.  输出张量


In [47]:
import torch
torch.bitwise_not(torch.tensor([0, 1, 2], dtype=torch.uint8))
# 0000 0000 -> 1111 1111
# 0000 0001 -> 1111 1110
# 0000 0010 -> 1111 1101 

tensor([255, 254, 253], dtype=torch.uint8)

## bitwise_and
计算输入和其他的位与。输入张量必须为整型或布尔型。对于bool张量，它计算逻辑与。

**定义**：  
torch.bitwise_and(input, other, *, out=None) → Tensor

**参数**：  
- input – the first input tensor  第一个输入张量

- other – the second input tensor  第二个输入张量

- out (Tensor, optional) – the output tensor.  输出张量


In [48]:
import torch
torch.bitwise_and(torch.tensor([-1, -2, 3], dtype=torch.int8),
                  torch.tensor([1, 0, 3], dtype=torch.int8))
torch.bitwise_and(torch.tensor([True, True, False]),
                  torch.tensor([False, True, False]))


tensor([False,  True, False])

## bitwise_or
计算输入和其他的位或。输入张量必须为整型或布尔型。对于bool张量，它计算逻辑或。

**定义**：  
torch.bitwise_or(input, other, *, out=None) → Tensor

**参数**：  
- input – the first input tensor  第一个输入张量

- other – the second input tensor  第二个输入张量

- out (Tensor, optional) – the output tensor.  输出张量


In [49]:
import torch
torch.bitwise_or(torch.tensor([-1, -2, 3], dtype=torch.int8),
                  torch.tensor([1, 0, 3], dtype=torch.int8))
torch.bitwise_or(torch.tensor([True, True, False]),
                  torch.tensor([False, True, False]))


tensor([ True,  True, False])

## bitwise_xor
计算输入和其他的位异或。输入张量必须为整型或布尔型。对于bool张量，它计算逻辑异或。

**定义**：  
torch.bitwise_xor(input, other, *, out=None) → Tensor

**参数**：  
- input – the first input tensor  第一个输入张量

- other – the second input tensor  第二个输入张量

- out (Tensor, optional) – the output tensor.  输出张量


In [50]:
import torch
torch.bitwise_xor(torch.tensor([-1, -2, 3], dtype=torch.int8),
                  torch.tensor([1, 0, 3], dtype=torch.int8))
torch.bitwise_xor(torch.tensor([True, True, False]),
                  torch.tensor([False, True, False]))


tensor([ True, False, False])

## bitwise_xor
计算输入的左算术移位。输入张量必须是整型的。
$$\text{out}_i=\text{input}_i<<\text{other}_i$$

**定义**：  
torch.bitwise_left_shift(input, other, *, out=None) → Tensor

**参数**：  
- input – the first input tensor  第一个输入张量

- other – the second input tensor  第二个输入张量

- out (Tensor, optional) – the output tensor.  输出张量


In [51]:
import torch
print(3<<3)
torch.bitwise_left_shift(torch.tensor([-1, -2, 3], dtype=torch.int8),
                         torch.tensor([1, 0, 3], dtype=torch.int8))


tensor([-2, -2, 24], dtype=torch.int8)

## bitwise_right_shift
计算输入的右算术移位。输入张量必须是整型的。
$$\text{out}_i=\text{input}_i>>\text{other}_i$$

**定义**：  
torch.bitwise_right_shift(input, other, *, out=None) → Tensor

**参数**：  
- input – the first input tensor  第一个输入张量

- other – the second input tensor  第二个输入张量

- out (Tensor, optional) – the output tensor.  输出张量


In [55]:
import torch
print(31 >> 3)
torch.bitwise_right_shift(torch.tensor([-2, -7, 31], dtype=torch.int8),
                          torch.tensor([1, 0, 3], dtype=torch.int8))

3


tensor([-1, -7,  3], dtype=torch.int8)

## ceil
向上取整

$$\text{out}_i=\lceil\operatorname{input}_i\rceil$$

**定义**：  
torch.ceil(input, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- out (Tensor, optional) – the output tensor.  输出张量


In [57]:
import torch
a = torch.randn(4)
print(a)
torch.ceil(a)

tensor([-0.3689, -0.0410,  1.4594, -1.5169])


tensor([-0., -0.,  2., -1.])

## clamp/clip
夹住.  
将输入的所有元素固定在[min, max]范围内

$$y_i=\min(\max(x_i,\min\text{value}_i),\max\text{value}_i)$$

**定义**：  
torch.clamp(input, min=None, max=None, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- min (Number or Tensor, optional) – lower-bound of the range to be clamped to  要夹紧的范围的下限

- max (Number or Tensor, optional) – upper-bound of the range to be clamped to  要夹紧的范围的上限

- out (Tensor, optional) – the output tensor.  输出张量


In [1]:
import torch
a = torch.randn(4)
print(a)
print(torch.clamp(a, min=-0.5, max=0.5))

min = torch.linspace(-1, 1, steps=4)
print(min)
torch.clamp(a, min=min)

tensor([-0.2149,  0.7258,  0.5111, -2.4046])
tensor([-0.2149,  0.5000,  0.5000, -0.5000])
tensor([-1.0000, -0.3333,  0.3333,  1.0000])


tensor([-0.2149,  0.7258,  0.5111,  1.0000])

## conj_physical
计算给定输入张量的元素共轭。

$$\text{out}_i=conj(\text{input}_i)$$

**定义**：  
torch.conj_physical(input, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- out (Tensor, optional) – the output tensor.  输出张量


In [2]:
import torch
torch.conj_physical(torch.tensor([-1 + 1j, -2 + 2j, 3 - 3j]))

tensor([-1.-1.j, -2.-2.j,  3.+3.j])

## copysign
用input的大小和other的符号创建一个新的浮点张量。
$$\operatorname{out}_i=\begin{cases}-|\operatorname{input}_i|&\text{if other}_i\leq-0.0\\ |\operatorname{imput}_i|&\text{if other}_i\geq0.0\end{cases}$$

**定义**：  
torch.copysign(input, other, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- out (Tensor, optional) – the output tensor.  输出张量


In [4]:
import torch
a = torch.randn(4)
print(a)
b = torch.randn(4)
print(b)

torch.copysign(a, b)

tensor([-0.2094, -0.7962,  0.0462,  0.0176])
tensor([-0.3092, -0.5713,  0.0554, -0.6485])


tensor([-0.2094, -0.7962,  0.0462, -0.0176])

## cos

$$\text{out}_i=\cos(\text{input}_i)$$

**定义**：  
torch.cos(input, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- out (Tensor, optional) – the output tensor.  输出张量


In [7]:
import torch
a = torch.randn(4)
torch.cos(a)

tensor([ 0.9805, -0.2416,  0.9493,  0.9866])

## cosh
返回一个包含输入元素的双曲余弦的新张量。

$$\text{out}_i=\cosh(\operatorname{input}_i)$$

**定义**：  
torch.cosh(input, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- out (Tensor, optional) – the output tensor.  输出张量


In [8]:
import torch
a = torch.randn(4)
torch.cosh(a)

tensor([1.0995, 1.3152, 1.9244, 1.8898])

## deg2rad
返回一个新的张量，其中输入的每个元素都从角度转换为弧度。

**定义**：  
torch.deg2rad(input, *, out=None) → Tensor

**参数**：  
- input (Tensor) – the input tensor.  输入张量

- out (Tensor, optional) – the output tensor.  输出张量


In [9]:
import torch
a = torch.tensor([[180.0, -180.0], [360.0, -360.0], [90.0, -90.0]])
torch.deg2rad(a)

tensor([[ 3.1416, -3.1416],
        [ 6.2832, -6.2832],
        [ 1.5708, -1.5708]])

## div/divide

将输入输入的每个元素除以其他输入的相应元素。

$$\text{out}_i=\dfrac{\text{input}_i}{\text{other}_i}$$

**定义**：  
torch.div(input, other, *, rounding_mode=None, out=None) → Tensor

**参数**：  
- input (Tensor) – the dividend 被除数

- other (Tensor or Number) – the divisor 除数

- out (Tensor, optional) – the output tensor.  输出张量

- rounding_mode (str, optional) – None、trunc、floor 

In [10]:
x = torch.tensor([ 0.3810,  1.2774, -0.2972, -0.3719,  0.4637])
print(torch.div(x, 0.5))

a = torch.tensor([[-0.3711, -1.9353, -0.4605, -0.2917],
                  [ 0.1815, -1.0111,  0.9805, -1.5923],
                  [ 0.1062,  1.4581,  0.7759, -1.2344],
                  [-0.1830, -0.0313,  1.1908, -1.4757]])
b = torch.tensor([ 0.8032,  0.2930, -0.8113, -0.2308])
print(torch.div(a, b))

print(torch.div(a, b, rounding_mode='trunc'))

print(torch.div(a, b, rounding_mode='floor'))

tensor([ 0.7620,  2.5548, -0.5944, -0.7438,  0.9274])
tensor([[-0.4620, -6.6051,  0.5676,  1.2639],
        [ 0.2260, -3.4509, -1.2086,  6.8990],
        [ 0.1322,  4.9764, -0.9564,  5.3484],
        [-0.2278, -0.1068, -1.4678,  6.3938]])
tensor([[-0., -6.,  0.,  1.],
        [ 0., -3., -1.,  6.],
        [ 0.,  4., -0.,  5.],
        [-0., -0., -1.,  6.]])
tensor([[-1., -7.,  0.,  1.],
        [ 0., -4., -2.,  6.],
        [ 0.,  4., -1.,  5.],
        [-1., -1., -2.,  6.]])
