[![](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/itmorn/AI.handbook/blob/main/DL/torch/nn/Dropout/Dropout.ipynb)

# Dropout
在训练过程中，使用来自伯努利分布的样本，以概率p随机归零输入张量的一些元素。  
这已被证明是一种有效的技术正则化和防止神经元的共适应，参考论文[Improving neural networks by preventing co-adaptation of feature detectors](https://arxiv.org/abs/1207.0580)。  
此外，在训练期间，输出将按$\frac{1}{1-p}$缩放；在评估过程中，模块只计算一个恒等函数。

**定义**：   
torch.nn.Dropout(p=0.5, inplace=False)

**参数**：  
- p (float) – probability of an element to be zeroed. Default: 0.5  一个元素被归零的概率。默认值:0.5

- inplace (bool) – If set to True, will do this operation in-place. Default: False  如果设置为True，将就地执行此操作。默认值:False

# 图解前向过程
    
<p align="center">
<img src="./imgs/Dropout.svg"
    width="2000" /></p>


In [46]:
# 调包计算
import torch
import torch.nn as nn
torch.manual_seed(666)
input = torch.randn(4, 3)

p=0.4
m = nn.Dropout(p=p)
print("input:\n", input, "\n")

m.train()
output = m(input)
print("output:\n", output, "\n")
print("由output还原input:\n", output*(1-p), "可以看到将输出还原为输入（有值的位置）\n")

m.eval()
output = m(input)
print("output:\n", output, "评估阶段，Dropout不改变输入的值\n")

input:
 tensor([[-2.1188,  0.0635, -1.4555],
        [-0.0126, -0.1548, -0.0927],
        [ 2.5916,  0.4542, -0.6890],
        [-0.9962,  0.1856,  0.1476]]) 

output:
 tensor([[-3.5313,  0.1059, -2.4258],
        [-0.0209, -0.2581, -0.1546],
        [ 4.3193,  0.0000, -1.1484],
        [-1.6603,  0.0000,  0.2461]]) 

由output还原input:
 tensor([[-2.1188,  0.0635, -1.4555],
        [-0.0126, -0.1548, -0.0927],
        [ 2.5916,  0.0000, -0.6890],
        [-0.9962,  0.0000,  0.1476]]) 可以看到将输出还原为输入（有值的位置）

output:
 tensor([[-2.1188,  0.0635, -1.4555],
        [-0.0126, -0.1548, -0.0927],
        [ 2.5916,  0.4542, -0.6890],
        [-0.9962,  0.1856,  0.1476]]) 评估阶段，Dropout不改变输入的值

