[![](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/itmorn/AI.handbook/blob/main/DL/module/Convolution/conv.ipynb)

# Conv1d

对由多个输入平面组成的输入信号应用1D卷积。

定义：  
torch.nn.Conv1d(in_channels, out_channels, kernel_size, stride=1, padding=0, dilation=1, groups=1, bias=True, padding_mode='zeros', device=None, dtype=None)

参数：  
in_channels (int): Number of channels in the input image
输入图像中的通道数

out_channels (int): Number of channels produced by the convolution
卷积产生的通道数

kernel_size (int or tuple): Size of the convolving kernel
卷积核的大小

stride (int or tuple, optional): Stride of the convolution. Default: 1
卷积步幅。默认值:1

padding (int, tuple or str, optional): Padding added to both sides of the input. Default: 0
输入框两边的添加的Padding尺寸。默认值:0

padding_mode (str, optional): ``'zeros'``, ``'reflect'``, ``'replicate'`` or ``'circular'``. Default: ``'zeros'``
添加Padding的方式

dilation (int or tuple, optional): Spacing between kernel elements. Default: 1
卷积核元素之间的间距

groups (int, optional): Number of blocked connections from input channels to output channels. Default: 1
分组卷积

bias (bool, optional): If ``True``, adds a learnable bias to the output. Default: ``True``
添加一个可学习的偏置项



## 图解in_channels、out_channels、kernel_size

<p align="center">
<img src="./imgs/conv1d.svg"
    width="2000" /></p>

In [26]:
import torch
import torch.nn as nn
torch.manual_seed(666)

batch_size = 2
in_channels = 2
sequence_length = 5
input = torch.randn(batch_size, in_channels, sequence_length)
print("input:",input)

m = nn.Conv1d(in_channels=in_channels, out_channels=2, kernel_size=3, stride=1, padding=0,
              dilation=1, groups=1, bias=False, padding_mode='zeros', device=None, dtype=None)

print("m.weight:",m.weight)

output = m(input)
print("output:",output)


input: tensor([[[-0.7747,  0.7926, -0.0062, -0.4377,  0.7148],
         [ 0.3590, -0.1242,  2.0345, -0.3479, -0.4007]],

        [[ 0.8059, -0.1021,  0.3168, -0.8889,  1.1768],
         [ 0.8074,  0.9144,  1.6259, -0.6535, -0.0865]]])
m.weight: Parameter containing:
tensor([[[-0.0783, -0.0347, -0.0791],
         [-0.3860,  0.3662, -0.0087]],

        [[-0.2497, -0.3820, -0.3683],
         [ 0.0319,  0.0496,  0.0144]]], requires_grad=True)
output: tensor([[[-0.1682,  0.7688, -0.9502],
         [-0.0725,  0.0577, -0.0527]],

        [[-0.0756,  0.3155, -0.9533],
         [-0.1843,  0.3324, -0.1548]]], grad_fn=<ConvolutionBackward0>)


In [16]:
import numpy as np
input_part = np.array([
    [-0.7747, 0.7926, -0.0062],
    [0.3590, -0.1242, 2.0345]
])

kernel_1 = np.array([
    [-0.0783, -0.0347, -0.0791],
    [-0.3860, 0.3662, -0.0087]
])
print(np.sum(input_part*kernel_1))

kernel_2 = np.array([
    [-0.2497, -0.3820, -0.3683],
    [0.0319,  0.0496,  0.0144]
])
print(np.sum(input_part*kernel_2))
# 结果和图上会有些许差异，主要是四舍五入所导致的误差

-0.16810998000000002
-0.07245857


## 图解stride
<p align="center">
<img src="./imgs/stride1d.svg"
    width="600" /></p>

In [25]:
import torch
import torch.nn as nn
torch.manual_seed(666)

batch_size = 2
in_channels = 2
sequence_length = 5
input = torch.randn(batch_size, in_channels, sequence_length)
print("input:",input)

m = nn.Conv1d(in_channels=in_channels, out_channels=2, kernel_size=3, stride=2, padding=0,
              dilation=1, groups=1, bias=False, padding_mode='zeros', device=None, dtype=None)

print("m.weight:",m.weight)

output = m(input)
print("output:",output) #可以看到output减少了一列

input: tensor([[[-0.7747,  0.7926, -0.0062, -0.4377,  0.7148],
         [ 0.3590, -0.1242,  2.0345, -0.3479, -0.4007]],

        [[ 0.8059, -0.1021,  0.3168, -0.8889,  1.1768],
         [ 0.8074,  0.9144,  1.6259, -0.6535, -0.0865]]])
m.weight: Parameter containing:
tensor([[[-0.0783, -0.0347, -0.0791],
         [-0.3860,  0.3662, -0.0087]],

        [[-0.2497, -0.3820, -0.3683],
         [ 0.0319,  0.0496,  0.0144]]], requires_grad=True)
output: tensor([[[-0.1682, -0.9502],
         [-0.0725, -0.0527]],

        [[-0.0756, -0.9533],
         [-0.1843, -0.1548]]], grad_fn=<ConvolutionBackward0>)


## 图解padding
<p align="center">
<img src="./imgs/padding1d.svg"
    width="600" /></p>

In [30]:
import torch
import torch.nn as nn
torch.manual_seed(666)

batch_size = 2
in_channels = 2
sequence_length = 5
input = torch.randn(batch_size, in_channels, sequence_length)
print("input:",input)

m = nn.Conv1d(in_channels=in_channels, out_channels=2, kernel_size=3, stride=1, padding=3,
              dilation=1, groups=1, bias=False, padding_mode='zeros', device=None, dtype=None)

print("m.weight:",m.weight)

output = m(input)
print("output:",output) #随着padding的增加，输出的长度越来越长


input: tensor([[[-0.7747,  0.7926, -0.0062, -0.4377,  0.7148],
         [ 0.3590, -0.1242,  2.0345, -0.3479, -0.4007]],

        [[ 0.8059, -0.1021,  0.3168, -0.8889,  1.1768],
         [ 0.8074,  0.9144,  1.6259, -0.6535, -0.0865]]])
m.weight: Parameter containing:
tensor([[[-0.0783, -0.0347, -0.0791],
         [-0.3860,  0.3662, -0.0087]],

        [[-0.2497, -0.3820, -0.3683],
         [ 0.0319,  0.0496,  0.0144]]], requires_grad=True)
output: tensor([[[ 0.0000,  0.0582,  0.0967, -0.1682,  0.7688, -0.9502, -0.0030,
           0.0987,  0.0000],
         [ 0.0000,  0.2905,  0.0201, -0.0725,  0.0577, -0.0527, -0.1947,
          -0.1912,  0.0000]],

        [[ 0.0000, -0.0708,  0.2678, -0.0756,  0.3155, -0.9533,  0.2494,
          -0.0587,  0.0000],
         [ 0.0000, -0.2852, -0.2170, -0.1843,  0.3324, -0.1548, -0.2527,
          -0.2966,  0.0000]]], grad_fn=<ConvolutionBackward0>)


## 图解dilation
<img src="./imgs/dilation1d.svg"
    width="2000" /></p>

In [32]:
import torch
import torch.nn as nn
torch.manual_seed(666)

batch_size = 2
in_channels = 2
sequence_length = 5
input = torch.randn(batch_size, in_channels, sequence_length)
print("input:",input)

m = nn.Conv1d(in_channels=in_channels, out_channels=2, kernel_size=3, stride=1, padding=0,
              dilation=2, groups=1, bias=False, padding_mode='zeros', device=None, dtype=None)

print("m.weight:",m.weight)

output = m(input)
print("output:",output)


input: tensor([[[-0.7747,  0.7926, -0.0062, -0.4377,  0.7148],
         [ 0.3590, -0.1242,  2.0345, -0.3479, -0.4007]],

        [[ 0.8059, -0.1021,  0.3168, -0.8889,  1.1768],
         [ 0.8074,  0.9144,  1.6259, -0.6535, -0.0865]]])
m.weight: Parameter containing:
tensor([[[-0.0783, -0.0347, -0.0791],
         [-0.3860,  0.3662, -0.0087]],

        [[-0.2497, -0.3820, -0.3683],
         [ 0.0319,  0.0496,  0.0144]]], requires_grad=True)
output: tensor([[[ 0.6142],
         [ 0.0392]],

        [[ 0.1173],
         [-0.6504]]], grad_fn=<ConvolutionBackward0>)


In [34]:
import numpy as np
input_part = np.array([
    [-0.7747, -0.0062, 0.7148],
    [0.3590, 2.0345, -0.4007]
])

kernel_1 = np.array([
    [-0.0783, -0.0347, -0.0791],
    [-0.3860, 0.3662, -0.0087]
])
print(np.sum(input_part*kernel_1))

kernel_2 = np.array([
    [-0.2497, -0.3820, -0.3683],
    [0.0319,  0.0496,  0.0144]
])
print(np.sum(input_part*kernel_2))
# 结果和图上会有些许差异，主要是四舍五入所导致的误差

0.61427946
0.03914337000000002


## 图解groups
<img src="./imgs/groups1d.svg"
    width="2000" /></p>

In [51]:
import torch
import torch.nn as nn
torch.manual_seed(666)

batch_size = 2
in_channels = 2
sequence_length = 5
input = torch.randn(batch_size, in_channels, sequence_length)
# print("input:",input)

print("\n----------------------groups=1----------------------:")
m = nn.Conv1d(in_channels=in_channels, out_channels=2, kernel_size=3, stride=1, padding=0,
              dilation=1, groups=1, bias=False, padding_mode='zeros', device=None, dtype=None)

print("m.weight:",m.weight)

output = m(input)
print("output:",output)
print("output.shape:",output.shape)

print("\n----------------------groups=2----------------------:")
m = nn.Conv1d(in_channels=in_channels, out_channels=2, kernel_size=3, stride=1, padding=0,
              dilation=1, groups=2, bias=False, padding_mode='zeros', device=None, dtype=None)

print("m.weight:",m.weight)

output = m(input)
print("output:",output)
print("output.shape:",output.shape)


----------------------groups=1----------------------:
m.weight: Parameter containing:
tensor([[[-0.0783, -0.0347, -0.0791],
         [-0.3860,  0.3662, -0.0087]],

        [[-0.2497, -0.3820, -0.3683],
         [ 0.0319,  0.0496,  0.0144]]], requires_grad=True)
output: tensor([[[-0.1682,  0.7688, -0.9502],
         [-0.0725,  0.0577, -0.0527]],

        [[-0.0756,  0.3155, -0.9533],
         [-0.1843,  0.3324, -0.1548]]], grad_fn=<ConvolutionBackward0>)
output.shape: torch.Size([2, 2, 3])

----------------------groups=2----------------------:
m.weight: Parameter containing:
tensor([[[ 0.2886, -0.0081, -0.0499]],

        [[-0.2986, -0.1184, -0.2425]]], requires_grad=True)
output: tensor([[[-0.2297,  0.2507, -0.0339],
         [-0.5859, -0.1194, -0.4690]],

        [[ 0.2177,  0.0123,  0.0400],
         [-0.7437, -0.3071, -0.3871]]], grad_fn=<ConvolutionBackward0>)
output.shape: torch.Size([2, 2, 3])


In [54]:
import numpy as np
input_part = np.array([
    [-0.7747, 0.7926, -0.0062],
    # [0.3590, -0.1242, 2.0345]
])

kernel_1 = np.array([
    [0.2886, -0.0081, -0.0499]
])
print(np.sum(input_part*kernel_1))

input_part = np.array([
    # [-0.7747, 0.7926, -0.0062],
    [0.3590, -0.1242, 2.0345]
])

kernel_2 = np.array([
    [-0.2986, -0.1184, -0.2425]
])
print(np.sum(input_part*kernel_2))
# 结果和图上会有些许差异，主要是四舍五入所导致的误差

-0.22968910000000003
-0.58585837


# 参考资料

[《人工智能导论：模型与算法》](https://item.jd.com/12653461.html)

[《统计学习方法》](https://item.jd.com/12522197.html)

[《机器学习》](https://item.jd.com/12762673.html)

[FIVE KEY ASSUMPTIONS OF LINEAR REGRESSION ALGORITHM](https://dataaspirant.com/assumptions-of-linear-regression-algorithm/)