[![](/imgs/colab-badge.svg)](https://colab.research.google.com/github/itmorn/AI.handbook/blob/main/DL/module/Convolution/conv.ipynb)

# Conv1d
对由多个输入平面组成的输入信号应用1D卷积。

定义：  
torch.nn.Conv1d(in_channels, out_channels, kernel_size, stride=1, padding=0, dilation=1, groups=1, bias=True, padding_mode='zeros', device=None, dtype=None)

参数：  
in_channels (int): Number of channels in the input image
输入图像中的通道数

out_channels (int): Number of channels produced by the convolution
卷积产生的通道数

kernel_size (int or tuple): Size of the convolving kernel
卷积核的大小

stride (int or tuple, optional): Stride of the convolution. Default: 1
卷积步幅。默认值:1

padding (int, tuple or str, optional): Padding added to both sides of the input. Default: 0
输入框两边的添加的Padding尺寸。默认值:0

padding_mode (str, optional): ``'zeros'``, ``'reflect'``, ``'replicate'`` or ``'circular'``. Default: ``'zeros'``
添加Padding的方式

dilation (int or tuple, optional): Spacing between kernel elements. Default: 1
卷积核元素之间的间距

groups (int, optional): Number of blocked connections from input channels to output channels. Default: 1
分组卷积

bias (bool, optional): If ``True``, adds a learnable bias to the output. Default: ``True``
添加一个可学习的偏置项



## 图解in_channels、out_channels、kernel_size

<p align="center">
<a href="https://raw.githubusercontent.com/itmorn/AI.handbook/main/DL/module/Convolution/imgs/conv1d.svg">
<img src="./imgs/conv1d.svg"
    width="2000" /></a></p>

In [26]:
import torch
import torch.nn as nn
torch.manual_seed(666)

batch_size = 2
in_channels = 2
sequence_length = 5
input = torch.randn(batch_size, in_channels, sequence_length)
print("input:",input)

m = nn.Conv1d(in_channels=in_channels, out_channels=2, kernel_size=3, stride=1, padding=0,
              dilation=1, groups=1, bias=False, padding_mode='zeros', device=None, dtype=None)

print("m.weight:",m.weight)

output = m(input)
print("output:",output)


input: tensor([[[-0.7747,  0.7926, -0.0062, -0.4377,  0.7148],
         [ 0.3590, -0.1242,  2.0345, -0.3479, -0.4007]],

        [[ 0.8059, -0.1021,  0.3168, -0.8889,  1.1768],
         [ 0.8074,  0.9144,  1.6259, -0.6535, -0.0865]]])
m.weight: Parameter containing:
tensor([[[-0.0783, -0.0347, -0.0791],
         [-0.3860,  0.3662, -0.0087]],

        [[-0.2497, -0.3820, -0.3683],
         [ 0.0319,  0.0496,  0.0144]]], requires_grad=True)
output: tensor([[[-0.1682,  0.7688, -0.9502],
         [-0.0725,  0.0577, -0.0527]],

        [[-0.0756,  0.3155, -0.9533],
         [-0.1843,  0.3324, -0.1548]]], grad_fn=<ConvolutionBackward0>)


In [16]:
import numpy as np
input_part = np.array([
    [-0.7747, 0.7926, -0.0062],
    [0.3590, -0.1242, 2.0345]
])

kernel_1 = np.array([
    [-0.0783, -0.0347, -0.0791],
    [-0.3860, 0.3662, -0.0087]
])
print(np.sum(input_part*kernel_1))

kernel_2 = np.array([
    [-0.2497, -0.3820, -0.3683],
    [0.0319,  0.0496,  0.0144]
])
print(np.sum(input_part*kernel_2))
# 结果和图上会有些许差异，主要是四舍五入所导致的误差

-0.16810998000000002
-0.07245857


## 图解stride
<p align="center">
<a href="https://raw.githubusercontent.com/itmorn/AI.handbook/main/DL/module/Convolution/imgs/stride1d.svg">
<img src="./imgs/stride1d.svg"
    width="600" /></a></p>

In [25]:
import torch
import torch.nn as nn
torch.manual_seed(666)

batch_size = 2
in_channels = 2
sequence_length = 5
input = torch.randn(batch_size, in_channels, sequence_length)
print("input:",input)

m = nn.Conv1d(in_channels=in_channels, out_channels=2, kernel_size=3, stride=2, padding=0,
              dilation=1, groups=1, bias=False, padding_mode='zeros', device=None, dtype=None)

print("m.weight:",m.weight)

output = m(input)
print("output:",output) #可以看到output减少了一列

input: tensor([[[-0.7747,  0.7926, -0.0062, -0.4377,  0.7148],
         [ 0.3590, -0.1242,  2.0345, -0.3479, -0.4007]],

        [[ 0.8059, -0.1021,  0.3168, -0.8889,  1.1768],
         [ 0.8074,  0.9144,  1.6259, -0.6535, -0.0865]]])
m.weight: Parameter containing:
tensor([[[-0.0783, -0.0347, -0.0791],
         [-0.3860,  0.3662, -0.0087]],

        [[-0.2497, -0.3820, -0.3683],
         [ 0.0319,  0.0496,  0.0144]]], requires_grad=True)
output: tensor([[[-0.1682, -0.9502],
         [-0.0725, -0.0527]],

        [[-0.0756, -0.9533],
         [-0.1843, -0.1548]]], grad_fn=<ConvolutionBackward0>)


## 图解padding
<p align="center">
<a href="https://raw.githubusercontent.com/itmorn/AI.handbook/main/DL/module/Convolution/imgs/padding1d.svg">
<img src="./imgs/padding1d.svg"
    width="600" /></a></p>

In [30]:
import torch
import torch.nn as nn
torch.manual_seed(666)

batch_size = 2
in_channels = 2
sequence_length = 5
input = torch.randn(batch_size, in_channels, sequence_length)
print("input:",input)

m = nn.Conv1d(in_channels=in_channels, out_channels=2, kernel_size=3, stride=1, padding=3,
              dilation=1, groups=1, bias=False, padding_mode='zeros', device=None, dtype=None)

print("m.weight:",m.weight)

output = m(input)
print("output:",output) #随着padding的增加，输出的长度越来越长


input: tensor([[[-0.7747,  0.7926, -0.0062, -0.4377,  0.7148],
         [ 0.3590, -0.1242,  2.0345, -0.3479, -0.4007]],

        [[ 0.8059, -0.1021,  0.3168, -0.8889,  1.1768],
         [ 0.8074,  0.9144,  1.6259, -0.6535, -0.0865]]])
m.weight: Parameter containing:
tensor([[[-0.0783, -0.0347, -0.0791],
         [-0.3860,  0.3662, -0.0087]],

        [[-0.2497, -0.3820, -0.3683],
         [ 0.0319,  0.0496,  0.0144]]], requires_grad=True)
output: tensor([[[ 0.0000,  0.0582,  0.0967, -0.1682,  0.7688, -0.9502, -0.0030,
           0.0987,  0.0000],
         [ 0.0000,  0.2905,  0.0201, -0.0725,  0.0577, -0.0527, -0.1947,
          -0.1912,  0.0000]],

        [[ 0.0000, -0.0708,  0.2678, -0.0756,  0.3155, -0.9533,  0.2494,
          -0.0587,  0.0000],
         [ 0.0000, -0.2852, -0.2170, -0.1843,  0.3324, -0.1548, -0.2527,
          -0.2966,  0.0000]]], grad_fn=<ConvolutionBackward0>)


## 图解dilation
<p align="center">
<a href="https://raw.githubusercontent.com/itmorn/AI.handbook/main/DL/module/Convolution/imgs/dilation1d.svg">
<img src="./imgs/dilation1d.svg"
    width="2000" /></a></p>

In [32]:
import torch
import torch.nn as nn
torch.manual_seed(666)

batch_size = 2
in_channels = 2
sequence_length = 5
input = torch.randn(batch_size, in_channels, sequence_length)
print("input:",input)

m = nn.Conv1d(in_channels=in_channels, out_channels=2, kernel_size=3, stride=1, padding=0,
              dilation=2, groups=1, bias=False, padding_mode='zeros', device=None, dtype=None)

print("m.weight:",m.weight)

output = m(input)
print("output:",output)


input: tensor([[[-0.7747,  0.7926, -0.0062, -0.4377,  0.7148],
         [ 0.3590, -0.1242,  2.0345, -0.3479, -0.4007]],

        [[ 0.8059, -0.1021,  0.3168, -0.8889,  1.1768],
         [ 0.8074,  0.9144,  1.6259, -0.6535, -0.0865]]])
m.weight: Parameter containing:
tensor([[[-0.0783, -0.0347, -0.0791],
         [-0.3860,  0.3662, -0.0087]],

        [[-0.2497, -0.3820, -0.3683],
         [ 0.0319,  0.0496,  0.0144]]], requires_grad=True)
output: tensor([[[ 0.6142],
         [ 0.0392]],

        [[ 0.1173],
         [-0.6504]]], grad_fn=<ConvolutionBackward0>)


In [34]:
import numpy as np
input_part = np.array([
    [-0.7747, -0.0062, 0.7148],
    [0.3590, 2.0345, -0.4007]
])

kernel_1 = np.array([
    [-0.0783, -0.0347, -0.0791],
    [-0.3860, 0.3662, -0.0087]
])
print(np.sum(input_part*kernel_1))

kernel_2 = np.array([
    [-0.2497, -0.3820, -0.3683],
    [0.0319,  0.0496,  0.0144]
])
print(np.sum(input_part*kernel_2))
# 结果和图上会有些许差异，主要是四舍五入所导致的误差

0.61427946
0.03914337000000002


## 图解groups
<p align="center">
<a href="https://raw.githubusercontent.com/itmorn/AI.handbook/main/DL/module/Convolution/imgs/groups1d.svg">
<img src="./imgs/groups1d.svg"
    width="2000" /></a></p>

In [51]:
import torch
import torch.nn as nn
torch.manual_seed(666)

batch_size = 2
in_channels = 2
sequence_length = 5
input = torch.randn(batch_size, in_channels, sequence_length)
# print("input:",input)

print("\n----------------------groups=1----------------------:")
m = nn.Conv1d(in_channels=in_channels, out_channels=2, kernel_size=3, stride=1, padding=0,
              dilation=1, groups=1, bias=False, padding_mode='zeros', device=None, dtype=None)

print("m.weight:",m.weight)

output = m(input)
print("output:",output)
print("output.shape:",output.shape)

print("\n----------------------groups=2----------------------:")
m = nn.Conv1d(in_channels=in_channels, out_channels=2, kernel_size=3, stride=1, padding=0,
              dilation=1, groups=2, bias=False, padding_mode='zeros', device=None, dtype=None)

print("m.weight:",m.weight)

output = m(input)
print("output:",output)
print("output.shape:",output.shape)


----------------------groups=1----------------------:
m.weight: Parameter containing:
tensor([[[-0.0783, -0.0347, -0.0791],
         [-0.3860,  0.3662, -0.0087]],

        [[-0.2497, -0.3820, -0.3683],
         [ 0.0319,  0.0496,  0.0144]]], requires_grad=True)
output: tensor([[[-0.1682,  0.7688, -0.9502],
         [-0.0725,  0.0577, -0.0527]],

        [[-0.0756,  0.3155, -0.9533],
         [-0.1843,  0.3324, -0.1548]]], grad_fn=<ConvolutionBackward0>)
output.shape: torch.Size([2, 2, 3])

----------------------groups=2----------------------:
m.weight: Parameter containing:
tensor([[[ 0.2886, -0.0081, -0.0499]],

        [[-0.2986, -0.1184, -0.2425]]], requires_grad=True)
output: tensor([[[-0.2297,  0.2507, -0.0339],
         [-0.5859, -0.1194, -0.4690]],

        [[ 0.2177,  0.0123,  0.0400],
         [-0.7437, -0.3071, -0.3871]]], grad_fn=<ConvolutionBackward0>)
output.shape: torch.Size([2, 2, 3])


In [54]:
import numpy as np
input_part = np.array([
    [-0.7747, 0.7926, -0.0062],
    # [0.3590, -0.1242, 2.0345]
])

kernel_1 = np.array([
    [0.2886, -0.0081, -0.0499]
])
print(np.sum(input_part*kernel_1))

input_part = np.array([
    # [-0.7747, 0.7926, -0.0062],
    [0.3590, -0.1242, 2.0345]
])

kernel_2 = np.array([
    [-0.2986, -0.1184, -0.2425]
])
print(np.sum(input_part*kernel_2))
# 结果和图上会有些许差异，主要是四舍五入所导致的误差

-0.22968910000000003
-0.58585837


## 图解bias
<p align="center">
<a href="https://raw.githubusercontent.com/itmorn/AI.handbook/main/DL/module/Convolution/imgs/bias1d.svg">
<img src="./imgs/bias1d.svg"
    width="2000" /></a></p>

In [56]:
import torch
import torch.nn as nn
torch.manual_seed(666)

batch_size = 2
in_channels = 2
sequence_length = 5
input = torch.randn(batch_size, in_channels, sequence_length)
print("input:",input)

m = nn.Conv1d(in_channels=in_channels, out_channels=2, kernel_size=3, stride=1, padding=0,
              dilation=1, groups=1, bias=True, padding_mode='zeros', device=None, dtype=None)

print("m.weight:",m.weight)
print("m.bias:",m.bias)

output = m(input)
print("output:",output)


input: tensor([[[-0.7747,  0.7926, -0.0062, -0.4377,  0.7148],
         [ 0.3590, -0.1242,  2.0345, -0.3479, -0.4007]],

        [[ 0.8059, -0.1021,  0.3168, -0.8889,  1.1768],
         [ 0.8074,  0.9144,  1.6259, -0.6535, -0.0865]]])
m.weight: Parameter containing:
tensor([[[-0.0783, -0.0347, -0.0791],
         [-0.3860,  0.3662, -0.0087]],

        [[-0.2497, -0.3820, -0.3683],
         [ 0.0319,  0.0496,  0.0144]]], requires_grad=True)
m.bias: Parameter containing:
tensor([ 0.2041, -0.0057], requires_grad=True)
output: tensor([[[ 0.0359,  0.9729, -0.7461],
         [-0.0782,  0.0520, -0.0584]],

        [[ 0.1285,  0.5196, -0.7492],
         [-0.1901,  0.3266, -0.1605]]], grad_fn=<ConvolutionBackward0>)


In [59]:
import numpy as np
input_part = np.array([
    [-0.7747, 0.7926, -0.0062],
    [0.3590, -0.1242, 2.0345]
])

kernel_1 = np.array([
    [-0.0783, -0.0347, -0.0791],
    [-0.3860, 0.3662, -0.0087]
])
print(np.sum(input_part*kernel_1)+0.2041)

kernel_2 = np.array([
    [-0.2497, -0.3820, -0.3683],
    [0.0319,  0.0496,  0.0144]
])
print(np.sum(input_part*kernel_2)-0.0057)
# 结果和图上会有些许差异，主要是四舍五入所导致的误差

0.035990019999999984
-0.07815857


# Conv2d
对由多个输入平面组成的输入信号应用2D卷积。

定义：  
torch.nn.Conv2d(in_channels, out_channels, kernel_size, stride=1, padding=0, dilation=1, groups=1, bias=True, padding_mode='zeros', device=None, dtype=None)

参数：  
in_channels (int): Number of channels in the input image
输入图像中的通道数

out_channels (int): Number of channels produced by the convolution
卷积产生的通道数

kernel_size (int or tuple): Size of the convolving kernel
卷积核的大小

stride (int or tuple, optional): Stride of the convolution. Default: 1
卷积步幅。默认值:1

padding (int, tuple or str, optional): Padding added to all four sides of the input. Default: 0
输入框四个边的添加的Padding尺寸。默认值:0

padding_mode (str, optional): ``'zeros'``, ``'reflect'``, ``'replicate'`` or ``'circular'``. Default: ``'zeros'``
添加Padding的方式

dilation (int or tuple, optional): Spacing between kernel elements. Default: 1
卷积核元素之间的间距

groups (int, optional): Number of blocked connections from input channels to output channels. Default: 1
分组卷积

bias (bool, optional): If ``True``, adds a learnable bias to the output. Default: ``True``
添加一个可学习的偏置项



## 图解in_channels、out_channels、kernel_size

<p align="center">
<a href="https://raw.githubusercontent.com/itmorn/AI.handbook/main/DL/module/Convolution/imgs/conv2d.svg">
<img src="./imgs/conv2d.svg"
    width="2000" /></a></p>

In [75]:
import torch
import torch.nn as nn
torch.manual_seed(666)

N = 2  # batch_size
C = 3  # 输入通道数
H = 5  # 输入高度
W = 5  # 输入宽度
input = torch.randn(N, C, H, W)
print("input:", input)

m = nn.Conv2d(in_channels=C, out_channels=2, kernel_size=3, stride=1, padding=0,
              dilation=1, groups=1, bias=False, padding_mode='zeros', device=None, dtype=None)

print("\nm.weight:", m.weight.shape)
print(m.weight)

output = m(input)
print("\noutput:", output.shape)
print(output)


input: tensor([[[[-0.7747,  0.7926, -0.0062, -0.4377,  0.4657],
          [-0.1880, -0.8975,  0.4169, -0.3840,  0.0394],
          [ 0.4869, -0.1476, -0.4459, -0.0336,  0.0221],
          [-0.0550, -0.9645,  0.0285, -0.3170,  1.6640],
          [ 0.7148,  0.3590, -0.1242,  2.0345,  0.9017]],

         [[-1.1558,  0.1841,  0.0934,  0.3168, -0.8889],
          [ 1.1768,  0.8074,  0.8133, -0.8232,  0.7238],
          [ 1.3477,  0.9699, -1.0729, -0.9426, -0.2336],
          [-0.2728,  0.0554,  1.9797,  0.2763,  0.3080],
          [-0.2687, -0.3787, -0.0259, -1.6019,  0.1780]],

         [[-0.7901, -0.2213, -0.9400,  0.4811, -0.5768],
          [ 0.3937,  0.4542, -1.1519,  0.7723, -0.7097],
          [-0.3601, -0.6734,  0.7011, -0.3622, -1.0503],
          [-1.2473,  0.0234,  2.2317, -1.4306, -0.7068],
          [ 0.3444, -0.9902, -0.9458,  0.8957,  0.5061]]],


        [[[ 0.7608,  0.4708,  1.3452,  0.6152, -0.4913],
          [ 0.8625,  0.2028,  0.2190,  0.2907, -0.6460],
          [-0.96

In [77]:
import numpy as np
input_part = np.array([
    [[-0.7747,  0.7926, -0.0062],
     [-0.1880, -0.8975,  0.4169],
     [0.4869, -0.1476, -0.4459]],

    [[-1.1558,  0.1841,  0.0934],
     [1.1768,  0.8074,  0.8133],
     [1.3477,  0.9699, -1.0729]],

    [[-0.7901, -0.2213, -0.9400],
     [0.3937,  0.4542, -1.1519],
     [-0.3601, -0.6734,  0.7011]]
])

kernel_1 = np.array([
    [[0.0762, -0.1053,  0.0464],
     [-0.1129, -0.1230, -0.1107],
     [-0.0667, -0.1036, -0.1620]],

    [[0.0355, -0.1921, -0.0552],
     [0.1444,  0.1322,  0.1732],
     [0.0152, -0.0624,  0.0404]],

    [[0.0104,  0.0387,  0.0363],
     [0.0599,  0.0737, -0.0216],
     [0.1002,  0.1255,  0.1053]]
])
print(np.sum(input_part*kernel_1))

kernel_2 = np.array([
    [[-0.1619,  0.1820, -0.1211],
     [0.1733,  0.1670, -0.0993],
     [0.0322, -0.1547,  0.1175]],

    [[-0.1096, -0.1338,  0.1487],
     [-0.0573,  0.1454,  0.1511],
     [0.1339, -0.0923, -0.1172]],

    [[-0.0601, -0.0949,  0.0579],
     [-0.1379,  0.0424,  0.1474],
     [0.1801, -0.1381, -0.1706]]
])
print(np.sum(input_part*kernel_2))
# 结果和图上会有些许差异，主要是四舍五入所导致的误差


0.23460186000000005
0.25592334000000005


## 图解stride
<p align="center">
<a href="https://raw.githubusercontent.com/itmorn/AI.handbook/main/DL/module/Convolution/imgs/stride2d.svg">
<img src="./imgs/stride2d.svg"
    width="800" /></a></p>

## 图解padding
<p align="center">
<a href="https://raw.githubusercontent.com/itmorn/AI.handbook/main/DL/module/Convolution/imgs/padding2d.svg">
<img src="./imgs/padding2d.svg"
    width="800" /></a></p>

## 图解dilation
<p align="center">
<a href="https://raw.githubusercontent.com/itmorn/AI.handbook/main/DL/module/Convolution/imgs/dilation2d.svg">
<img src="./imgs/dilation2d.svg"
    width="2000" /></a></p>

## 图解groups
<p align="center">
<a href="https://raw.githubusercontent.com/itmorn/AI.handbook/main/DL/module/Convolution/imgs/groups2d.svg">
<img src="./imgs/groups2d.svg"
    width="2000" /></a></p>

# Conv3d
对由多个输入平面组成的输入信号应用2D卷积。

定义：  
torch.nn.Conv2d(in_channels, out_channels, kernel_size, stride=1, padding=0, dilation=1, groups=1, bias=True, padding_mode='zeros', device=None, dtype=None)

参数：  
in_channels (int): Number of channels in the input image
输入图像中的通道数

out_channels (int): Number of channels produced by the convolution
卷积产生的通道数

kernel_size (int or tuple): Size of the convolving kernel
卷积核的大小

stride (int or tuple, optional): Stride of the convolution. Default: 1
卷积步幅。默认值:1

padding (int, tuple or str, optional): Padding added to all four sides of the input. Default: 0
输入框四个边的添加的Padding尺寸。默认值:0

padding_mode (str, optional): ``'zeros'``, ``'reflect'``, ``'replicate'`` or ``'circular'``. Default: ``'zeros'``
添加Padding的方式

dilation (int or tuple, optional): Spacing between kernel elements. Default: 1
卷积核元素之间的间距

groups (int, optional): Number of blocked connections from input channels to output channels. Default: 1
分组卷积

bias (bool, optional): If ``True``, adds a learnable bias to the output. Default: ``True``
添加一个可学习的偏置项



# 参考资料

[《人工智能导论：模型与算法》](https://item.jd.com/12653461.html)

[《统计学习方法》](https://item.jd.com/12522197.html)

[《机器学习》](https://item.jd.com/12762673.html)

[FIVE KEY ASSUMPTIONS OF LINEAR REGRESSION ALGORITHM](https://dataaspirant.com/assumptions-of-linear-regression-algorithm/)