[![](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/itmorn/AI.handbook/blob/main/DL/module/Convolution/ConvTranspose.ipynb)

# ConvTranspose1d 
对由多个输入平面组成的输入图像应用1维转置卷积。

padding (int or tuple, optional): ``dilation * (kernel_size - 1) - padding`` zero-padding will be added to both sides of the input. Default: 0
output_padding (int or tuple, optional): Additional size added to one side
    of the output shape. Default: 0

定义：   
torch.nn.ConvTranspose1d(in_channels, out_channels, kernel_size, stride=1, padding=0, output_padding=0, groups=1, bias=True, dilation=1, padding_mode='zeros', device=None, dtype=None)

参数：  
in_channels (int): Number of channels in the input image
输入图像中的通道数

out_channels (int): Number of channels produced by the convolution
卷积产生的通道数

kernel_size (int or tuple): Size of the convolving kernel
卷积核的大小

stride (int or tuple, optional): Stride of the convolution. Default: 1
卷积步幅。默认值:1

padding (int or tuple, optional): ``dilation * (kernel_size - 1) - padding`` zero-padding will be added to both sides of the input. Default: 0
输入框两边的添加的Padding尺寸。默认值:0

padding_mode (str, optional): ``'zeros'``, ``'reflect'``, ``'replicate'`` or ``'circular'``. Default: ``'zeros'``
添加Padding的方式

dilation (int or tuple, optional): Spacing between kernel elements. Default: 1
卷积核元素之间的间距

groups (int, optional): Number of blocked connections from input channels to output channels. Default: 1
分组卷积

bias (bool, optional): If ``True``, adds a learnable bias to the output. Default: ``True``
添加一个可学习的偏置项



## 图解padding=0, dilation=1, stride=1
<p align="center">
<a href="https://raw.githubusercontent.com/itmorn/AI.handbook/main/DL/module/Convolution/imgsConvTranspose/convTranspose1d.svg">
<img src="./imgsConvTranspose/convTranspose1d.svg"
    width="2000" /></a></p>

In [36]:
# padding=0, dilation=1, stride=1
import torch
import torch.nn as nn
torch.manual_seed(666)

# batch_size = 2 # batch_size不指定默认是1
C_in = 1 # in_channels一般用C_in或C代替
L = 3 # sequence_length
# input = torch.randn(batch_size, in_channels, L)
input = torch.randn(C_in, L)
print("input:",input)

m = nn.ConvTranspose1d(in_channels=C_in, out_channels=1, kernel_size=3, stride=1, padding=0,
              dilation=1, groups=1, bias=False, padding_mode='zeros', device=None, dtype=None)

print("\nm.weight:",m.weight)

output = m(input)
print("\noutput:",output)


import numpy as np
input_part1 = np.array([0, 0, -2.1188])
input_part2 = np.array([0, -2.1188, 0.0635])
input_part3 = np.array([-2.1188, 0.0635, -1.4555])
input_part4 = np.array([0.0635, -1.4555, 0])
input_part5 = np.array([-1.4555, 0, 0])

kernel = np.array([-0.2863, -0.5682, 0.0846])

print(np.sum(input_part1*kernel), np.sum(input_part2*kernel),
      np.sum(input_part3*kernel), np.sum(input_part4*kernel), np.sum(input_part5*kernel))
# 结果和图上会有些许差异，主要是四舍五入所导致的误差

input: tensor([[-2.1188,  0.0635, -1.4555]])

m.weight: Parameter containing:
tensor([[[ 0.0846, -0.5682, -0.2863]]], requires_grad=True)

output: tensor([[-0.1792,  1.2093,  0.4475,  0.8089,  0.4168]],
       grad_fn=<SqueezeBackward1>)
-0.17925047999999996 1.20927426 0.44739643999999995 0.8088350500000001 0.41670965


## 图解padding=1, dilation=1, stride=1
<p align="center">
<a href="https://raw.githubusercontent.com/itmorn/AI.handbook/main/DL/module/Convolution/imgsConvTranspose/convTranspose1d.svg">
<img src="./imgsConvTranspose/convTranspose1d.svg"
    width="2000" /></a></p>

In [40]:
# padding=1, dilation=1, stride=1
import numpy as np
import torch
import torch.nn as nn
torch.manual_seed(666)

C_in = 1  # in_channels一般用C_in或C代替
L = 3  # sequence_length
input = torch.randn(C_in, L)
print("input:", input)

m = nn.ConvTranspose1d(in_channels=C_in, out_channels=1, kernel_size=3, stride=1, padding=1,
                       dilation=1, groups=1, bias=False, padding_mode='zeros', device=None, dtype=None)

print("\nm.weight:", m.weight)

output = m(input)
print("\noutput:", output)


# input_part1 = np.array([0, 0, -2.1188])
input_part2 = np.array([0, -2.1188, 0.0635])
input_part3 = np.array([-2.1188, 0.0635, -1.4555])
input_part4 = np.array([0.0635, -1.4555, 0])
# input_part5 = np.array([-1.4555, 0, 0])

kernel = np.array([-0.2863, -0.5682, 0.0846])

print(
#     np.sum(input_part1*kernel),
    np.sum(input_part2*kernel),
    np.sum(input_part3*kernel),
    np.sum(input_part4*kernel),
#     np.sum(input_part5*kernel)
)
# 结果和图上会有些许差异，主要是四舍五入所导致的误差


input: tensor([[-2.1188,  0.0635, -1.4555]])

m.weight: Parameter containing:
tensor([[[ 0.0846, -0.5682, -0.2863]]], requires_grad=True)

output: tensor([[1.2093, 0.4475, 0.8089]], grad_fn=<SqueezeBackward1>)
1.20927426 0.44739643999999995 0.8088350500000001


## 图解padding=0, dilation=2, stride=1
<p align="center">
<a href="https://raw.githubusercontent.com/itmorn/AI.handbook/main/DL/module/Convolution/imgsConvTranspose/convTranspose1d.svg">
<img src="./imgsConvTranspose/convTranspose1d.svg"
    width="2000" /></a></p>

In [51]:
# padding=0, dilation=2, stride=1
import numpy as np
import torch
import torch.nn as nn
torch.manual_seed(666)

C_in = 1  # in_channels一般用C_in或C代替
L = 3  # sequence_length
input = torch.randn(C_in, L)
print("input:", input)

m = nn.ConvTranspose1d(in_channels=C_in, out_channels=1, kernel_size=3, stride=1, padding=0,
                       dilation=2, groups=1, bias=False, padding_mode='zeros', device=None, dtype=None)

print("\nm.weight:", m.weight)

output = m(input)
print("\noutput:", output)


input_part1 = np.array([0, 0, -2.1188])
input_part2 = np.array([0, 0, 0.0635])
input_part3 = np.array([0, -2.1188, -1.4555])
input_part4 = np.array([0,0.0635, 0])
input_part5 = np.array([-2.1188,-1.4555, 0])
input_part6 = np.array([0.0635,0, 0])
input_part7 = np.array([-1.4555,0, 0])

kernel = np.array([-0.2863, -0.5682, 0.0846])

print(
    np.sum(input_part1*kernel),
    np.sum(input_part2*kernel),
    np.sum(input_part3*kernel),
    np.sum(input_part4*kernel),
    np.sum(input_part5*kernel),
    np.sum(input_part6*kernel),
    np.sum(input_part7*kernel)
)
# 结果和图上会有些许差异，主要是四舍五入所导致的误差


input: tensor([[-2.1188,  0.0635, -1.4555]])

m.weight: Parameter containing:
tensor([[[ 0.0846, -0.5682, -0.2863]]], requires_grad=True)

output: tensor([[-0.1792,  0.0054,  1.0809, -0.0361,  1.4337, -0.0182,  0.4168]],
       grad_fn=<SqueezeBackward1>)
-0.17925047999999996 0.0053720999999999994 1.08076686 -0.0360807 1.43362754 -0.01818005 0.41670965


## 图解padding=0, dilation=1, stride=2
<p align="center">
<a href="https://raw.githubusercontent.com/itmorn/AI.handbook/main/DL/module/Convolution/imgsConvTranspose/convTranspose1d.svg">
<img src="./imgsConvTranspose/convTranspose1d.svg"
    width="2000" /></a></p>

In [53]:
# padding=0, dilation=1, stride=2
import numpy as np
import torch
import torch.nn as nn
torch.manual_seed(666)

C_in = 1  # in_channels一般用C_in或C代替
L = 3  # sequence_length
input = torch.randn(C_in, L)
print("input:", input)

m = nn.ConvTranspose1d(in_channels=C_in, out_channels=1, kernel_size=3, stride=2, padding=0,
                       dilation=1, groups=1, bias=False, padding_mode='zeros', device=None, dtype=None)

print("\nm.weight:", m.weight)

output = m(input)
print("\noutput:", output)


input_part1 = np.array([0, 0, -2.1188])
input_part2 = np.array([0, -2.1188, 0])
input_part3 = np.array([-2.1188, 0, 0.0635])
input_part4 = np.array([0, 0.0635, 0])
input_part5 = np.array([0.0635, 0, -1.4555])
input_part6 = np.array([0, -1.4555, 0])
input_part7 = np.array([-1.4555, 0, 0])

kernel = np.array([-0.2863, -0.5682, 0.0846])

print(
    np.sum(input_part1*kernel),
    np.sum(input_part2*kernel),
    np.sum(input_part3*kernel),
    np.sum(input_part4*kernel),
    np.sum(input_part5*kernel),
    np.sum(input_part6*kernel),
    np.sum(input_part7*kernel)
)
# 结果和图上会有些许差异，主要是四舍五入所导致的误差


input: tensor([[-2.1188,  0.0635, -1.4555]])

m.weight: Parameter containing:
tensor([[[ 0.0846, -0.5682, -0.2863]]], requires_grad=True)

output: tensor([[-0.1792,  1.2040,  0.6121, -0.0361, -0.1413,  0.8270,  0.4168]],
       grad_fn=<SqueezeBackward1>)
-0.17925047999999996 1.20390216 0.6119845399999999 -0.0360807 -0.14131534999999998 0.8270151000000001 0.41670965


# ConvTranspose2d
和ConvTranspose1d同理，部分原理可参考Conv部分

# ConvTranspose3d
和ConvTranspose1d同理，部分原理可参考Conv部分的原理

# 参考资料

[《人工智能导论：模型与算法》](https://item.jd.com/12653461.html)

[《统计学习方法》](https://item.jd.com/12522197.html)

[《机器学习》](https://item.jd.com/12762673.html)

[FIVE KEY ASSUMPTIONS OF LINEAR REGRESSION ALGORITHM](https://dataaspirant.com/assumptions-of-linear-regression-algorithm/)