[![](./imgs/colab-badge.svg)](https://colab.research.google.com/github/itmorn/AI.handbook/blob/main/DL/module/Convolution/ford.ipynb)

# Fold
Combines an array of sliding local blocks into a large containing tensor.
将一个 滑动局部块数组 合并为一个大的张量。

定义：  
torch.nn.Fold(output_size, kernel_size, dilation=1, padding=0, stride=1)

参数：   
output_size (int or tuple): the shape of the spatial dimensions of the output (i.e., ``output.sizes()[2:]``)
输出的空间维度的形状

kernel_size (int or tuple): the size of the sliding blocks
滑动块的大小

stride (int or tuple, optional): the stride of the sliding blocks in the input spatial dimensions. Default: 1
输入空间维度中滑动块的步幅。默认值:1

padding (int or tuple, optional): implicit zero padding to be added on both sides of input. Default: 0
在输入的两边添加隐式的零填充。默认值:0

dilation (int or tuple, optional): a parameter that controls the stride of elements within the neighborhood. Default: 1
控制邻域内元素步幅的参数。默认值:1


## 图解参数
<p align="center">
<a href="https://raw.githubusercontent.com/itmorn/AI.handbook/main/DL/module/Convolution/imgsFord/ford.svg">
<img src="./imgsFord/ford.svg"
    width="2000" /></a></p>

In [1]:
import torch
import torch.nn as nn

x = torch.Tensor( [[[  1,  2,  3,  4],
   					[  5,  6,  7,  8],
   					[  9, 10, 11, 12],
   					[ 13, 14, 15, 16]]])

print("x\n",x)

unfold = nn.Unfold(kernel_size=(2,2), stride=2)
x_unfold = unfold(x) 
print("x_unfold\n",x_unfold)

fold = nn.Fold(output_size=(3,3), kernel_size=(2,2), stride=1, dilation=1,padding=0)
fold = nn.Fold(output_size=(4,4), kernel_size=(4,1), stride=1, dilation=1,padding=0)
fold = nn.Fold(output_size=(4,4), kernel_size=(2,2), stride=2, dilation=1,padding=0)
fold = nn.Fold(output_size=(5,5), kernel_size=(2,2), stride=2, dilation=2,padding=0)
fold = nn.Fold(output_size=(3,3), kernel_size=(2,2), stride=2, dilation=2,padding=1)
fold = nn.Fold(output_size=(1,1), kernel_size=(2,2), stride=2, dilation=2,padding=2)

x_fold = fold(x_unfold)
print("x_fold\n",x_fold)



x
 tensor([[[ 1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.],
         [ 9., 10., 11., 12.],
         [13., 14., 15., 16.]]])
x_unfold
 tensor([[ 1.,  3.,  9., 11.],
        [ 2.,  4., 10., 12.],
        [ 5.,  7., 13., 15.],
        [ 6.,  8., 14., 16.]])
x_fold
 tensor([[[34.]]])
