[![](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/itmorn/AI.handbook/blob/main/DL/module/Convolution/unford.ipynb)

# Unfold
从batched input tensor中提取滑动局部块。

定义：  
torch.nn.Unfold(kernel_size, dilation=1, padding=0, stride=1)

参数：   
kernel_size (int or tuple): the size of the sliding blocks
滑动块的大小

stride (int or tuple, optional): the stride of the sliding blocks in the input spatial dimensions. Default: 1
输入空间维度中滑动块的步幅。默认值:1

padding (int or tuple, optional): implicit zero padding to be added on both sides of input. Default: 0
在输入的两边添加隐式的零填充。默认值:0

dilation (int or tuple, optional): a parameter that controls the stride of elements within the neighborhood. Default: 1
控制邻域内元素步幅的参数。默认值:1


## 图解kernel_size=(3,3)、padding=0、stride=1、dilation=1
<p align="center">
<a href="https://raw.githubusercontent.com/itmorn/AI.handbook/main/DL/module/Convolution/imgsUnford/unford.svg">
<img src="./imgsUnford/unford.svg"
    width="2000" /></a></p>

In [18]:
import torch
import torch.nn as nn
torch.manual_seed(666)

input = torch.randn(3, 4, 4) #BCHW
print("input:\n",input,"\n")

unfold = nn.Unfold(kernel_size=(3, 3),padding=0,stride=1,dilation=1)

output = unfold(input)
print("output:\n",output,"\n")

print(output.size())

input:
 tensor([[[-0.7747,  0.7926, -0.0062, -0.4377],
         [ 0.4657, -0.1880, -0.8975,  0.4169],
         [-0.3840,  0.0394,  0.4869, -0.1476],
         [-0.4459, -0.0336,  0.0221, -0.0550]],

        [[-0.9645,  0.0285, -0.3170,  1.6640],
         [ 0.7148,  0.3590, -0.1242,  2.0345],
         [ 0.9017, -1.1558,  0.1841,  0.0934],
         [ 0.3168, -0.8889,  1.1768,  0.8074]],

        [[ 0.8133, -0.8232,  0.7238,  1.3477],
         [ 0.9699, -1.0729, -0.9426, -0.2336],
         [-0.2728,  0.0554,  1.9797,  0.2763],
         [ 0.3080, -0.2687, -0.3787, -0.0259]]]) 

output:
 tensor([[-0.7747,  0.7926,  0.4657, -0.1880],
        [ 0.7926, -0.0062, -0.1880, -0.8975],
        [-0.0062, -0.4377, -0.8975,  0.4169],
        [ 0.4657, -0.1880, -0.3840,  0.0394],
        [-0.1880, -0.8975,  0.0394,  0.4869],
        [-0.8975,  0.4169,  0.4869, -0.1476],
        [-0.3840,  0.0394, -0.4459, -0.0336],
        [ 0.0394,  0.4869, -0.0336,  0.0221],
        [ 0.4869, -0.1476,  0.0221, -0.0550

## 图解kernel_size=(4,2)、padding=0、stride=1、dilation=1
<p align="center">
<a href="https://raw.githubusercontent.com/itmorn/AI.handbook/main/DL/module/Convolution/imgsUnford/unford.svg">
<img src="./imgsUnford/unford.svg"
    width="2000" /></a></p>

In [19]:
import torch
import torch.nn as nn
torch.manual_seed(666)

input = torch.randn(3, 4, 4) #BCHW
print("input:\n",input,"\n")

unfold = nn.Unfold(kernel_size=(4, 2),padding=0,stride=1,dilation=1)

output = unfold(input)
print("output:\n",output,"\n")

print(output.size())

input:
 tensor([[[-0.7747,  0.7926, -0.0062, -0.4377],
         [ 0.4657, -0.1880, -0.8975,  0.4169],
         [-0.3840,  0.0394,  0.4869, -0.1476],
         [-0.4459, -0.0336,  0.0221, -0.0550]],

        [[-0.9645,  0.0285, -0.3170,  1.6640],
         [ 0.7148,  0.3590, -0.1242,  2.0345],
         [ 0.9017, -1.1558,  0.1841,  0.0934],
         [ 0.3168, -0.8889,  1.1768,  0.8074]],

        [[ 0.8133, -0.8232,  0.7238,  1.3477],
         [ 0.9699, -1.0729, -0.9426, -0.2336],
         [-0.2728,  0.0554,  1.9797,  0.2763],
         [ 0.3080, -0.2687, -0.3787, -0.0259]]]) 

output:
 tensor([[-0.7747,  0.7926, -0.0062],
        [ 0.7926, -0.0062, -0.4377],
        [ 0.4657, -0.1880, -0.8975],
        [-0.1880, -0.8975,  0.4169],
        [-0.3840,  0.0394,  0.4869],
        [ 0.0394,  0.4869, -0.1476],
        [-0.4459, -0.0336,  0.0221],
        [-0.0336,  0.0221, -0.0550],
        [-0.9645,  0.0285, -0.3170],
        [ 0.0285, -0.3170,  1.6640],
        [ 0.7148,  0.3590, -0.1242],
    

## 图解kernel_size=(3,3)、padding=1、stride=1、dilation=1
<p align="center">
<a href="https://raw.githubusercontent.com/itmorn/AI.handbook/main/DL/module/Convolution/imgsUnford/unford.svg">
<img src="./imgsUnford/unford.svg"
    width="2000" /></a></p>

In [22]:
import torch
import torch.nn as nn
torch.manual_seed(666)

input = torch.randn(3, 4, 4) #BCHW
print("input:\n",input,"\n")

unfold = nn.Unfold(kernel_size=(3, 3),padding=1,stride=1,dilation=1)
output = unfold(input)
print("output:\n",output,"\n")

print(output.size())

input:
 tensor([[[-0.7747,  0.7926, -0.0062, -0.4377],
         [ 0.4657, -0.1880, -0.8975,  0.4169],
         [-0.3840,  0.0394,  0.4869, -0.1476],
         [-0.4459, -0.0336,  0.0221, -0.0550]],

        [[-0.9645,  0.0285, -0.3170,  1.6640],
         [ 0.7148,  0.3590, -0.1242,  2.0345],
         [ 0.9017, -1.1558,  0.1841,  0.0934],
         [ 0.3168, -0.8889,  1.1768,  0.8074]],

        [[ 0.8133, -0.8232,  0.7238,  1.3477],
         [ 0.9699, -1.0729, -0.9426, -0.2336],
         [-0.2728,  0.0554,  1.9797,  0.2763],
         [ 0.3080, -0.2687, -0.3787, -0.0259]]]) 

output:
 tensor([[ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000, -0.7747,  0.7926, -0.0062,
          0.0000,  0.4657, -0.1880, -0.8975,  0.0000, -0.3840,  0.0394,  0.4869],
        [ 0.0000,  0.0000,  0.0000,  0.0000, -0.7747,  0.7926, -0.0062, -0.4377,
          0.4657, -0.1880, -0.8975,  0.4169, -0.3840,  0.0394,  0.4869, -0.1476],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.7926, -0.0062, -0.4377,  0.0000,
    

## 图解kernel_size=(3,3)、padding=0、stride=2、dilation=1
<p align="center">
<a href="https://raw.githubusercontent.com/itmorn/AI.handbook/main/DL/module/Convolution/imgsUnford/unford.svg">
<img src="./imgsUnford/unford.svg"
    width="2000" /></a></p>

In [25]:
import torch
import torch.nn as nn
torch.manual_seed(666)

input = torch.randn(3, 4, 4) #BCHW
print("input:\n",input,"\n")

unfold = nn.Unfold(kernel_size=(3, 3),padding=0,stride=2,dilation=1)

output = unfold(input)
print("output:\n",output,"\n")

print(output.size())

input:
 tensor([[[-0.7747,  0.7926, -0.0062, -0.4377],
         [ 0.4657, -0.1880, -0.8975,  0.4169],
         [-0.3840,  0.0394,  0.4869, -0.1476],
         [-0.4459, -0.0336,  0.0221, -0.0550]],

        [[-0.9645,  0.0285, -0.3170,  1.6640],
         [ 0.7148,  0.3590, -0.1242,  2.0345],
         [ 0.9017, -1.1558,  0.1841,  0.0934],
         [ 0.3168, -0.8889,  1.1768,  0.8074]],

        [[ 0.8133, -0.8232,  0.7238,  1.3477],
         [ 0.9699, -1.0729, -0.9426, -0.2336],
         [-0.2728,  0.0554,  1.9797,  0.2763],
         [ 0.3080, -0.2687, -0.3787, -0.0259]]]) 

output:
 tensor([[-0.7747],
        [ 0.7926],
        [-0.0062],
        [ 0.4657],
        [-0.1880],
        [-0.8975],
        [-0.3840],
        [ 0.0394],
        [ 0.4869],
        [-0.9645],
        [ 0.0285],
        [-0.3170],
        [ 0.7148],
        [ 0.3590],
        [-0.1242],
        [ 0.9017],
        [-1.1558],
        [ 0.1841],
        [ 0.8133],
        [-0.8232],
        [ 0.7238],
        [ 0.

## 图解kernel_size=(3,3)、padding=0、stride=1、dilation=2
<p align="center">
<a href="https://raw.githubusercontent.com/itmorn/AI.handbook/main/DL/module/Convolution/imgsUnford/unford.svg">
<img src="./imgsUnford/unford.svg"
    width="2000" /></a></p>

In [27]:
import torch
import torch.nn as nn
torch.manual_seed(666)

input = torch.randn(3, 5, 5) #BCHW
print("input:\n",input,"\n")

unfold = nn.Unfold(kernel_size=(3, 3),padding=0,stride=1,dilation=2)

output = unfold(input)
print("output:\n",output,"\n")

print(output.size())

input:
 tensor([[[-0.7747,  0.7926, -0.0062, -0.4377,  0.4657],
         [-0.1880, -0.8975,  0.4169, -0.3840,  0.0394],
         [ 0.4869, -0.1476, -0.4459, -0.0336,  0.0221],
         [-0.0550, -0.9645,  0.0285, -0.3170,  1.6640],
         [ 0.7148,  0.3590, -0.1242,  2.0345,  0.9017]],

        [[-1.1558,  0.1841,  0.0934,  0.3168, -0.8889],
         [ 1.1768,  0.8074,  0.8133, -0.8232,  0.7238],
         [ 1.3477,  0.9699, -1.0729, -0.9426, -0.2336],
         [-0.2728,  0.0554,  1.9797,  0.2763,  0.3080],
         [-0.2687, -0.3787, -0.0259, -1.6019,  0.1780]],

        [[-0.7901, -0.2213, -0.9400,  0.4811, -0.5768],
         [ 0.3937,  0.4542, -1.1519,  0.7723,  0.2121],
         [-0.5884, -0.2218,  0.5193, -1.1982,  0.8625],
         [ 0.2028,  0.2190, -0.2499,  0.9205, -0.8619],
         [ 0.3163, -0.5174, -0.0523,  0.7585,  1.3658]]]) 

output:
 tensor([[-0.7747],
        [-0.0062],
        [ 0.4657],
        [ 0.4869],
        [-0.4459],
        [ 0.0221],
        [ 0.7148],
  