[![](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/itmorn/AI.handbook/blob/main/DL/module/Pooling/MaxUnpool.ipynb)

# MaxUnpool2d
Computes a partial inverse of MaxPool2d.
MaxPool2d is not fully invertible, since the non-maximal values are lost.
MaxUnpool2d takes in as input the output of MaxPool2d including the indices of the maximal values and computes a partial inverse in which all non-maximal values are set to zero.

MaxPool2d的逆计算，主要是用来恢复池化之前形状的。
MaxPool2d不是完全可逆的，因为非最大值会丢失。
MaxUnpool2d将MaxPool2d的输出作为输入，包括最大值的索引，并计算部分逆，其中所有非最大值都设置为零。

定义：       
torch.nn.MaxUnpool2d(kernel_size, stride=None, padding=0)

参数：  
kernel_size (int or tuple): Size of the max pooling window.

stride (int or tuple): Stride of the max pooling window. It is set to :attr:`kernel_size` by default.

padding (int or tuple): Padding that was added to the input


## 图解参数

<p align="center">
<a href="https://raw.githubusercontent.com/itmorn/AI.handbook/main/DL/module/Pooling/imgsMaxUnpool/MaxUnpool.svg">
<img src="./imgsMaxUnpool/MaxUnpool.svg"
    width="2000" /></a></p>

In [12]:
import torch
import torch.nn as nn

input = torch.torch.tensor([[[[1.,  2.,  3., 4., 5.],
                              [6.,  7.,  8., 9., 10.],
                              [11., 12., 13., 14., 15.],
                              [16., 17., 18., 19., 20.]]]])
print("input:\n", input)

pool = nn.MaxPool2d(kernel_size=2, stride=2, return_indices=True)
output_pool, indices_pool = pool(input)
print("output_pool:\n", output_pool)

unpool = nn.MaxUnpool2d(kernel_size=2, stride=2)
output_unpool = unpool(output_pool, indices_pool, output_size=input.size())
print("unpool:\n", output_unpool)

input:
 tensor([[[[ 1.,  2.,  3.,  4.,  5.],
          [ 6.,  7.,  8.,  9., 10.],
          [11., 12., 13., 14., 15.],
          [16., 17., 18., 19., 20.]]]])
output_pool:
 tensor([[[[ 7.,  9.],
          [17., 19.]]]])
unpool:
 tensor([[[[ 0.,  0.,  0.,  0.,  0.],
          [ 0.,  7.,  0.,  9.,  0.],
          [ 0.,  0.,  0.,  0.,  0.],
          [ 0., 17.,  0., 19.,  0.]]]])


# MaxUnpool1d 、 MaxUnpool3d 和 MaxUnpool2d 类似
部分原理可参考Conv部分（里面有针对1、2、3维更详细的图解）  
[![](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/itmorn/AI.handbook/blob/main/DL/module/Convolution/Conv.ipynb)